src/xwayland-unmanaged.c
src/xwayland.c

Fixes
- #1360
- #1466
Follow-up from
- #1470
Not personally tested but code LGTM.
Originally written by @jlindgren90, I only added the `TODO` comment and modified the commit body to close the 2 issues.

xwayland: prevent crash due to unexpected surface dissociate events

---

include/view.h
src/view.c

When restoring a window's natural geometry during a layout change, require a stricter definition of "visible": either a window's midpoint must be visible, or it will be repositioned. We still respect a mostly-offscreen natural geometry when restoring in an unchanged layout.
Fixes: #1476.

view: ensure midpoint is visible on layout change

---

include/labwc.h
include/xwayland.h
src/xwayland.c

This should allow for follow up work to deal with all window types mentioned at https://specifications.freedesktop.org/wm-spec/wm-spec-1.4.html#idm45649101374512
The PR contains a new function exposed via `xwayland.h` (so it can be used for `-unmanaged` as well):
```c
bool xwayland_surface_contains_window_type(
struct wlr_xwayland_surface *surface, enum atom window_type);
```
It also adds a (`xwayland.c`) listener for `set_window_type` so there is an entry point to not just check at map time but also get notified about dynamic changes of the window types.
The `atom_names` array could be moved to `xwayland.c` rather than living within `xwayland.h`. If we want to keep the `enum atom` argument for the new function the enum would have to stay in `xwayland.h`. An alternative to that would be …

xwayland: support querying more window types

---

NEWS.md

This is improves viewing the xml snippets in the document on GitHub. Not sure though if this document is used at other places where this could conflict.
Before: https://github.com/labwc/labwc/blob/master/NEWS.md#added
After: https://github.com/labwc/labwc/blob/4bd89ad83e2fff5b31e7112ad0d141e4c6a756c3/NEWS.md#added

NEWS.md: wrap xml in markdown code blocks

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/view.h
src/config/rcxml.c
src/interactive.c
src/view.c
src/xdg.c

Clients may wish to know if they are "tiled" and change their sizing behavior accordingly. For example, if https://codeberg.org/dnkl/foot/pulls/1580 is merged, `foot` will insist by default that its size be a multiple of the character cell size unless a window is maximized, fullscreened or tiled. Without notifying the client that the window is tiled, this will cause strange artifacts like a snapped-to-edge window (especially on the right) pulling away from the edge a bit. Clients like `mpv` also seem to care when they are tiled; currently, snapping `mpv` to the edge causes it to render in one of the corners, but after this change, `mpv` will take up the requested region when snapping and render letterbox/pillarbox regions as needed.
I'm not sure if I've caught all cases properly, so this …

view, xdg: notify clients when tiling windows

---

data/labwc-symbolic.svg
data/labwc.desktop
data/labwc.svg
meson.build

A .desktop file was previously added for the labwc session, this adds a
badge for it where it is supported. The .desktop files and the badges
are also moved to `data/`.
Ref: #36, 9fa783e, labwc/labwc-artwork#7
An example from lightdm:
Before:
After:

meson.build: install badges for labwc and migrate to data/ 

---

include/edges.h
src/edges.c
src/resistance.c
src/snap.c

This PR includes three commits that address issues in response to comments on IRC:
1. The first commit is a simple fix that avoids having the window attract to an edge, even when attraction is disabled, when a view approaches another view and then the direction of motion is reversed.
2. The second commit weakens the edge-traversal test, which avoids snapping a window "kitty-corner" to another window. This should reduce user surprise.
3. The third commit more closely mimics Openbox behavior, wherein resistance is only applied against "entry" into the space of another window, or departure of a window from an output. Note that attraction may still grab the trailing edge of a window as it slides past the edge of another view as it moves past the view, but a) this feels kind of natural, and b) …

Refinements to edge behavior

---

include/view.h
src/foreign.c
src/ssd/ssd_extents.c
src/view.c

This PR
- adds a new `view->outputs` bitset to store the calculation result of the intersection with \*all\* outputs the view is currently visible on. It is replacing the intersection in `src/foreign.c` to notify panels about the outputs so the result can be used for other cases like the invisible resize area around windows.
- uses the new `view->outputs` bitset in `src/ssd/ssd_extents.c`
This ensures that the invisible resize handle works across outputs
while still making sure that it won't leak into neighboring ones just
because it is positioned closely to an output edge (either manually,
maximized or snapped via SnapToEdge or SnapToRegion).
Fixes: #1486
Reported-By: @lurch
TODO:

src/ssd: allow invisible resize area across outputs

---

.github/workflows/build.yml

Void's container naming [changed in Fall 2023](https://voidlinux.org/news/2023/08/container-updates.html).

CI: update Void-musl base image

---

include/edges.h
include/view.h
src/edges.c
src/interactive.c
src/resistance.c
src/snap.c

This is mostly the work of @Consolatis, in the [`feature/invisible_edge_snapping`](https://github.com/Consolatis/labwc/tree/feature/invisibile_edge_snapping) branch, to ignore invisible edges when applying resistance:
1. At the start of interactive operations on a particular view, the scene graph is walked to build, for each view, a bitfield of currently visible edges *without regard for the view receiving interaction*.
2. In `edges_find_neighbors`, all views which have no visible edges are skipped completely, unless the `ignore_hidden` flag is set to false (this is done for action-based snapping).
3. The standard validation done by the edge engine is modified so that any invisible edge is effectively moved out to infinity, which should remove it from consideration for snapping.
While I …

edges: do not apply resistance to invisible edges

---

src/output.c

Preliminary fix for
- #1525
Based on the protocol we should also revert all previously correctly committed outputs.
#1528 is doing just that but may cause regressions so we need a short term solution and then deal with potential issues in #1528 after the release.
@Tamaranch
Testing would be greatly appreciated so we can include this preliminary fix for the next release.

src/output.c: notify clients about config errors

---

src/seat.c

Exclude none (zero) from the bitmask test , otherwise the bitmask test is always true when click method is configured to 'none' and as a result the configuration will be skipped.
Follow up from https://github.com/labwc/labwc/pull/1555 (I needed some time to wrap my head around this ;))

seat: fix configure condition for click method

---

docs/rc.xml

Some distro packages install the example config at `/etc/xdg/labwc/rc.xml` and thus users of those packages were having a gap 10 setting by default.
Lets remove the gap from the example config to match our intended default.

docs/rc.xml: remove gap from the example config

---

CONTRIBUTING.md

The wording was wrong. Should be in alphabetical order.

CONTRIBUTING.md: correct the instructions for adding a locale code

---

docs/labwc-actions.5.scd
include/view.h
src/action.c
src/view.c

...when using more than two outputs.
Use (centre-x,centre-y) rather than (1,0) and (0,1).
Fixes: #1582

view: fix view_get_adjacent_output() bug and implement wrap argument for MoveToOutput

---

docs/labwc-config.5.scd
include/common/string-helpers.h
include/config/session.h
src/common/string-helpers.c
src/config/session.c
src/main.c

This came up on IRC and seems like it would be a useful addition.

session: run shutdown script, clean up activation env before exit

---

src/config/session.c

This PR resolves issue #694.
(This is my very first open source contribution.)

session.c: updated dbus activation environment with more env vars

---

docs/labwc.1.scd
include/config/session.h
src/common/parse-bool.c
src/config/session.c
src/main.c

This is an attempt to address https://github.com/labwc/labwc/issues/1530#issuecomment-1975010257 by only updating the dbus/systemd activation environment when the DRM backend is in use or the `LABWC_UPDATE_ACTIVATION_ENV` environment variable explicitly requests an update.

session: only update activation environment when running DRM backend or by explicit request

---

include/input/ime.h
include/labwc.h
src/input/ime.c
src/input/keyboard.c
src/input/meson.build
src/seat.c
src/server.c

This PR adds support for text-input-unstable-v3 protocol and input-method-unstable-v2 protocol.
Addresses #783
This is based on [Sway's implementation](https://github.com/swaywm/sway/blob/master/sway/input/text_input.c), but I made many changes because it had some designs that don't make sense to me, like follows:
-  It uses `sway_text_input.pending_focused_surface` which is used solely for keeping track of focused surface when input-method isn't present and complicates the code.
- When the focused surface is updated, the relay always sends `deactivate` event to input-method for every text-input to send `leave` event.
- When received `commit`/`enable` requests from application, the relay always sends some events to input-method although the focus might be already moved to another …

IME: Support input method (without IME popups)

---

src/input/touch.c

https://github.com/labwc/labwc/issues/1545
This PR uses cursor emulate events to respond to touchscreen input on window headerbars and frames.
I have no idea if this is the correct way to do this, but it seems to work pretty well in my testing. Someone who understands more about how this area of the code works should probably review it, as there is probably a better way to do it!

Use cursor emulate events to handle touch on headerbar

---

include/view.h
src/desktop.c
src/seat.c
src/view.c
src/xwayland-unmanaged.c
src/xwayland.c

Now that we have _NET_WM_WINDOW_TYPE support, we can use it to fix focus issues with Globally Active windows more properly, as we've discussed before (https://github.com/labwc/labwc/issues/1139#issuecomment-1763191003), and remove various hacks/workarounds that are no longer needed.
The first commit is the important one. The others aren't urgent but are nice cleanups, and will be more relevant when the wlroots support is in place to merge #1142. Details in the commit messages.
Fixes:
- #1139
- #1341

xwayland: use _NET_WM_WINDOW_TYPE to fix focus issues

---

include/labwc.h
include/output-virtual.h
src/action.c
src/meson.build
src/output-virtual.c
src/output.c

This commit moves the virtual output related functions
into their own file at `src/output-virtual.c` with its
own include file to reduce `include/labwc.h` bit by bit.
Additionally, it removes the need to keep the
`server->headless.pending_output_name` char array around
by temporarily disconnecting the handler when creating a
new virtual output. This allows to set the output name
right in the `output_virtual_add()` call rather than to
store the pending name until the new output event handler
has been called.
It also makes adding a virtual fallback output easier in
a follow-up PR.

src/output.c: refactor virtual output related functions

---

include/labwc.h
src/xdg.c
src/xwayland.c

This is relevant for touchpad taps with `tapAndDrag` disabled.
When the user taps the client surface (e.g. mpv and un-decorated titlebar of chromium) with the setting above, libinput sends button press & release signals so quickly that the compositor receives move/resize request from the client after the button release signal is processed, so `interactive_finish()` is never called.
Since the checks I added are duplicated in `xdg.c` and `xwayland.c`, maybe it's better to move them into `view-impl-common.c` and share it.
This includes minor style fixes and additional comments on `seat.pressed`.

Ignore move/resize request from clients when the view is not pressed

---

docs/environment
include/output-virtual.h
src/output-virtual.c
src/output.c
src/server.c

Follow-up from
- #1523
Copy from `docs/environment`
```
##
##
```
Things to do:

Add optional headless fallback output

---

README.md

That one was missing in the default bindings.

README.md: add alt-space binding

---

docs/labwc-config.5.scd
include/common/string-helpers.h
src/common/string-helpers.c
src/config/session.c

1. All '*.env' files in an 'environment.d' directory alongside each potential 'environment' file will be parsed and added to the environment.
2. For the purposes of configuration merging, an environment definition exists at one level if either the 'environment' file is defined or its corresponding 'environment.d' contains any valid '*.env' file.
3. Variable declarations of the form "VARIABLE=", with no following value, will be written to the environment as empty strings.
Quick tests show this working, but it hasn't been rigorously tested, and the merge logic needs testing as well.

session: process environment.d and allow empty variables

---

include/input/cursor.h
src/input/cursor.c
src/seat.c

As per https://github.com/labwc/labwc/issues/1587 - this seems to work for reloading cursor size and theme on a labwc --reconfigure.

Reload cursor theme and size on reconfigure

---

src/input/keyboard.c
src/seat.c

...if keymap cannot be created for the provided XKB_DEFAULT_LAYOUT.
If keymap still cannot be created, exit with a helpful message to avoid crash that is hard to understand.
Fixes: https://github.com/stefonarch/lxqt-labwc-session/issues/7

keyboard: use 'us' as fallback for XKB_DEFAULT_LAYOUT

---

src/config/session.c

I was going to make the `error` label more descriptive, but realized we don't even need the label. What's more, we can short-circuit some string parsing when would would just wind up ignoring the results.

session: abort process_line early if line contains no key

---

docs/labwc-actions.5.scd
include/config/default-bindings.h
src/action.c
src/config/rcxml.c

This is an alternative to #1604 that implements my desire to make this a per-action argument. Given that `at_cursor` is ignored for `root-menu`, this could also be a separate option, *e.g.* `ShowClientMenuHere`, which takes no arguments.

action: allow client-menu to open at mouse cursor

---

include/common/buf.h
src/common/buf.c

There is at least one user of the buffer API that reuses a single buffer by just resetting `buf.len` to `0`. This works as long as the new user of the buffer actually adds something to the buffer.
However, if we don't add anything but still provide `buf.buf` to a consumer, the old content will be re-used.
This patch thus adds two new clearing variants to the buffer API:
- `buf_clear()` which doesn't reset the internal allocations
- `buf_reset()` which does free the internal allocations
Additionally, this patch makes `buf_add_char()` public which allows adding single characters to an existing buffer. This will be used in a future PR which implements custom format strings for the OSD.
---
Background:
- https://github.com/labwc/labwc/pull/1623#discussion_r1525966047
This PR doesn't change …

src/common/buf.c: enhance the buffer API

---

CONTRIBUTING.md
po/POTFILES.in
po/ar.po
po/cs.po
po/de.po
po/es.po
po/et.po
po/eu.po
po/fi.po
po/gl.po
po/hu.po
po/id.po
po/it.po
po/ja.po
po/ka.po
po/labwc.pot
po/lt.po
po/nl.po
po/pa.po
po/pl.po
po/pt.po
po/ru.po
po/sv.po
po/tr.po
po/uk.po
po/zh_CN.po
src/config/rcxml.c

Translators - no need to update as "Workspaces" is already covered in `menu.c` and gettext is smart enough to re-use it.
I took the liberty to update all the comments in the `po` files too. tested about 6 locales and all works, including RTL in Arabic (https://github.com/labwc/labwc/issues/1630#issuecomment-2002306206). Would appreciate some CJK testing as I don't have those fonts, but there should be no problem.

NLS: translate "Workspaces" in rcxml.c. closes #1630

---

include/common/font.h
include/common/graphic-helpers.h
include/common/scaled_font_buffer.h
src/common/font.c
src/common/graphic-helpers.c
src/common/scaled_font_buffer.c
src/menu/menu.c
src/ssd/resize_indicator.c
src/ssd/ssd_titlebar.c

After a roundabout discussion[1] with wlroots devs, it's become apparent that subpixel text rendering (a.k.a. "ClearType") does not work properly when rendering over a transparent background, as labwc currently does.
Basically it comes down to the fact that the color of semi-transparent pixels (which is adjusted redder or bluer to compensate for RGB subpixel alignment) depends somewhat on background color. When rendering over transparency, the text engine doesn't know the intended background color and can't adjust the pixel colors correctly.
With Pango/Cairo, the end result can range from grayscale rendering (no subpixel rendering at all) to wrong/oversaturated colors (for example, bright pink pixels when rendering white text on blue background).
This change solves the issue by first …

common: render text buffers with opaque background

---

src/xwayland.c

These views (notifications, floating toolbars, etc.) should not be shown in taskbars/docks/etc. (which are the stated use-case of the wlr-foreign-toplevel protocol).
See also: https://github.com/jlindgren90/qmpanel/issues/7

xwayland: exclude unfocusable views from wlr-foreign-toplevel

---

include/layers.h
src/input/cursor.c
src/layers.c
src/seat.c

Use the following logic:
- Exclusive: Grant regardless of layer. Previously it was only given if in top or overlay layers. Grant if in the same or higher layer than (nearer overlay) any other client with exclusive interactivity.
- On-demand: Grant only if no other layer-shell client has exclusive keyboard interactivity. Previously it was treated the same as exclusive.
- None: Unset focus if the commit associated with the 'none' came from the currently focused layer. Previously it was just unset regardless.
Remove unecessary top/overlay check in seat_set_focus_layer(). Such checks should be made prior to calling the function.

layer: change logic for giving keyboard-interactivity

---

src/xwayland.c

...for example `Fall Guys`. It is believed to be caused by setting override-redirect on an xwayland-surface with a child window, thus breaking the way root-toplevels are obtained.
```
(threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0)
at pthread_kill.c:44
at pthread_kill.c:78
(fmt=0x7739d9f9bb68 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x5a76573f9222 "root", file=file@entry=0x5a76573f9606 "../labwc/src/view.c", line=line@entry=2013, function=function@entry=0x5a7657400320 <__PRETTY_FUNCTION__.14> "view_move_to_front") at assert.c:94
(assertion=assertion@entry=0x5a76573f9222 "root", file=file@entry=0x5a76573f9606 "../labwc/src/view.c", line=line@entry=2013, function=function@entry=0x5a7657400320 <__PRETTY_FUNCTION__.14> "view_move_to_front") …
```

xwayland: fix segv bug when starting game

---

src/xdg-popup.c

Prevents xdg popups from being placed under waybar.
Before:
After:

src/xdg-popup.c: unconstrain popup within usable area

---

docs/labwc-menu.5.scd
include/common/spawn.h
include/menu/menu.h
src/action.c
src/common/spawn.c
src/menu/menu.c
src/server.c

http://openbox.org/wiki/Help:Menus#Pipe_menus
Before merge
There is lots of stuff that needs to be done with menus in general (e.g. making sure we don't have duplicate menu ids, positioning big menus better within usable areas, handling `nr_items * item_height > usable_area->height`)... but let's leave that for separate PRs.

Support pipemenus

---

src/layers.c

...for the following reasons:
1. We interpret 'normal input-focus semantics' for clients with on-demand keyboard interactivity to means that a surface receives input focus on cursor-button-press AND on map (the latter previously missing), just like a normal window would. In this regard, we do not differentiate between layers.
2. Most layer-surfaces set the keyboard interactivity at a similar time to their first (and normally only) map, so the absence of an explicit attempt to focus on map does not make a difference. However, for a long-running layer-shell client (such as lxqt-runner) which sets the interactivity on launch and then maps/unmaps many times throughout its lifetime, a specific focus-attempt is required on map to avoid the client itself having to keep resetting its …

layer: try to set keyboard focus on map

---

include/common/parse-double.h
src/common/meson.build
src/common/parse-double.c
src/config/rcxml.c
src/config/tablet.c

This is my (probably over-engineered) attempt to properly parse floats with regard to locale. We ensure that there is at most one `,` or `.` and, if so, convert it to the locale-dependent separator before parsing with `strtod`. If there are too many separators, or the numeric conversion fails, or there is trailing garbage after the parsed number, an error is emitted and the function does not write any converted value.
I tested some basic inputs with `<mouse><scrollFactor>` and this seems to work as anticipated: `1.05` and `1,05` are both recognized as valid, `1,000.5` and `0.1.2` are both rejected.
Fixes: #1665.

common: validate and properly parse floats

---

src/common/graphic-helpers.c
src/overlay.c
src/theme.c

wlr_scene_rects expect their color to be pre-multiplied while cairo_set_source_rgba() expects them to not be pre-multiplied.
With this patch we now use premultiplied colors internally by default and then reverse it when setting cairo colors.
This ensures the titlebar uses a consistent color in case it was defined with some transparency by the user.
Fixes:
- #1684

Use pre-multiplied colors by default

---

CONTRIBUTING.md
docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all

docs: 80 column lines (where possible), drop trailing whitespace

---

scripts/checkpatch.pl
src/common/font.c

common/font: avoid rendering semi-transparent background twice

---

src/common/scene-helpers.c
src/output.c

Also reduce log spam from failed output commits that can happen for various reasons outside of our control.
Fixes:
- #1667
---
There is also a wip branch [here](https://github.com/Consolatis/labwc/tree/issue/1667_scene_output_assert) which tries to fix this more generally but I am not feeling confident enough with that one for the current point in the dev cycle.

output: ensure we don't run into an assert() on VT switch

---

.github/workflows/build.yml
include/ssd-internal.h
meson.build
meson_options.txt
src/layers.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

This may help uncover potential bugs in the future.
If we end up getting too many false positives we can still disable it again.

CI: enable gcc static analyzer

---

include/edges.h
include/snap-constraints.h
include/snap.h
src/edges.c
src/interactive.c
src/meson.build
src/resistance.c
src/snap-constraints.c
src/snap.c
src/view.c
src/xdg.c

When growing or shrinking a view by snapping to an edge, a client may ignore the requested size and instead keep its original size or substitute a different (possibly constrained) size. In this case, the view may not actually contact the snapped edge, and a subsequent snap attempt will just keep re-trying (and failing) to contact the same ege.
To mitigate this, remember the last-snapped view, snapping direction and offset of the snapping edge in snap.c; when re-attempting a snap for the same view in the same direction, ignore the edge that was last "hit", to allow snapping to progress beyond the problematic edge.
The implementaion considers a single, static cache in an attempt to minimize intrusion into other parts of the program. This means there are some... *edge*... cases where a snap …

snap: cache and ignore last-snapped edge when growing or shrinking

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
include/osd.h
src/action.c
src/config/rcxml.c
src/desktop.c
src/input/keyboard.c
src/meson.build
src/osd.c
src/osd_field.c
src/view.c

field (printf style formatting) to replace the original field formats. I added documentation, and fixed the few style check complaints.
Example:
```
<windowSwitcher preview="no" outlines="no" allWorkspaces="yes">
<fields>
<field content="custom" format="foobar %b %3s %-10o %-20W %-10i %t" width="100%" />
</fields>
</windowSwitcher>
```
Mono space font recommended, along with possibly adjusting width of OSD window, 
can be used in conjunction wiith #1662

OSD window switcher, based on work done by @Consolatis, it uses a custom

---

src/input/cursor.c

Looks like we forgot that one earlier, contrary to emulating cursor buttons (https://github.com/labwc/labwc/blob/master/src/input/cursor.c#L1120) 
From https://github.com/labwc/labwc/issues/1672#issuecomment-2052534441 , found by @DynamoFox

input: notify idle manager when emulating cursor move

---

docs/labwc-theme.5.scd
docs/themerc

- The default value of `osd.bg.color` is `#e1dedb`, as it falls back to `window.active.title.bg.color` (I may be missing some context here)
- "all border colors" in the description of `border.color` sounds like it includes `osd.border.color`

Small fixes in `doc/themerc` and `docs/labwc-theme.5.scd`

---

docs/labwc-theme.5.scd
docs/themerc
include/overlay.h
include/theme.h
src/debug.c
src/overlay.c
src/seat.c
src/theme.c

This PR adds following theme settings:
- `snapping-preview.region.area.color`
- `snapping-preview.edge.area.color`
- `snapping-preview.region.rect-type` (`Auto|Area|Outlines`)
- `snapping-preview.edge.rect-type` (`Auto|Area|Outlines`)
I named the theme entry `rect-type` to make `labwc-theme.5.scd` easy to follow, but maybe it should be just `type`.
I restructured `struct overlay` to allow independent styles for region/edge snapping overlay.
I also added `inactivate_overlay()` as a refactoring.
In the future, maybe we can also make the colors of outlines configurable like:
`snapping-preview.region.outlines.colors: #ffffff,#000000,#ffffff`
In that case, I think the colors of OSD preview should also be configurable.

 overlay: make overlay's style and colors configurable

---

src/common/graphic-helpers.c

This is a follow-up to #1702
Before this change:

graphic-helpers: prevent multi-rect edges from overlapping at corner

---

docs/labwc-theme.5.scd
docs/themerc
include/theme.h
src/osd.c
src/theme.c

Adds theme settings like:
```
osd.window-switcher.preview.border.width: 2
osd.window-switcher.preview.border.color: #ffffff,#00a2ff,#ffffff
```

osd: add theme settings for window-switcher preview

---

docs/labwc-config.5.scd
src/config/session.c

Some people might benefit from reading `environment.d` in sorted order, and that's easy to achieve with `scandir`, a POSIX 2008 routine.

session: sort directory entries in environment.d

---

docs/labwc-config.5.scd
include/view.h
include/window-rules.h
include/xwayland.h
src/config/rcxml.c
src/view.c
src/window-rules.c
src/xdg.c
src/xwayland.c

This builds on #1490. I reverted the hard-coded rules for desktop windows for now. Instead I exposed the feature to users and added heuristics for xdg-shell, as [proposed by @Consolatis](https://github.com/labwc/labwc/compare/master...Consolatis:labwc:feature/window_rule_root_only). See also the [relevant openbox documentation](http://openbox.org/wiki/Help:Applications).
I personally want to use it like this:
```xml
<windowRule type="normal">
<action name="Maximize"/>
</windowRule>
```
It works quite well, but not perfect. For example, the dialog to enter the primary password for thunderbird behaves correctly under xwayland, but not under native wayland. I intentionally kept the description of the internal heurustics in the docs vague so we can refine them later (e.g. based on size …

Implement type filter for window rules

---

docs/labwc-config.5.scd
include/window-rules.h
src/config/rcxml.c
src/window-rules.c
src/xwayland.c

This allows to ignore X11 client side configure requests like positioning and resizing and can be used to fight some X11 applications that persist to have their windows spawn at specific places and sizes.
Fixes:
- #1446
---
I don't really like the runtime `strcmp()` calls with the rules, at some point we could consider moving those to enums instead.

window-rules: add ignoreConfigureRequest

---

include/action.h
include/button/common.h
include/common/scaled_scene_buffer.h
include/config/default-bindings.h
include/config/touch.h
include/labwc.h
include/window-rules.h
src/debug.c
src/input/keyboard.c
src/seat.c

I switched to clangd from VSCode's intellisense today and it showed me some errors regarding headers.
- Added headers like <stddef.h> for `NULL`, <wayland-util.h> for `wl_link` and <stdbool.h> for `bool`.
- Fixed circular dependency of `labwc.h` and `ime.h`

Resolve errors from clangd

---

docs/labwc-config.5.scd
docs/labwc-theme.5.scd
docs/rc.xml.all
docs/themerc
include/config/rcxml.h
include/overlay.h
include/theme.h
src/config/rcxml.c
src/debug.c
src/main.c
src/overlay.c
src/server.c
src/theme.c

Resolves #1735
As now whether to draw a filled rectangle or an outlined rectangle is independently configured, I added `snapping.overlay.[region|edge].stroke`.
However, I'm thinking of replacing `*.fill`/`*.stroke` with `*.bg.enabled`/`*.border.enabled`. I think this will make it easier to understand.
Another approach is removing `*.fill`/`*.stroke` and letting users disable them by setting `*.bg.color` to `#0000000` and `*.border.width` to `0`.
Give me your opinions.

overlay: s/preview/overlay/ and draw filled/outlined rectangle independently

---

docs/labwc-config.5.scd
docs/labwc-theme.5.scd
docs/rc.xml.all
docs/themerc
include/config/rcxml.h
include/ssd-internal.h
include/ssd.h
include/theme.h
src/config/rcxml.c
src/ssd/meson.build
src/ssd/ssd.c
src/ssd/ssd_shadow.c
src/theme.c

Add optional drop-shadows to windows using server-side decoration. The presence and appearance of the shadows can be configured in rc.xml separately for active and inactive windows.  The default is no shadows to preserve current behaviour.
The shadows are drawn in two fixed buffers containing a corner and edge, then the edges are scaled according to window size.

ssd: add window drop-shadows

---

include/view.h
src/ssd/ssd.c

I noticed following error was printed when a view is resized to minimum width.
I re-installed pixman Arch Linux package with symbols to debug it and found this is due to a negative value passed to `wlr_scene_rect_set_size()`. 
```
*** BUG ***
In pixman_region32_union_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
```

ssd_titlebar.c: don't pass negative value to wlr_scene_rect_set_size()

---

src/view-impl-common.c

Fixes #1752.
Steam's Big Picture mode runs in fullscreen mode, but requests it before being mapped.
When a client requests fullscreen mode, `desktop_update_top_layer_visiblity()` checks if there's a fullscreen window in the output to determine the top layer should be hidden or not, but unmapped views are always ignored.
So `desktop_update_top_layer_visiblity()` should be called also on map. 
Not sure this is following the spec.

view: update top layer visibility on map

---

src/menu/menu.c

This fixes use-after-free in `fill_item()` on Reconfigure with invalid `menu.xml` like below:
```xml
<openbox_menu>
<item id="rofi-run" label="Run command">
<action name="Execute" command="rofi-run" />
</item>
</menu>
</openbox_menu>
```
Fixes #1776

menu: reset parser state in `menu_finish()`

---

src/foreign.c
src/input/cursor.c
src/xdg.c
src/xwayland.c

Fixes:
- #1640
Other than fixing that bug It also doesn't make sense to allow control of windows from within the window switcher in the first place. Testing appreciated.

osd: prevent handling cursor actions in preview mode

---

src/desktop.c
src/view.c

If a full-screen window is minimized, top-layer views like waybar are kept hidden. This PR tries to fix this behavior.
I noticed this with some Wine games when they minimized themselves after losing focus (for instance by using the window switcher), but of course it's easy to reproduce once you know about it.

view: fix top-layer not showing with minimized full-screen view

---

src/desktop.c
src/view.c

Fixes #1792
A caveat is that panels in `bottom` layer is still always hidden by a fullscreen window.
Testing is welcome.

desktop: show/hide `top` layer more smartly

---

include/magnifier.h
src/magnifier.c

I tried magnifier and it works very nicely, but I found that magnifier becomes quite laggy and damage tracking doesn't work correctly when I enabled magnifier with `WLR_RENDERER=pixman`. So this PR disables magnifier for pixman renderer for now.
The first commit is just a minor refactor.

Disable magnifier for pixman renderer

---

docs/labwc-actions.5.scd
include/view.h
src/config/rcxml.c
src/view.c
src/window-rules.c

I noticed that `view_matches_criteria()` and `view_matches_query()` are basically the same, so I reused some code. This builds on #1731  to avoid merge conflcts.

reuse query logic for window rules

---

docs/labwc-actions.5.scd
src/action.c

Use `<action name="AutoPlace" policy="cursor"/>` instead.
Suggested-by: @tokyo4j
To be merged after PR #1785

Deprecate MoveToCursor

---

include/input/ime.h
src/input/ime.c

Closes #1794.
We didn't support multiple IME popups since input-method-v2 protocol has no way to position them individually, but we should support it to provide IME developers with more programming flexibility.

IME: support multiple IME popups

---

src/common/scene-helpers.c

Fixes the high power consumption issue reported by @droc12345.
My fix is based on my understanding that the output state should be committed when the cursor has been moved or magnifier on/off state is changed.
I confirmed the CPU consumption reduced from around 5% to lower than 1% with this fix.

magnifier: fix high power consumption even with magnifier disabled

---

src/config/rcxml.c

Before this patch, having a branch or query with an invalid or missing parent action would trigger an assert when trying to access the parent. This patch ensures that we bail out instead.
Reported-by: fuyukai via IRC (thanks)
---
Backtrace:
```
00:00:00.000 [../labwc-0.7.1/src/config/rcxml.c:366] expect <action name=""> element first. nodename: 'name.acttion' content: 'ForEach'
labwc: ../labwc-0.7.1/src/action.c:231: action_get_arg: Assertion `action' failed.
Program received signal SIGABRT, Aborted.
0x00007ffff70ab82c in ?? () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007ffff70ab82c in ??? () at /usr/lib64/libc.so.6
#1  0x00007ffff70587ba in raise () at /usr/lib64/libc.so.6
#2  0x00007ffff70404f7 in abort () at /usr/lib64/libc.so.6
#3  0x00007ffff7040417 in ??? () at …
```

src/config/rcxml.c: ensure parent action is available

---

include/view.h
src/config/rcxml.c
src/view.c

Before this patch, the window type would be checked even if not actually requested to do so.
Fixes:
- #1852

ForEach: initialize view query window_type correctly

---

src/tearing.c

\+ replace `calloc()` with `znew()`

src/tearing.c: remove listeners on destroy

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/input/cursor.h
include/input/tablet-tool.h
include/input/tablet.h
include/labwc.h
protocols/meson.build
src/config/rcxml.c
src/input/cursor.c
src/input/meson.build
src/input/tablet-tool.c
src/input/tablet.c
src/server.c

As a follow up to https://github.com/labwc/labwc/issues/1672 and the ideas mentioned there, I ~played/hacked~ put this together. Running `gtk4-demo` and there the `Paint` demo, I can draw now in Stylus only mode and pen pressure is applied. So far so good.
~Looking at the general UI, just blindly switching from mouse emulation to tabled mode disables a lot of things that are imho not so easy to get correctly implemented, e.g. focus switch between applications, resize applications, drag & drop and surely a few others. That said, having a configuration switch like 'tablet-mode' (tablet-native|mouse-emulation) and/or an action 'toogle-tablet-mode' might be a way to mitigate this and allow a user to consciously switch between modes with all the consequences and restrictions applied.~ Actually …

feat: add partial tablet v2 protocol support

---

src/input/tablet.c

A resize with a tablet tool might end above a non-tablet capable surface, discard the proximity-in in that case.
Fixes a segfault for this situation.

input: send tablet proximity-in only above a valid surface

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/labwc.h
include/view.h
include/window-rules.h
src/config/rcxml.c
src/server.c
src/view.c
src/window-rules.c

This adds support for the [security-context-v1](https://wayland.app/protocols/security-context-v1) protocol. It is used by sandbox engines to restrict the features that sandboxed connections can use. For example, it is currently supported by Flatpak.
The implementation is based on the Sway code but adapted to Labwc. The `sandbox_engine` and `sandbox_app_id` parameters are added to window rules in order to be able to apply different rules for sandboxed clients.
The easiest way to test it is probably to take a recent version of Flatpak. Use it to run a Wayland application (for example, Firefox) with `WAYLAND_DEBUG` enabled and check for `wp_security_context` in the logs.

Add support for security-context-v1

---

include/input/tablet-tool.h
include/labwc.h
src/input/cursor.c
src/input/tablet-tool.c
src/seat.c

... at the same time. Omit cursor notifications from a pointer when a tablet tool (stylus/pen) is in proximity. We expect to get cursor notifications from the tablet tool instead. A side effect from giving pointer focus on tablet proximity.
My suggestion to handle this glitch, which sound actually scarier than it is. I'm only seeing the "wrong" cursor when doing out-of-surface scrolling in GTK4 applications.
Follow up from https://github.com/labwc/labwc/pull/1678 and "draft" for now to let this sink in.

input: prevent cursor notifications from pointer and tablet tool

---

README.md
docs/README
docs/meson.build
docs/shutdown

Closes #1809
_______________
Noticed the mentioned issue and maybe I can help with that?
Description is derived from the first sentence from the shutdown section in the man-page.

docs: add example shutdown file

---

src/input/ime.c

Fixes issues reported in #1871.
The first commit fixes a bug that multiple IME popup scene-nodes can be created if `wl_surface` is not destroyed when `input_popup_surface_v2` is destroyed.
The second commit fixes a flicker when IME popup is created with its surface mapped.
Here are videos showing the bug when I run the program provided in #1871 ([source](https://github.com/user-attachments/files/15531817/ime-test.zip))
Before this PR:
https://github.com/labwc/labwc/assets/22029524/72d04363-edf5-4de8-b67e-168ca64af9c6
After the first commit (flicker appears at 0:14):
https://github.com/labwc/labwc/assets/22029524/772ca60c-dbd6-40c2-ac6c-6b7c763591a4

IME: Fix some issues about IME popups

---

include/input/tablet-tool.h
include/input/tablet.h
src/input/cursor.c
src/input/tablet-tool.c
src/input/tablet.c

Notify all axis based on the capabilities of the tablet tool. At least GTK applications expect this for e.g. smooth pressure or distance events. 
With this change, distance and pressure (which are supported by my stylus) are also butter-smooth when not moving (no x,y motion) the stylus in the "Touch and Drawing Tablets" demo in gtk3-demo. (I've discovered this demo just recently)
First commit is a small refactoring, move tablet specifics into the tablet files.   
PS: Krita is still fine with this changes and looks like Gnome/Mutter is doing the same:
Gnome/Mutter: 
```
[3010668.867] zwp_tablet_tool_v2@4278190083.motion(737.50781250, 465.45703125)
[3010668.876] zwp_tablet_tool_v2@4278190083.pressure(0)
[3010668.880] zwp_tablet_tool_v2@4278190083.distance(49151)
[3010668.883] …
```

input: always notify all tablet axis

---

docs/labwc-config.5.scd
include/config/keybind.h
include/input/keyboard.h
src/config/rcxml.c
src/input/keyboard.c
src/seat.c

This is intended to replace https://github.com/labwc/labwc/pull/1761
It is based on #1761 and has had the following things done to it:
- Rebased against master
- Original commits squashed into one.
- A [fixup] commit added (although we ought to take it's commit message) to add a `onRelease` option to make the whole thing explicit. See discussion in original PR.
Note: still needs a squash of the two commits.
@tokyo4j @ahesford @Consolatis @jlindgren90 Would one of you be happy to do a quick review? I'm good with it and have tested, but feel I've tweaked the code to the point where it could do with a second pair of eyes.
@spl237 - Are you okay with the changes I've made?

modkeys - attempt 2

---

include/xwayland.h
src/input/cursor.c
src/xwayland.c

As wlr_xwayland caches the pixel data when not yet started up due to the delayed lazy startup approach, we do have to re-set the xwayland cursor image when reloading the cursor theme. Otherwise the first X11 client connected will cause the xwayland server to use the cached (and destroyed) pixel data.
To reproduce:
- Compile with b_sanitize=address,undefined
- Start labwc (nothing in autostart that could create a X11 connection, e.g. no GTK or X11 application)
- Reconfigure
- Start some X11 client

xwayland: reset cursor image on cursor theme reload

---

docs/labwc-config.5.scd
include/input/tablet-pad.h
include/input/tablet.h
include/labwc.h
src/input/tablet-pad.c
src/input/tablet.c
src/seat.c

Looking at the pad support in the tablet v2 protocol, this seems pretty straight forward and works with the "paint" demo in `gtk4-demo` by letting me use the pad buttons to change colors.
```
[ 142826.733] zwp_tablet_seat_v2@29.pad_added(new id zwp_tablet_pad_v2@4278190081)
[ 142826.734] zwp_tablet_pad_v2@4278190081.buttons(4)
[ 142826.735] zwp_tablet_pad_v2@4278190081.path("/sys/devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4.2/1-4.2:1.0/0003:056A:0378.0005/input/input22/event5")
[ 142826.737] zwp_tablet_pad_v2@4278190081.group(new id zwp_tablet_pad_group_v2@4278190082)
[ 142826.738] zwp_tablet_pad_group_v2@4278190082.modes(1)
[ 142826.739] zwp_tablet_pad_group_v2@4278190082.buttons(array[16])
[ 142826.740] zwp_tablet_pad_group_v2@4278190082.done()
[ 142826.741] …
```

feat: add tablet v2 pad support

---

src/menu/menu.c

...to avoid assert() in item_create() because current_menu is NULL.
Reproduce crash with...
<?xml version="1.0" encoding="utf-8"?>
<openbox_menu>
<item label="foo"/>
</openbox_menu>

menu: ignore <item> without parent <menu>

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/resize-outlines.h
include/view.h
src/config/rcxml.c
src/input/cursor.c
src/meson.build
src/resize-outlines.c
src/ssd/resize-indicator.c
src/theme.c

Closes #1328.
https://github.com/labwc/labwc/assets/22029524/e59a08f6-e3d1-4806-afb1-d95e3d4e8c74
The theme for the frame shown to indicate resized window when `<resize><drawcontents>` is set to no is configured with:
- `resize-frame.width`
- `resize-frame.color`
But I'm not sure about these names. Perhaps `resize.frame.{width,color}` or other names are better.
I initially implemented the frame as a combination of multi_rect and scene_rect like I did for snapping overlay, but I removed it for simplicity (we need to add `resize-frame.{bg,border}.enabled` and disable translucent scene_rect for pixman renderer).
If anyone wants it, I can move it back from [here](https://github.com/tokyo4j/labwc/tree/drawcontents-first).
The first commit adds `zero_array()` macro in `theme.c` to shorten the …

Implement <resize><drawContents>

---

include/input/keyboard.h
src/action.c
src/input/keyboard.c

This fixes the problem where if a mousebinding uses a modifier key which has an onRelease binding, the mousebinding does not cancel the pending onRelease binding if it is triggered.
The approach is to clear the pending release binding whenever any bound action occurs, which means it only needs to take place at one point in the code.
There may be other issues here which I have not considered, but this appears to fix the problem for me without breaking any other bindings - more testing and/or advice much appreciated.

Fix release keybindings being triggered after mouse bindings

---

docs/menu.xml
src/menu/menu.c

...because it seems like better English and is more consistent with other menu entries.
Same for 'Move Left' and 'Move Right'

menu: capitalize Roll Up/Down

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
src/action.c

Useful for switching between application-defined and mapped tablet  pad buttons. Also for quickly troubleshooting tablet behavior.
Probably not the most useful action, but simple implementation so why not.

feat: add ToggleTabletMouseEmulation action

---

src/input/tablet-pad.c

Otherwise we might end with a failed assertion if the tablet or pad isn't a libinput device.
Fixes https://github.com/labwc/labwc/issues/1916

input: test if tablet device is a libinput device

---

po/meson.build
src/main.c

Fixes #1901.
This makes the locale for client-menu items and workspace names follow the env var `LANG` defined in `~/.config/environments`.
The first commit is just a minor refactoring.

Initialize locale after reading ~/.config/environment

---

docs/labwc-actions.5.scd
include/labwc.h
src/action.c
src/input/keyboard.c

Should fix #449 PreviousWindow is the same as NextWindow
Edit to add: With the addition of osd_state.direction, there really is no need for LAB_CYCLE_*
enums or the check for them. It's mostly a change to desktop_cycle_view but it doesn't hurt to leave
the enum stuff till after the freeze. Actually this whole PR could wait, but it's not particularly invasive. 
ETA2: forget what I said above about LAB_CYCLE_* as I refactored it to keep it and fix the directional cycling.

PrevioiusWindow - fix problems with cycling not working correctly

---

include/ssd-internal.h
include/view.h
src/ssd/ssd-border.c
src/ssd/ssd-titlebar.c
src/ssd/ssd.c
src/view.c

My attempt to solve https://github.com/labwc/labwc/issues/1862 ~Still draft to let this land slowly and give it some time for testing.~
With this PR, my SSD corners look and behave the same as CSD GTK corners which gives a beautiful consistent look.   
A side effect is unfortunately that the "rounded hover effect on square  buttons" can be seen (much) more often.
Closes https://github.com/labwc/labwc/issues/1862

feat: set squared SSD corners when SSD client is tiled and notified about being tiled

---

src/view.c

Thonny (Python IDE made with Tk) may set the window geometry to 1x1 and maximizes the window before mapping. This set `view->natural_geometry` to 1x1, so labwc tried to restore the window geometry to it on unmaximize, causing validation errors in `ssd_update_geometry()` as its width and height are smaller than `LAB_MIN_VIEW_{WIDTH,HEIGHT}`.
This PR fixes it by not allowing geometries smaller than `LAB_MIN_VIEW_{WIDTH,HEIGHT}` in `view->natural_geometry`.
Closes #1921.

view: don't try to restore to very small width/height on unmaximize

---

include/common/scene-helpers.h
src/common/scene-helpers.c
src/magnifier.c
src/output.c

Gamma changes take another code path and thus did not render the magnifier.
This patch adds the magnfifier to the gamma code path and also slightly refactors the gamma handling.
Fixes:
- #1905
---
Completely untested.

magnifier: fix flickering on simultaneous gamma changes

---

include/layers.h
src/layers.c
src/xdg-popup.c
src/xdg.c

See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3514 which added support on the wlroots side.
We now re-run popup positioning (for both xdg-shell and layer-shell popups) when the "reposition" event is received. This allows popups that change size (such as qmpanel's applications menu) to be positioned correctly.
xdg-shell v3 also gives the compositor some additional "hints" for popup positioning (reactive, parent_size, and parent_configure_serial) which are available but we don't make use of currently.

xdg: support xdg-shell v3 with popup repositioning

---

subprojects/seatd.wrap

IIRC this was just a prop for building wlroots when the move to seatd happened and it wasn't yet common in repos.

Remove subprojects/seatd.wrap as no longer needed

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/xwayland.c

This seems to work as expected, keeping the server alive indefinitely at launch rather than allowing it to die.
- Changing the configuration option and reconfiguring does not change the behavior, because the wlroots xwayland object is still the same as was created at launch. Changing the behavior requires a compositor restart. Do we care? Attempting to fix this would seem to require terminating the X server, which could be catastrophic for any connected clients.
- Is there a better name or placement for the configuration option?
Closes: #1958.

xwayland: allow persistence

---

include/session-lock.h
src/session-lock.c
src/view.c

- Fix #1943
- Fix a bug I introduced in #1858 that allowed multiple clients to lock the screen.
- Clear keyboard focus on lock so keyboard events are never sent to normal surfaces once the screen is locked, even when the session-lock client haven't mapped its surface yet.

session-lock: fix some bugs related to keyboard focus etc.

---

src/menu/menu.c
src/theme.c

- Add missing `zfree/zdrop()` calls in menu.c and theme.c
- Change an early `return` to a `continue` when trying multiple config paths -- this appears to be what was intended, and fixes a memory leak

treewide: fix memory leaks on reconfigure

---

include/labwc.h
src/xdg.c

wlroots < 0.17 didn't allow to reliably check the source surface of an xdg activation request as it reset the surface to NULL when it was destroyed before the token was used. This happens regularly for notifications for example. Thus we treated the token as valid even without checking for the source surface.
wlroots 0.17 added a new_token signal where we can attach information to the existing token which we can then use when evaluating activation requests. This patch implements that check.

src/xdg.c: verify source surface for xdg_activation request

---

.github/workflows/build.yml
include/input/cursor.h
include/labwc.h
include/output-state.h
meson.build
protocols/meson.build
src/common/scene-helpers.c
src/decorations/xdg-deco.c
src/input/cursor.c
src/input/keyboard.c
src/input/tablet-pad.c
src/input/tablet.c
src/input/touch.c
src/layers.c
src/meson.build
src/output-state.c
src/output.c
src/seat.c
src/server.c
src/tearing.c
src/view.c
src/xdg-popup.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c
subprojects/wlroots.wrap

Same story as
- #626
This branch is not intended to be merged anytime soon but should allow to collaborate on chasing wlroots master.
As in the previous PR, feel free to push changes into this branch.
I suggest not using force pushes for now to reduce chances of accidentally overwriting something. If some existing commit should be amended just use `!fixup` or `[fixup]` or something along that line and refer to the subject of the commit to be amended (the hash may change due to rebases). We can remove that no-force-push restriction once we have a somewhat stable base to work with.
Like in #626 our goal should also be to make this PR as small as possible to reduce rebase conflicts with master. So if we can merge a commit in master that works for 0.17 and 0.18 without introducing any …

Update for wlroots 0.18

---

src/ssd/ssd-border.c
src/ssd/ssd.c

ssd: make borders respect snapped state on Reconfigure

---

src/ssd/ssd-border.c
src/ssd/ssd.c

[v0.7] ssd: make borders respect snapped state on Reconfigure

---

include/xwayland.h
src/xwayland.c

Set the initial geometry of maximized/fullscreen views before actually mapping them, so that they can do their initial layout and drawing with the correct geometry. This avoids visual glitches and also avoids undesired layout changes with some apps (e.g. HomeBank).
Depends on: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4546
Fixes:
- #1320

xwayland: set initial geometry in map_request handler

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/config/tablet-tool.h
include/input/cursor.h
include/input/tablet.h
src/config/meson.build
src/config/rcxml.c
src/config/tablet-tool.c
src/input/cursor.c
src/input/tablet-pad.c
src/input/tablet.c

Still draft since early days and there is already a big flaw:  the motion configuration overwrites all tools (Stylus, Pen, Tablet Mouse etc), but actually this should be on a per-tool base. Since we have `tool->hardware_serial` and/or `tool->hardware_wacom`, this should be doable. 
TODO:
PS: Multiple tool configurations could also be a separate PR, or may be even wait until someone hits this to have a real life demand.
Closes https://github.com/labwc/labwc/issues/1957

feat: support relative tablet motion

---

include/labwc.h
include/view.h
src/interactive.c
src/view.c
src/xdg.c
src/xwayland.c

Currently, initially maximized (or fullscreen) xdg-shell views exhibit one of two issues:
- some (e.g. GTK and Qt apps) paint an initial frame un-maximized (before the "map" event) and only maximize in a later commit
- others (e.g. foot) maximize immediately without flicker, but never store a valid natural size, so we end up using a fallback (640x480)
Under KWin, neither of these issues occur, so I looked into what labwc is doing wrong. It seems that:
- wlroots internally sends an initial configure event with a size of 0x0 to all xdg-shell views. This requests the client to set its own preferred (a.k.a. natural) size.
- For an initially maximized/fullscreen view, the initial configure event should contain the maximized/fullscreen size rather than 0x0. In labwc, this means we have to call …

xdg: handle initially maximized xdg-shell views better

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all
include/common/box.h
include/config/rcxml.h
src/common/box.c
src/common/meson.build
src/config/rcxml.c
src/edges.c
src/view.c

This is what I suggested in https://github.com/labwc/labwc/pull/1772#issuecomment-2093799066.
This adds following settings:
```xml
<placement>
<policy>cascade</policy>
<cascadeOffset x="40" y="30" />
</placement>
```
`cascade` policy places a new window at the center of the screen like `center` policy, but possibly shifts its position to bottom-right so the new window doesn't cover existing windows.
Its algorithm is copied from Kwin ([link](https://github.com/KDE/kwin/blob/df9f8f8346b5b7645578e37365dabb1a7b02ca5a/src/placement.cpp#L589)), combined with some helper functions I added (`wlr_box_contains()`, `wlr_box_intersects()` and `wlr_box_union()`).
https://github.com/labwc/labwc/assets/22029524/df90c7d2-7fa3-4550-8fa9-eb2d83a709dc
I think this policy achieves a good balance of …

view: implement `cascade` placement policy

---

docs/labwc-theme.5.scd
docs/themerc
include/ssd.h
include/theme.h
include/view.h
src/snap.c
src/ssd/ssd-border.c
src/ssd/ssd-extents.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/ssd/ssd.c
src/theme.c
src/view.c
src/xwayland.c

This commit introduces new option "window.button.width". Despite the name it currently affects both width and height.

theme: allow to set window button size

---

docs/README
docs/labwc-config.5.scd
docs/xinitrc
include/config/session.h
src/config/session.c
src/xwayland.c

Cf. #1961. This splits the xinitrc support for separate consideration.
Even though this change doesn't address the issue in #1958 because of a [race that we can't control](https://github.com/labwc/labwc/pull/1961#issuecomment-2207000149), I think it still warrants inclusion for four reasons:
1. It seems to partially address the issue, especially for remote clients where symlinking `.Xdefaults -> .Xresources` server-side is insufficient to trigger Xlib behavior that will cause clients to read resource configuration on disk.
2. It allows users of even local clients to force things like an `xrdb` load every time Xwayland is lazily restarted. This means that, even if the intitial client triggering its launch must fall back on `.Xdefaults` behavior for proper configuration, subsequent clients …

xwayland: support xinitrc scripts to configure server on launch

---

docs/labwc-config.5.scd
include/labwc.h
src/config/rcxml.c
src/output.c

Remove the NO_ATOMIC check, and add a conditional fallback for errors, which usually result from properties being applied during a flip, such as hardware cursor image changes. Falling back is limited so that persistent errors do not keep immediate flips running forever, but instead disable them until an output is reset. Verified working at least on AMD Radeon 6700 XT.

backend/drm: Fix up tearing for atomic modesetting

---

src/edges.c

Fixes: #1621
I haven't made a PR for this because I don't understand how resistance works and the issue only happened when I drag a window tiled to the bottom edge in nested session, but now the issue is more apparent while testing #2009.
CC @ahesford

edges.c: fix flicker of snapped windows in nested session

---

src/xdg.c

The initial configure event is now sent explicitly by labwc rather than by wlroots. We need to move the maximize/fullscreen logic to the initial commit handling accordingly.
Updates #1956, fixes #1994, replaces #1995.

xdg: update initial maximize logic for wlroots 0.18

---

include/labwc.h
include/magnifier.h
src/magnifier.c
src/server.c

This implementation is nearly identical to Sway's, except that it also reloads the configuration, to spur on reloading the server-side decorations.

backend/drm: Implement support for renderer loss recovery

---

src/layers.c

With wlroots 0.18, layer-shell's `new_surface` event is emitted on `zwlr_layer_shell_v1.get_layer_surface` request rather than the first commit. This change layer-shell clients like `fuzzel` to flicker on launch because labwc was sending a configure event with fullscreen geometry due to the absence of geometry hints on `get_layer_surface` requests.
This PR removes the code that updates the usable area from `new_surface` handler, preventing unintended configure events with fullscreen geometry.
Suggested by https://github.com/labwc/labwc/pull/1995#issuecomment-2240718847

layer-shell: stop sending configure events on surface creation

---

src/xdg-popup.c

Fixes #2012
`wlr_popup->current.geometry.{x,y}` are usually zero on initial commit, so xdg-popups were always unconstrained against the output which contains the top-left of the parent toplevel.
This PR changes xdg-popups to be unconstrained against the output which contains the top-left of preliminary popup geometry designated by xdg-positioner given as an argument of "get_popup" or "reposition" requests.
EDIT:
~Currently this doesn't work correctly with nested popups.~
EDIT2:
Now correct outputs are chosen also for nested popups.
Also added  a fix for #2017.

src/xdg-popup.c: choose output depending on xdg-positioner

---

src/common/graphic-helpers.c

Detected by `-Db_sanitize=address,undefined` for libwayland

multirect: remove destroy listener before freeing

---

src/common/graphic-helpers.c

Detected by `-Db_sanitize=address,undefined` for libwayland

[v0.7] multirect: remove destroy listener before freeing

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
src/config/rcxml.c
src/input/cursor.c
src/interactive.c
src/xdg.c

Closes #1968.
This PR adds `<snapping><dragResistance>` which configures the distance of cursor movement for dragging a tiled/maximized window.
I found dragging an initially maximized window places the window at a bit incorrect position. Not sure I can fix it in this PR.
~This PR also temporarily includes the commit from #2010.~

Implement resistance for tiled windows

---

include/labwc.h
src/interactive.c
src/xdg.c

The position where the view should be anchored can now be slightly different from the current cursor position.
Addresses a TODO from #2009.

xdg: account for drag resistance in do_late_positioning()

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
include/config/rcxml.h
include/labwc.h
include/view.h
src/action.c
src/config/rcxml.c
src/output.c
src/tearing.c

This is a slightly different approach to https://github.com/labwc/labwc/pull/1568
Whereas https://github.com/labwc/labwc/pull/1568 (forcefully) enables tearing when the active window is full screen and still allows tearing for non-fullscreen windows when the window hints tearing, this PR interprets  the 'fullscreen' option  as a restriction on top of the existing allow tearing ('yes') option. So 'fullscreen' here means "allow tearing *only* in fullscreen state". Additionally  the toggle action overrides the application preference. So once you started toggling, the application preference is ignored. I hope I described this clearly in the docs as part of this PR. 
I'm using the gsync demo from https://github.com/labwc/labwc/pull/1568#issuecomment-1986931068 for testing. Starting this via …

feat: add tearing fullscreen options

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
src/config/rcxml.c
src/input/cursor.c
src/interactive.c

As we already have `<resistance><{screen,window}EdgeStrength>`, `<resistance>` will be a better place for this setting.

Rename <snapping><dragResistance> to <resistance><unSnapThreshold>

---

docs/labwc-config.5.scd
include/input/tablet.h
src/input/tablet.c

Contrary to the raw tablet events, the cursor events transform the coordinates based on a mapped output orientation. Otherwise those events are the same. See https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/types/wlr_cursor.c#L897
Note that this only applies to absolute coordinates, the relative ones (`dx`, `dy`) are not transformed, in that case a user still has to manually set rotation in our tablet config.
~Additionally our own rotation is applied after area transformation, but the auto rotation is applied before. No real issue, just a slightly inconsistent behavior. We could turn around our behavior though to make this fully consistent, which is a minimal change.~
TODO:
Closes #1990 
cc: @dashavoo

input: subscribe to tablet tool events from cursor

---

src/xdg.c

I believe #1974 is the way to go, but it prevents activation of some major applications like thunderbird.
As I suggested #1974, adding option to configure policy for focus requests like `<core><focusRequestRequirement input="yes|no" focus="yes|no">` or implementing urgency hint will be the optimal way to prevent arbitrary focus-stealing without degrading UX. But as we're almost in the cool-down period, let's disable the source surface verification temporarily and move it forward later.

xdg-activation: temporarily disable source surface verification

---

src/xdg.c

This PR fixes an error message when launching a windowed Chromium: `00:00:01.778 [../src/view.c:720] view has empty geometry, not centering`.
That occurred because Chromium sends 2 commits before the mapping commit.

xdg: fix error when launching windowed Chromium

---

include/input/tablet-pad.h
include/input/tablet-tool.h
include/input/tablet.h
include/labwc.h
src/input/cursor.c
src/input/tablet-pad.c
src/input/tablet-tool.c
src/input/tablet.c
src/input/touch.c
src/seat.c

Otherwise we would subscribe multiple times to the same event when having multiple tablets.
Follow up from https://github.com/labwc/labwc/pull/2060 after sleeping a night and looking again how the eventing is setup for `touch` (which also subscribes to cursor events).

fix: move cursor event listeners from tablet to seat 

---

src/xdg.c
src/xwayland.c

1. Fixes #2074
2. Just like we're doing for xwayland surfaces, destroy foreign-toplevel handle rather than hiding it when xdg surface is unmapped. This behavior follows sway and xdg-shell protocol:
>  All active operations (e.g., move, resize) are canceled and all attributes (e.g. title, state, stacking, ...) are discarded for an xdg_toplevel surface when it is unmapped.
(2.) is tested with https://github.com/tokyo4j/wayland-demo/tree/remap

Fixes for foreign-toplevel when a view is re-mapped

---

src/xwayland.c

...to cope with pre-wlroots-0.18.0 behaviour resulting in dissociate events being emitted without a prior associate one.
As discussed via IRC with @vyivel and @Consolatis 
Suggest merging after `0.8.0`

xwayland: remove dissociate work-around

---

src/output.c

Running nested now shows the labwc icon + uses labwc in its title rather than "wlroots".
Example:

output: set 'labwc' as app_id and title for nested outputs

---

include/menu/menu.h
src/menu/menu.c

Without this patch we would happily access `pipe_ctx->item` members even if the item had been destroyed in the meantime.
---
Reproducer:
```bash
#!/usr/bin/bash
if test -n "$1"; then
sleep $1
fi
cat << EOF
<openbox_pipe_menu>
<menu id="delay-test-$(( RANDOM ))" label="Delay 3" execute="$(readlink -f "$0") 3" />
</openbox_pipe_menu>
EOF
```
and in menu.xml:
```xml
<menu id="delay" label="Delay" execute="~/.config/labwc/pipe_delay.sh" />
</menu>
```
Open the `Delay` menu, hover over `Delay 3` and then press `ESC` before the 3 seconds have been elapsed.

src/menu: prevent delayed pipe menu response on item destroy

---

include/menu/menu.h
src/menu/menu.c

Without this patch we would happily access `pipe_ctx->item` members even if the item had been destroyed in the meantime.

[0.7 backport] src/menu: prevent delayed pipe menu response on item destroy

---

docs/labwc-menu.5.scd
docs/labwc-theme.5.scd
docs/themerc
include/menu/menu.h
include/theme.h
src/common/scaled-font-buffer.c
src/menu/menu.c
src/theme.c

For visibility only so nobody else duplicates effort.
Cc: @heroin-moose  (as you mentioned this some time ago).
Have implemented `menu.title.bg.color: #589bda`
TODO:

menu: support titles defined by `<separator label="">`

---

docs/labwc-actions.5.scd
src/action.c

Useful for window rules.
This is a follow up from https://github.com/labwc/labwc/issues/1985#issuecomment-2271575221
Well, actually it is a work around for this issue, esp.  https://github.com/labwc/labwc/issues/1985#issuecomment-2271586923
@Narrat I've tested this briefly with the GTK4-Demo and Nautilus with:
```xml
<windowRules>
<windowRule title="*">
<action name="EnableTabletMouseEmulation"/>
</windowRule>
<windowRule title="Paint">
<action name="DisableTabletMouseEmulation"/>
</windowRule>
</windowRules>
```
Would be cool if you could confirm that this works for you.
PS: Not sure about the naming though like I wrote here https://github.com/labwc/labwc/discussions/2070#discussioncomment-10361475

action: add Enable/DisableTabletMouseEmulation

---

include/common/buf.h
src/common/buf.c
t/buf-simple.c

Cc @tokyo4j Is this useful for the YAML patch instead of the `BUF_FMT` macro?
Haven't tested it yet. Waiting for a test directory (#1099)

buf: add buf_add_fmt()

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/libinput.h
include/config/rcxml.h
include/labwc.h
src/config/libinput.c
src/config/rcxml.c
src/input/cursor.c
src/seat.c

Closes #2033.
But my concern about this PR is whether we should allow users to configure per-device scroll factor also for tablet devices. Looking at `handle_axis()` in `src/input/tablet.c`, it seems that we are not applying any multiplier to `distance` or `wheel_delta`. @jp7677 Do you have any opinions on this?

input: move <scrollFactor> to <libinput> section

---

src/common/buf.c

This works around a wrong truncation warning in older GCC versions:
```
../src/common/buf.c:110:10: error: null destination pointer [-Werror=format-truncation=]
110 |  int n = vsnprintf(NULL, size, fmt, ap)
```

common/buf.c: use 0 directly in vsnprintf()

---

docs/labwc-config.5.scd
docs/labwc-theme.5.scd
docs/rc.xml.all
include/config/default-bindings.h
src/config/mousebind.c
src/theme.c

- Mouse context `Omnipresent` -> `AllDesktops`
- Theme elements `window.*.button.omnipresent` -> `window.*.button.desk`
- Update documentation accordingly
This implements the first, and simplest, alternative discussed in #2112.

action: rename "omnipresent" button options for Openbox compatibility

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
include/resistance.h
src/config/rcxml.c
src/input/cursor.c
src/interactive.c
src/regions.c
src/resistance.c
src/xdg.c

Fixes #1521
Applies drag resistance unidirectionally for horizontally/vertically maximized windows, allowing them to be dragged without being untiled immediately.
While dragging a horizontally/vertically maximized window, edge/region snapping is disabled to prevent unintentional snapping and overlays.
The first commit stops unshading maximized/tiled views at the start of interactive move as it did't seem to be useful and caused flicker.
This PR also includes some refactoring to simplify the logic.
I'm totally fine delaying this PR after the next release. But I want to move forward the discussion below:
As I said in IRC yesterday, I'm thinking of changing `<snapping><dragResistance>` to something like `<resistance><snapOffThreshold>` (or maybe `<resistance><unSnapThreshold>`) as …

 interactive: allow moving horizontally/vertically maximized window

---

src/input/cursor.c
src/interactive.c

When labwc un-tiles views, it generally changes their size, which sends a configure request to the client. However, because the view has been disabled in the wlroots scene, it will not receive and process the configure when labwc expects. Instead, the handling will be deferred until the user unshades the view at some arbitrary time in the future, resulting in labwc registering complains like
[../src/xdg.c:239] client did not respond to configure request in 100 ms
Furthermore, the reconfigure will still generally produce flicker (as the view opens in its tiled size and then jumps to its natural geometry). Because skipping the unshade might cause client problems and doesn't eliminate the problem it sought to resolve, let's revert this.
This reverts commit …

Revert "src/interactive.c: don't unshade when view is un-tiled by dragging"

---

include/ssd-internal.h
src/ssd/ssd-border.c
src/ssd/ssd-extents.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/ssd/ssd.c

Another alternative for #1959 and #1964.
This fixes #1947 by removing some buttons for tiny windows. For windows smaller than (button width)*2, corners
are un-rounded so a small titlebar can be rendered with scene-rect.
Demo (extents are colored for visualization):
https://github.com/user-attachments/assets/f155c9dc-6f20-438f-8b16-74e2603d19b0

ssd: allow ssd to be smaller than minimal size by removing buttons

---

docs/labwc-theme.5.scd
docs/themerc
include/ssd.h
include/theme.h
include/view.h
src/snap.c
src/ssd/ssd-border.c
src/ssd/ssd-extents.c
src/ssd/ssd-titlebar.c
src/ssd/ssd.c
src/theme.c
src/view.c
src/xwayland.c

I've played a bit with the hover effects and came up with this simple version that is nicely consistent with GTK CSD applications I’m using and also plays nicely with squared corners ( win-win ;) ).
I would love to get this ready for review/merge. Obviously I should put this behind an option to not break existing setups. Furthermore I guess, but not sure if it is needed, the radius of the hover circle should also be a theme option. Any thoughts on where to put and how to name those options (`rc.xml` or `theme`)?
My suggestions:
Since we already have `<theme><cornerRadius>` may be `<theme><hoverRadius>` could work, whereas  `hoverRadius == 0` would be no rounded hover effects (thus keeping the current hover effect) and any value `> 1` would be applied as is (if it fits the max possible …

theme: add circle hover effect for window buttons

---

src/theme.c

When padding.width is set, the corner radius of the rectangle hover effect can be smaller since there is more space available.
This avoid weird looking rounded corners of the hover effect when there is enough space due to padding, that said, this is still a band aid.

theme: compensate the hover corner radius with padding

---

docs/labwc-actions.5.scd
docs/rc.xml.all

- Add some missing `atCursor="no"` in `rc.xml.all`
- Describe the behavior updated in #2146
- The added sentence is currently a bit inaccurate as we just search for the window menu button rather than the actual button that opened the menu. #2165 will fix this.
I won't self-merge just in case because I'm bad at writing English.

docs: some fixes about `<action name="ShowMenu" atCursor="no">`

---

src/xdg.c

Fixes #2142 by just removing `view_adjust_size()` from `xdg_toplevel_view_configure()`.
Maybe we should still adjust the window size before when resizing windows via actions (https://github.com/labwc/labwc/pull/83#issuecomment-945166313), but I wonder if we really need to do it.
At least we currently have a strange behavior with `<keybind key="" name.action="ResizeRelative" left="-10" />` like the video below and we should fix it when we decide to adjust the window size before resizing windows via actions.
https://github.com/user-attachments/assets/bb1e9ab6-757c-4705-b19f-41ad74001959

xdg: don't always adjust the window size before configure

---

meson.build

...with this warning message:
```
[100/161] Compiling C object labwc.p/src_button_button-svg.c.o FAILED: labwc.p/src_button_button-svg.c.o
gcc -Ilabwc.p -I. -I.. -Iinclude -I../include -I/usr/include/wlroots-0.18 -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libxml2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/sysprof-6 -I/usr/include/cairo -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/lib/pkgconfig/../../include/librsvg-2.0 -I/usr/include/gdk-pixbuf-2.0 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O0 -g -DWLR_USE_UNSTABLE -Wundef -Wlogical-op -Wmissing-include-dirs …
```

ci: use -Wno-expansion-to-defined to avoid Arch CI error

---

src/xdg.c

If a client times out responding to a configure request then the handle_configure_timeout() callback is run.  This cleans up the pending state and moves the view to the pending location, but keeps the current size. The idea is to stop slow applications causing too much lag when the user manipulates the window.  This callback used view_impl_apply_geometry() to actually apply the changes.
view_impl_apply_geometry() contains some heuristics to detect if we're resizing a window from the top, left, or top-left, and if so to do the expected behaviour of keeping the window's bottom/right corner in the same place.  However, that code was erroneously triggering in the case when the user requests to change a window from maximized to fullscreen but the client times out on the configure request. …

Don't detect edge-resizes in configure timeout

---

docs/labwc-actions.5.scd
include/view.h
src/action.c
src/view.c

Behaves identical like SnapToEdge and SnapToRegion, but untiles the window when already being tiled to the given region or direction.
I somehow missed this since there is already `ToggleMaximize` ;). `ToggleSnapToEdge` is also identical with the behavior I'm seeing on Gnome Mutter w.r.t. tiling.

action: add ToggleSnapToEdge/Region and UnSnap

---

src/ssd/ssd-titlebar.c

`view->ssd_enabled && view->ssd == NULL` is possible during the client is in fullscreen. So we need to check if `view->ssd` is NULL first in `ssd_update_window_icon()`.

ssd: fix crash on app_id updates while the app is in fullscreen

---

src/xdg.c

Fixes #2183.
This PR modifies the workaround for Qt apps introduced in #1229 by using the toplevel surface size (`surface->current.{width,height}`) instead of the whole surface extent (returned from `wlr_surface_get_extends()`), to update `view->current`.
Using toplevel surface size as the window geometry doesn't sound not right in regard to the xdg-protocol, but I think this change is OK as we're already not strictly following the protocol since #1229 and this doesn't complicate the codebase so much.
CC @jlindgren90 as I'm not 100% sure that this PR doesn't reintroduce any problems.

xdg: fix de-synced SSD when shrinking Thunderbird window

---

src/ssd/ssd-titlebar.c

Currently, left-aligned title text gets pushed right up to the window icon with no spacing at all, which looks bad IMO.
Before: 
After:
themerc has:
```
padding.width: 4
padding.height: 2
window.button.width: 22
window.button.spacing: 4
```

ssd: also add spacing between innermost button and title

---

include/view.h
src/view.c
src/xdg.c

In the case of an initially-maximized view which is taking a long time to un-maximize (seen for example with Thunderbird on slow machines), we may end up in handle_configure_timeout() with an empty pending geometry. In that case we have no great options (we can't center the view since we don't know the un-maximized size yet), so set a fallback position.
Fixes: #2191
Video running nested (slowed down to 50%):
https://github.com/user-attachments/assets/dfb35d39-e023-4733-a8c3-26f5b8184e34

xdg: try to handle slow un-maximize with empty natural geometry better

---

data/labwc-portals.conf
data/labwc.desktop
docs/environment
meson.build
src/config/session.c

The previous `UseIn` key was deprecated in xdg-desktop-portal 1.17/1.18. It has been superceded by the portals.conf structure so that each desktop can configure the precise desired structure for portals. In addition, support was added to the Desktop Entry Specifications to support a `DesktopNames` key that login managers will use to set XDG_CURRENT_DESKTOP.
* [portals.conf Documentation](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals.conf.rst.in)
* [Example sway-portals.conf](https://salsa.debian.org/swaywm-team/sway/-/blob/debian/sid/debian/sway-portals.conf)
* [Desktop Entry Specifications](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html)
Ref: flatpak/xdg-desktop-portal#955

Add labwc to XDG_CURRENT_DESKTOP to support a portals.conf

---

data/labwc-portals.conf

The GTK xdg-portal implementation, which is used as the default behind the wlr xdg-portal implementation, exposes the Inhibit interface even on a non-Gnome session. Unfortunately this D-BUS interface does not work on labwc.
By explicitly disabling this interface, firefox and may be other applications are not tricked into using the xdg-portal interface but use the Wayland IdleInhibit protocol instead which labwc supports.
See https://github.com/labwc/labwc/discussions/1503 for more technical details and also how to test this. This has also been raised https://github.com/labwc/labwc/pull/1716#issuecomment-2299758917 as a comment for the PR that introduced the portal configuration. Note that the same change has been proposed for the wlr-xdg-portal implementation …

data: disable Inhibit D-BUS interface in xdg-portals configuration

---

src/theme.c

The current `create_hover_fallback()` doesn't scale up the corner radius (and `padding.width`) correctly when the fallback hover effect is drawn on top of a non-hover icon buffer that's larger than the window button size.
So for example, when `close-active.png` with the size of 800x200 is provided, the hover effect looks as if it's not rounded at all:
This PR fixes it by switching the scale of the cairo context with `cairo_scale()`.
This also includes a minor refactor of #2145.

theme: scale corner radius in hover effect rendering

---

meson.build

`-Dicon=disabled` should disable window icons even when libsfdo is installed system-wide.

build: allow disabling icon when libsfdo is installed system-wide

---

src/icon-loader.c

GIMP for example sets its WM_CLASS to "gimp-2.10", which does not match the "gimp.desktop" filename, but matches the StartupWMClass key listed in it.
Thanks to @vyivel for the suggestion.

icon-loader: also match desktop entries StartupWMClass

---

src/action.c
src/xdg.c

Fix crash when executing view-related actions like `Maximize` from a menu opened by `show_window_menu` requests (https://github.com/labwc/labwc/pull/2167#issuecomment-2393015264).
Note that I don't know internals of `menu.c`. I just copied the lines from `show_menu()` in `action.c`.

xdg: fix crash on actions from menu opened by show_window_menu requests

---

src/icon-loader.c
src/xwayland.c

By:
- stripping extensions from relative icon filenames (for example, gdmap.desktop has "Icon=gdmap_icon.png")
- ~lowercasing the app_id before the fallback lookup since WM_CLASS is often capitalized ("Scid" now matches /usr/share/pixmaps/scid.png)~
- using the WM_CLASS "instance" rather than "class" string, which is usually the same but lowercase
~Change strcasecmp() to locale-independent g_ascii_strcasecmp() throughout the file, for consistency with g_ascii_strdown().~

icon-loader: fix a few more missing icons

---

include/buffer.h
src/buffer.c
src/common/font.c
src/common/graphic-helpers.c
src/common/scaled-font-buffer.c
src/common/scaled-scene-buffer.c
src/img/img-png.c
src/img/img-svg.c
src/img/img-xbm.c
src/img/img-xpm.c
src/osd.c
src/ssd/ssd-shadow.c
src/theme.c
src/workspaces.c

Add buffer_adopt_cairo_surface(), which allows wrapping an existing cairo image surface in a struct lab_data_buffer. This is useful when loading PNGs since most will be loaded as ARGB32 already.
Fix a memory leak in the non-ARGB32 PNG case, where we do still need to paint to a new image surface -- we were leaking the original surface.
Eliminate an unnecessary temporary image surface in SVG loading and just render the SVG to the image surface held by the lab_data_buffer.
I also cleaned up and clarified the buffer API a bit:
- Add a pointer to the held cairo_surface_t (so we can still access it if there is no cairo_t).
- Remove the free_on_destroy bool (it was always true).
- Rename unscaled_width/height to logical_width/height and add an explanatory comment. It was unclear what "unscaled" …

buffer: reduce unnecessary painting to new cairo surfaces

---

src/xdg.c

This is especially relavant for `<resize drawContents="no">`.
Demo (left: before, right: after):
https://github.com/user-attachments/assets/c0363f17-17b9-404d-a425-1b8c8ef8413a

xdg: take into account minimum window size for resizing

---

include/buffer.h
include/common/box.h
include/icon-loader.h
include/img/img-png.h
include/img/img-svg.h
include/img/img-xpm.h
include/labwc.h
include/ssd-internal.h
src/buffer.c
src/common/box.c
src/icon-loader.c
src/img/img-png.c
src/img/img-svg.c
src/img/img-xpm.c
src/output.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/theme.c

Very short summary: make icon-loader and ssd agree on what size icons
will be displayed at, and then load icons at the best available quality
for that size.
Before/after comparison, logical icon size 16px, various scales:
Before/after comparison, logical icon size 22px, various scales:
(Left-to-right: Xfce4 Terminal, XTerm, Spotify. Xfce4 Terminal has PNGs
at various sizes (but notably not 22px) plus an SVG. XTerm has a single
48px XPM. Spotify has a single huge 512px PNG, which as you can see is
downscaled badly in master.)
Changes in detail (just copied from commit messages):
- Add a new function to get the maximum scale of all usable outputs
- Pass the maximum output scale through to img_svg_load(), which
ultimately calls cairo_surface_set_device_scale() before rendering …

Improve icon display especially at larger output scales

---

docs/labwc-theme.5.scd
docs/themerc
include/ssd-internal.h
include/theme.h
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/theme.c
src/view.c

As we are approach the cool-down for the next release I am pondering the
titlebar settings. We have added some slightly conflicting theme options and it
is important that we strike a balance between sane default value and avoiding
some visible breaking changes.
Firstly we have added support for icons which are enabled by default.
Secondly - and over slightly longer than this release cycle - we have moved
from a very simple BUTTON_WIDTH constant which originated in early labwc
commits, to a few more knobs namely:
```
window.button.hover.bg.shape: circle|rectangle (default rectangle)
padding.width: 0
window.button.spacing: 0
window.button.width: 26
```
Whilst these have been given _default_ values to maintain the current look,
themes containing for example `padding.width` will result in a …

Titlebar related breaking changes

---

docs/labwc-theme.5.scd
docs/themerc
include/theme.h
src/theme.c

My GTK theme (Arc-Dark) has a hover effect with rounded corners, so I think it's worth supporting it rather than only supporting `rectangle` and `circle`. The existing `circle` hover effect can be reproduced if you set `window.button.hover.bg.corner-radius` more than half the button size and `window.button.{width,height}` equal.
I will not stick with this change, however, as I'll keep using the default theme anyway. I just wanted to confirm the right approach for the customization of the hover effect before the next release.
CC @johanmalm @jp7677

theme: replace `window.button.hover.bg.shape` with `window.button.hover.bg.corner-radius`

---

include/labwc.h
src/server.c

I spend this weekend setting up labwc `master` with wlroots `0.18` on a Raspberry Pi with a touch screen and an hdmi display. This is essentially a multi GPU setup.
It turns out that dmabuf feedback is needed to let labwc/wlroots find the correct EGL-Wayland driver. Without this PR `eglinfo -B` showed me the mesa `swrast` driver for EGL wayland platform, with this PR applied it shows the Raspberry Pi driver `drm-rp1-dsi`.
Using `mpv --vo=gpu --gpu-context=wayland` confirmed that with this PR I was no longer using a software renderer.
Note that this patch is only needed with labwc `0.8`. Labwc `0.7.4` with wlroots `0.17` did not needed this for seeing the hardware driver.
This PR mirrors #1278  as-is but with adjusted logging and a in wlroots `0.18` changed function call …

server: add dmabuf feedback

---

src/theme.c

I misunderstood when I was writing #2213; the iterator value of `wl_list_for_each()` is initialized whether or not the list is empty.
This reminds me of [a topic from linux kernel](https://lwn.net/ml/linux-kernel/20220217184829.1991035-1-jakobkoschel@gmail.com/).

src/theme.c: fix misuse of wl_list_for_each

---

src/menu/menu.c

menu: fix the calculation for centered titles

---

src/action.c

Before this PR, `client-menu` needed to be opened for `client-send-to-menu` to be updated.

src/action.c: fix client-send-to-menu not properly updated

---

src/input/tablet.c

This mechanism is only indirect, so it deserves a comment.

input: add comments about tablet mouse emulation

---

src/icon-loader.c

src/icon-loader.c: skip non application entries for wmclass lookup

---

docs/environment
docs/themerc

To match the common style in docs/

docs: replace two 'we's with passive forms

---

include/menu/menu.h
src/menu/menu.c
src/view.c

Update client-list-combined-menu when a window is destroyed to avoid SEGFAULT when selecting an that window entry in it.

menu: fix UAF in client-list-combined-menu after window destruction

---

src/config/session.c
src/main.c

src/config/session.c add env var LABWC_VER
This could be useful going forward for helper programs such as `labwc-menu-generator` or `labwc-tweaks`

src/main.c: add environment variable LABWC_VER

---

include/labwc.h
include/output-state.h
src/common/scene-helpers.c
src/output-state.c
src/output.c
src/server.c
src/view.c

We have several wlr_output_* functions which are just wrappers around corresponding wlr_output_state_* functions and don't actually touch the wlr_output itself. These probably made some sense historically, but IMHO they are just confusing now. So remove them and call wlr_output_state_* directly.
Rename wlr_output_commit() (still useful) to output_state_commit().
For after 0.8.1.

output: remove ported wlr_output functions

---

include/common/parse-bool.h
src/common/parse-bool.c
src/config/rcxml.c

Parsing directly as a bool was setting incorrect values in the query struct.
Reported on IRC by @Consolatis

config/rcxml.c: fix parsing of three-state query parameters

---

docs/labwc-actions.5.scd
src/view.c
src/window-rules.c

The `view_query.maximized` field should be initialized to the non-zero `VIEW_AXIS_INVALID` where used, rather than assuming the default zero value of `VIEW_AXIS_NONE`. Also, all of the early (pre-existing) tests in `view_matches_query` were not effectively distinguishing between "not tested" and "tested but passed" with the refactored match structure.
Fixes: #2288.

query: fix default values in query, fix match logic

---

include/labwc.h
src/common/scene-helpers.c
src/output.c

Currently, the cursor plane does not allow async page flips which causes tearing page flips to be rejected if the cursor was moved.
However, in games where no cursor image is present, the async page flips can still work as expected.
Instead of permanently disabling tearing after too many failures, test the output state first before each frame to see if we can commit with tearing_page_flip set to true.
Snippet used:
```c
if (state->tearing_page_flip) {
struct timespec start, end;
clock_gettime(CLOCK_MONOTONIC, &start);
if (!wlr_output_test_state(wlr_output, state)) {
wlr_log(WLR_DEBUG, "Output test for tearing failed on %s, "
"trying page-flip without tearing", wlr_output->name);
state->tearing_page_flip = false;
}
clock_gettime(CLOCK_MONOTONIC, &end);
long seconds = end.tv_sec - …
```

tearing: avoid permanent disable due to rejected commits

---

src/menu/menu.c

I.e. drop the extra padding from menu_item_padding_x that got there when separators with labels were implemented.

menu: use only menu_separator_padding_width to pad separators w/o label

---

src/output.c

... to make it possible in future to *not* immediately auto-configure
new outputs when connected (which will be a future PR).
In particular:
- Move regions_reconfigure_output() and session_lock_output_create()
into add_output_to_layout(), which would be called also if the output
is enabled later.
- Move seat_output_layout_changed() to do_output_layout_change() so it
is called for any layout change, not just adding new outputs.
- Then factor out configure_new_output() as a new function.

output: split up new_output_notify()

---

README.md

Project is no longer available.
https://archlabs.github.io/

Remove link to archlabslinux

---

src/action.c

Prior to this PR, a menu opened with:
```xml
<action name="ShowMenu">
<position x="center" y="center" />
</action>
```
was not correctly centered when `menu.items.padding.x` is non-zero.

menu: correctly center a menu opened with <position x="center" y="center">

---

src/icon-loader.c

This adds a final check to the fuzzy matching for application icons, whereby the number of characters in whichever is shorter of the desktop file name and the app id is compared.
I have already implemented heuristics similar to this in my desktop panel application to get icons for the task switcher - https://github.com/raspberrypi-ui/wf-panel-pi/blob/efafe5800adbf76869c8b7f1e03b6cf6dd4d4622/src/widgets/window-list/toplevel.cpp#L701 - and this final test matches a few common applications which are otherwise missed, such as GIMP.

Add final check for matching partial strings when looking for icons

---

include/input/cursor.h
include/labwc.h
src/input/cursor.c
src/input/tablet.c
src/input/touch.c
src/seat.c

The last commit is work in progress, I'm Just opening this for visibility and early feedback.
This needs to be based on https://github.com/labwc/labwc/pull/2253 . Once that one is in, I'll probably open a separate PR with only the first two commits, which are a follow up from https://github.com/labwc/labwc/issues/2242#issuecomment-2417932320. Well, after some testing…
About the WIP commit, hiding the cursor for touch feels very natural for me (Sway does that as well, see https://github.com/swaywm/sway/blob/master/sway/input/cursor.c#L408), but unfortunately it is slightly more work to keep the cursor hidden and affects other input handlers.
Not sure though if the cursor should still be hidden when cursor emulation for touch is enabled, I tend to keep the cursor visible in that case. Any …

feat: hide cursor for touch and prevent pointer cursor interference

---

docs/labwc-config.5.scd
src/config/session.c

...like `FOO=$FOO:bar` to avoid environment variables growing on reconfigure.
Cc @spl237

environment: disallow recursive env var assignments

---

include/labwc.h
src/icon-loader.c
src/main.c
src/osd.c
src/protocols/cosmic_workspaces/cosmic-workspaces.c
src/seat.c
src/server.c

This PR fixes some memory leaks (including ones for singletons) detected by ASAN.
The first 5 commits fixes memory leaks for `output->osd_buffer`, `icon_loader->icon_theme`, `seat->workspace_osd_timer`, `cosmic_manager` and `server->ssd_hover_state` respectively, and the last commit finally releases all the resources like `wlr_allocator`, `wlr_renderer`, `wlr_backend` and `wlr_scene`.
To suppress all the errors from ASAN with EGL renderer, https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/ce615a44c06ed10ab51b9c5a630acb43ef014efb needs to be reverted.

Fix memory leaks detected by ASAN

---

docs/labwc-theme.5.scd
include/theme.h
src/menu/menu.c
src/ssd/ssd-border.c
src/ssd/ssd-shadow.c
src/ssd/ssd-titlebar.c
src/ssd/ssd.c
src/theme.c
src/view.c

- Reorder `menu.*` theme entries (in documentation and codebase) that are currently scattered around. This is my primary motivation of this PR so that we can smoothly add theme entries for richer menu design (borders, rounded corners and padding).
- Move `theme->*_inactive_*` and `theme->*_active_*` into `theme->window`. This is a fixup for #2213.
- Rename `theme->menu_item_padding_*` to `theme->menu_items_padding_*`
- Rename `theme->title_height` to `theme->titlebar_height` (ref. https://github.com/labwc/labwc/pull/2189#issue-2555113495)

theme: tidy up codebase and documentation

---

src/workspaces.c

workspaces: keep focus on omnipresent windows when switching workspaces

---

src/menu/menu.c

This fixes segfault when exiting with a menu opened, which is a regression from eaf11fac.

menu: fix UAF of server->menu_current

---

include/menu/menu.h
src/menu/menu.c

This PR is a preparation for richer menu design including borders, rounded corners and padding around items (ref: https://github.com/tokyo4j/labwc/tree/rounded-menu, https://github.com/labwc/labwc/pull/2240#issuecomment-2422437018).
The first & second commits split the initialization of menu items into `item_create()`/`separator_create()` and `item_create_scene()`/`separator_create_scene()`/`title_create_scene()` so that we can create all the scene nodes in items after knowing the final menu width. This will allow us to smoothly add support for rounded corners without bloating `menu_update_width()` (renamed to `menu_update_scene()` in this PR) as we cannot resize cairo surfaces unlike scene-rects.
The third commit fixes that `menu.title.text.justify: right` worked like …

menu: refactor in preparation for richer menu design (+ minor fixes)

---

src/menu/menu.c

Prior to this PR, nesting the same menus (e.g. `<menu id="foo"><menu id="foo" /></menu>`) caused stack overflow at `close_all_submenus()` when trying to open it.

menu: invalidate nested duplicated menus

---

src/menu/menu.c

7651531 introduced a regression: `menu_update_scene()` which re-creates a menu scene was called for all the menus when a pipemenu is created, so the menus (parent of the pipemenu) were always moved to (0,0) and hidden, and the pipemenu was incorrectly positioned.
This PR fixes it by calling `menu_update_scene()` only for the pipemenu when it's created.
The second commit just eliminates dead code in `menu_hide_submenu()` I added in the prior PR by mistake.

menu: fix incorrect positioning of pipemenus

---

docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

I've been using `cascade` placement policy for several months and it's been working very well. It avoids the perfect overlap with `center` policy when user opens multiple windows consecutively, but its behavior is more predictable than `automatic` policy in my opinion.
I think we can provide better out-of-the-box experience to users by setting this policy to the default value.

placement: set default placement policy to `cascade`

---

src/menu/menu.c

This fixes use-after-free when there's only 1 desktop and `menu_hide_submenu()` is called to delete "Workspaces" submenu in client-menu before menu scenes are initialized.
As `menu_create()` and `item_create()` no longer initialize scenes after 76515316, `menu->scene_tree` and `item->tree` should be null-checked.
Sorry for another regression!

menu: fix UAFs in menu_destroy() and item_destroy()

---

src/theme.c

This fixes a regression introduced with:
https://github.com/labwc/labwc/commit/dcd9b47e5b584a2559d41cd255bb043f11970d12
A weak moment, missed that those can be negative while adding the checks ;)
Fixes #2294

theme: allow negative values for menu overlap

---

include/common/mem.h
include/config/keybind.h
src/config/keybind.c
src/config/rcxml.c
src/config/touch.c
src/img/img-svg.c
src/seat.c
src/view-impl-common.c

We didn't free `keybind->keysyms` on
- keybind de-duplication
- keybind removal due to empty action list
This PR adds a `keybind_destroy()` function which takes care of properly freeing the keybind.
---
For some `char *` vars in `struct rc` we were using `= xstrdup()` without freeing the previous value. This caused a mem leak with a config like
```xml
<theme>
<name>Numix</name>
</theme>
<theme name="Numix" />
```
This PR adds a new `xstrdup_replace(char *ptr, const char *val)` helper which does a `free(ptr); ptr = xstrdup(val)`.
---
Also thrown in a  small fix to remove line terminators from some log messages.

Fix some small config related memory leaks

---

src/view.c

Fixes
- #2337
Backported from 36e099fc93b3caf87e7f390a732fcec69373de8c
Slightly modified to handle the changed `struct output` rather than `struct wlr_output` argument for `output_enable_adaptive_sync()` in 7912665b0f3a541e5d766c7942446716df5e839d.
Edit:
Removed the `assert()` completely to keep the code churn to a minimum. Even with the [earlier changes](https://github.com/labwc/labwc/compare/f0212400f0e0fc2f6901fa658301fe2a2497b83b..12a1ae4c92560c4c984444d1f82f7248b5154478) due to the changed argument we still run into a `unused var` warning due to `struct output` only being used within the assert which would require a further workaround.
CC @spl237 (another backport for 0.7)

[v0.7 backport] view: ensure output is usable before setting adaptive sync

---

src/icon-loader.c

icon-loader: fall back to app-id if icon from .desktop failed

---

include/common/list.h
include/common/scaled-scene-buffer.h
src/common/scaled-font-buffer.c
src/common/scaled-scene-buffer.c

Suggested in #2352, combined with @Consolatis's work.
This PR adds `equal()` API in scaled-scene-buffer which can be used to share buffers for visually duplicated elements (e.g. scaled-font-buffer with the same text, font color and size). This PR itself isn't much beneficial as most `scaled-font-buffer`s are not duplicated, but this will greatly reduce the increased memory usage in #2352 as `scaled-rect-buffer`s used for backgrounds of menu and menu items will be visually the same.

scaled-scene-buffer: implement buffer sharing mechanism

---

src/output.c

When the output is in the process of being enabled, but the new state has not been committed yet, wlr_output->enabled is still false. So it's not safe to assert that it's true in output_enable_adaptive_sync().
Fixes: 36e099fc93b3caf87e7f390a732fcec69373de8c
"view: ensure output is usable before setting adaptive sync"

output: fix assert() fail when enabling an output that was disabled

---

include/view.h
src/view.c
src/workspaces.c

Follow-up from #2332 
One more related issue I noticed is the following:
- two omnipresent views and a usual one
- focus the usual one
- switch workspace
- one of the two omnipresent views gets focus
- switch back to the previous workspace
- focus the usual one
- switch workspace
- now the other omnipresent view gets focus
I think this is because we are using `view_for_each()` to move the omnipresent views to the new workspace. However, `server->views` is ordered topmost first and we only reparent the view scene tree without changing the ordering of `server->views`. `desktop_focus_topmost_view()` in contrast uses the scene node ordering (which is topmost last) to find the topmost view and then raises that one (which then in turn moves it to the front of `server->views`).
An easy 'fix' …

workspaces: use view_for_each_reverse() to move omnipresent views

---

docs/labwc-theme.5.scd
docs/themerc
include/common/scaled-rect-buffer.h
include/theme.h
src/common/meson.build
src/common/scaled-rect-buffer.c
src/menu/menu.c
src/theme.c

Since #2352 is so large and contains many things to discuss (e.g. default values of new theme configs), I decided to create another PR that only adds support for menu borders.
This PR adds following theme configurations:
```
menu.border.width: 1
menu.border.color: #a8a5a2
```
Currently, `menu.border.width` inherits `border.width` and `menu.border.color` inherits `window.active.border.color` just like Openbox does. However, as I explained in https://github.com/labwc/labwc/pull/2352#issuecomment-2478479590, the default value of `window.active.border.color` is the same as that of `window.active.title.bg.color` and `menu.items.active.bg.color`, so menu borders can be invisible with the default configuration like this:
So, I'm thinking of setting the default value of `menu.border.color` to …

menu: support borders

---

src/menu/menu.c

In Openbox, `menu.overlap.y: 3` is applied like:
However, in the current labwc, the y-offset is inverted like:
This PR fixes it to follow Openbox's behavior.

menu: invert the y-offset of submenus applied by menu.overlap.y

---

src/theme.c

It was a cruft from my experiment of adding borders around titles.
It even caused an integer overflow because `theme->menu_border_width` can be `INT_MIN` when `menu_header_height` is calculated. This didn't cause sigfault, however, because `INT_MIN * 2` becomes 0.

menu: don't include menu.border.width for menu title height

---

src/common/graphic-helpers.c

`lab_data_buffer->logical_{width,height}` are not the actual size of the backing buffer, so `wlr_buffer.{width,height}` should be used when duplicating it in `get_cairo_surface_from_lab_data_buffer()`.
This mistake caused segfault when an icon file 1~2 times larger than `window.button.{width,height}` is loaded, because the buffer for the raw icon file is reused by setting `lab_data_buffer->logical_{width,height}` with the size for display which is different from `wlr_buffer.{width,height}` (see `buffer_convert_cairo_surface_for_icon()`), and it is duplicated with `get_cairo_surface_from_lab_data_buffer()` for hovered/rounded variants of titlebar button.

graphic-helpers: fix segfault when medium-size icon file is loaded

---

.github/workflows/build.yml
scripts/asan_leak_suppressions
scripts/ci/ci_autostart.sh
scripts/ci/smoke-test.sh

Since GitHub runners now support hardware virtualization, the maximal runtime of the FreeBSD runner is somewhere around 3 to 6 minutes. It may still fail sometimes so keep the timeout parameter around.
Also re-enable the Debian build job (by compiling the wlroots subproject) and add the address sanitizer to the Debian smoke-test now that we should be leak free on shutdown.

Ci: reduce timeout to 10 minutes and add b_sanitize=address,undefined to detect leaks in the runtime test

---

docs/labwc-config.5.scd
include/window-rules.h
src/config/rcxml.c
src/input/keyboard.c
src/window-rules.c

...for modifiers which are part of keybinds. This supports clients (for example blender) that want to see the modifier-release-event even if it was part of a keybinds. This is treated as a special case and can only be achieved by configuration.
Most clients (including those using Qt and GTK) are setup to not see these modifier release events - and actually misbehave if they do.  For example Firefox shows the menu bar if alt is pressed and then released, whereas if only pressed (because the release is absorbed) nothing happens. So, if Firefox saw bound modifier-release-events it would show the menu bar every time the window-switcher is used with alt-tab.
Issue #1507
Cc @charbelnicolas 
Testing appreciated.
TODO

keyboard: optionally send release-events

---

include/buffer.h
include/common/graphic-helpers.h
src/buffer.c
src/common/font.c
src/common/graphic-helpers.c
src/common/scaled-rect-buffer.c
src/img/img-svg.c
src/osd.c
src/theme.c
src/workspaces.c

I think `memcpy()` in `get_cairo_surface_from_lab_data_buffer()` is redundant as we can use `cairo_image_surface_create_for_data()` instead. Also we can always set `buffer->{cairo,surface}` so that we can just access them when we start writing on/from the buffer.

buffer: always set buffer->surface and remove buffer->cairo

---

.github/workflows/build.yml

Using a .wrap file + `--force-fallback-for` just for Debian complicates everything and turns `build.yml` into more spaghetti than it already is.

CI: disable clang for Debian until they get wayland 1.23.1

---

src/ssd/ssd-titlebar.c

I think it's fine to merge this PR for the next release.
This fixes the pixman error (which causes `assert()` failure in wlroots 0.19 https://github.com/labwc/labwc/pull/2388#issue-2696997166) when a tiny window is decorated.
In #2213, `set_squared_corners(false)` was always called when titlebar is created. However, `set_squared_corners(false)` sets the width of the titlebar background buffer to `(view width) - (corner radius)`, which causes pixman errors due to the negative width set for titlebar background buffer when the view is so small.
Note: `ssd_should_be_squared()` returns `true` when the titlebar corners should be un-rounded as the view is so small or tiled, but maximization state is not considered. `set_squared_corners()` rounds/un-rounds the titlebar corners, so `true` should …

ssd: fix pixman error when SSD is created for tiny windows

---

src/server.c

In the longer term we want this to be user-configurable (and also depend on the sandbox engine, app_id and instance).
But dropping privileged protocols for sandboxed clients in the meantime seems like a sensible thing to do and matches user expectations.
Related: #2392
---
I think we should add this before 0.8.2.
When we implement a user config for this we can also move the new functions into its own file, they feel a bit hacked onto `server.c` with this PR.
Can be tested with https://gitlab.freedesktop.org/wlroots/wlr-clients/-/merge_requests/6

server.c: block privileged protocols for sandboxed clients

---

src/action.c

Suggested by stormshadow in IRC.
This PR slides menus opened from buttons (with `atCursor="no"`) to the left by `menu.border.width`.
|before|after|
|-|-|
|![20241206_13h17m28s_grim](https://github.com/user-attachments/assets/32fd5bcf-88ba-4dd6-b8b1-9a375af5e0ca)|![20241206_13h17m11s_grim](https://github.com/user-attachments/assets/a7000720-020b-481a-a103-ca8e542ea5de)|
This change is primarily for the default window menu opened from the left-corner window icon, but I think it doesn't sacrifice the look when the button from which the menu is opened is not placed in the left corner:
I think we can merge this PR before the next release, as the change is quite small.

menu: slightly slide menus opened from buttons

---

src/action.c

This PR reverts #2403 due to the regression (#2404). #2406 might be fine for fixing the regression, but introducing an unknown code path would increase the risk of another regression.

Revert "menu: slightly slide menus opened from buttons"

---

include/labwc.h
src/action.c

Prior to this PR, output-relative coordinate was passed to `menu_open_root()` as the menu position when it's designated via `position.x`/`position.y` arguments in ShowMenu action, so menu can be misplaced to the output other than the one in which the cursor is in.
Intended for merging before 0.8.2, but it's up to other devs.

action: fix menu position with "x"/"y" arguments in multi-monitor setup

---

src/config/rcxml.c

...when options are specified as elements leading to hitting the assert() in xstrdup().
Reproduce by using this rc.xml:
```
<?xml version="1.0"?>
<labwc_config>
<touch>
<deviceName>foo</deviceName>
<mapToOutput>bar</mapToOutput>
</touch>
</labwc_config>
```
It is likely that <touch> was only tested with options as attributes.
Discovered when playing with https://github.com/johanmalm/yaml2xml/ (thought I'd pull the code out of that yaml-PR and get a CLI tool going). Cc: @tokyo4j

config/rcxml.c: fix crash in <touch> section

---

scripts/wl_compcheck.py

Simple utility to allow protocol and version comparison between different running compositors. This can be used to detect missing protocols or versions in labwc. See for example this result when running against the current labwc master and sway 1.10 (nested, results on DRM may differ slightly):
```
Protocols missing from labwc @ wayland-0
ext_transient_seat_manager_v1                   1
wl_compositor                                   6  (has version 5)
wp_alpha_modifier_v1                            1
wp_content_type_manager_v1                      1
xdg_wm_base                                     5  (has version 3)
zwp_keyboard_shortcuts_inhibit_manager_v1       1
Protocols missing from sway @ wayland-1
wl_drm                                          2
zcosmic_workspace_manager_v1 …
```

scripts: add wl_compcheck.py

---

docs/labwc-config.5.scd
src/config/rcxml.c

This is a compile-time check, so it will be too conservative if somebody updates wlroots after building labwc, but that is still better than the alternatives.
I don't like the idea of hard-depending on `wlroots >= 0.18.2` after that is released. It isn't necessary for core (or even expected) functionality in labwc, and changing the default persistence flag effectively renders inoperable the bug we are trying to avoid. Strict version requirements are an unnecessary burden on distribution packagers as well as end users that may be balancing competing interests (imaging an end user trying to build the latest release, but who prefers to keep a system version of wlroots that has not yet been updated).
At the same time, forcing xwayland to persist by default when somebody *has* updated wlroots …

config: only default to xwayland persistence on old wlroots versions

---

docs/environment

...because it has not been relevant since before firefox v121 and even firefox-esr on Debian bullseye is now at v128.
Suggested-by: cry0xen

docs/environment: remove example MOZ_ENABLE_WAYLAND=1

---

include/common/font.h
include/common/scaled-font-buffer.h
include/menu/menu.h
src/common/font.c
src/common/scaled-font-buffer.c
src/menu/menu.c
src/ssd/resize-indicator.c
src/ssd/ssd-titlebar.c

Split from #2399. This PR removes `arrow` argument from `font_buffer_create()` and `scaled_font_buffer_update()` so that we can simplify the calculation of the size of a font buffer. Now, 2 separate scaled-font-buffers for a label and a arrow sign are created for a submenu item. 
Other changes are:
- Now `font_buffer_create()` accepts non-positive numbers for `max_width`, in which case the natural font width is always used for buffer creation.
- `menuitem->{normal,selected}` are replaced by simple `menuitem->{normal_tree,selected_tree}`, since we no longer dynamically update buffers of existing menuitems.

font: remove arrow character from font buffer

---

include/menu/menu.h
src/menu/menu.c

For post-0.8.2. I wrote this patch some weeks ago, but now I think it's more useful than just a refactoring since this PR fixes the the root cause of #2404.
---
Since wlroots already provides a mechanism to place popups via `wlr_xdg_positioner_rules_get_geometry()` and `wlr_xdg_positioner_rules_unconstrain_box()`, I think we can simplify the codebase by applying them also for compositor-side menus. 
Notable functional changes are:
- Slide the menu to fit in the output when it's opened out of the output (e.g. when top-left window menu is opened when the window is overflowing to the left), rather than not updating the menu at all. This should prevent reintroducing #2404 when we reland #2403.
|before|after|
|-|-|
|![20241208_17h39m10s_grim](https://github.com/user-attachments/assets/1147bc8d- …

menu: improve algorithm for menu placement with xdg-positioner

---

docs/labwc-config.5.scd

...when matching against keybinds.
Copied from:
https://github.com/labwc/labwc/blob/63dc609085d42d16401e23079bb50e2f07e31de5/src/input/keyboard.c#L215-L238

labwc-config(5): describe how keys are processed

---

include/protocols/cosmic-workspaces-internal.h
include/workspaces.h
src/protocols/cosmic_workspaces/cosmic-workspaces.c
src/protocols/cosmic_workspaces/output.c
src/workspaces.c

Split of from
- #2365
Some more minor prep work:
- Removes `lab_cosmic_workspace_set_hidden()` calls as its a concept labwc does not support.
- Prefixes some cosmic internal API naming to not clash with a future ext-workspace implementation

Some more minor prep work for ext-workspaces

---

include/input/ime.h
src/input/ime.c

After commit [e2189903](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e21899037a97dcade40149f05ab54229c0018644) in wlroots, when ctrl-f is pressed in firefox with a IME client running, the following key-release event for "f" is not sent, thus "f" is repeated like "ffffffffff..." in the input box of firefox. This is because the key-release event for "f" is firstly relayed to the IME client and then sent via the virtual keyboard created by the IME client while the key-press event is sent via physical keyboard, and with [e2189903](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/e21899037a97dcade40149f05ab54229c0018644), key-release events without a corresponding key-press event on the same keyboard is not emitted to the compositor. …

keyboard: fix missing release event when IME is enabled while key press 

---

include/common/font.h
include/common/scaled-scene-buffer.h
src/common/font.c
src/common/scaled-font-buffer.c
src/common/scaled-rect-buffer.c
src/common/scaled-scene-buffer.c

For post-0.8.2.
Prior to this PR, a backing buffer with scale 1 was always created for a `scaled_scene_buffer` before showing it, and backing buffers for specific scales were created on `output_enter` events.
This PR removes this redundant re-renderings by calling `wlr_scene_buffer_set_dest_size()` upon `scaled_scene_buffer` creation so that we can receive `output_enter` events without creating a backing buffer, and delaying the first rendering to the first `output_enter` event.
This PR includes some refactors in `font.c` and `menu.c`, so I'm thinking of splitting this to smaller ones after we release 0.8.2.

 scaled-scene-buffer: reduce unnecessary renderings

---

src/action.c

This is reland of #2403 which was reverted with #2407, but this prevents the x-position of the menu from being negative and slides menus opened with Alt-Space too. CC @st0rm-shad0w

menu: slightly slide menus opened with atCursor="no"

---

src/output.c
src/server.c

Also, always top-align submenus intead of inheriting the vertical alignment of their parent. This is consitent with Openbox behaviour.
Related-to: #1150

menu: move menu_tree to front

---

include/labwc.h
include/protocols/ext-workspace-internal.h
include/protocols/ext-workspace.h
include/workspaces.h
protocols/ext-workspace-v1.xml
protocols/meson.build
src/output.c
src/protocols/ext-workspace/ext-workspace.c
src/protocols/ext-workspace/meson.build
src/protocols/ext-workspace/output.c
src/protocols/meson.build
src/workspaces.c

Minor final touches missing from the implementation but should be fine to test clients against.
The first two commits are prep work for supporting both, cosmic-workspaces and ext-workspaces and will be split into an own PR so this one is easier to review.
~~Note: the [protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) is still not merged so it may be changed further. Do not use this protocol in non-dev builds or without hiding it behind feature flags.~~
CC @LBCrion in case you want to start playing with an implementation in sfwbar and need a compositor to test against.

Protocol implementation: ext-workspaces

---

include/buffer.h
include/common/box.h
include/common/scaled-img-buffer.h
include/desktop-entry.h
include/img/img-png.h
include/img/img-svg.h
include/img/img-xbm.h
include/img/img-xpm.h
include/img/img.h
include/node.h
include/ssd-internal.h
include/theme.h
src/buffer.c
src/common/box.c
src/common/meson.build
src/common/scaled-img-buffer.c
src/common/scaled-scene-buffer.c
src/desktop-entry.c
src/desktop.c
src/img/img-png.c
src/img/img-svg.c
src/img/img-xbm.c
src/img/img-xpm.c
src/img/img.c
src/img/meson.build
src/node.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/theme.c

- Fix #2286
- Fix blurry window button icons in outputs with a scale larger than 1
- `lab_img` holds a cache for a loaded image (`lab_data_buffer` for PNG/XBM/XPM images and `RsvgHandle` for SVG images).
- `lab_img` is created with `lab_img_load()` and rendered to a buffer with `lab_img_render()`. This allows rendering the same images for different sizes/scales.
- __"Modifier"__ functions can be applied to `lab_img` with `lab_img_add_modifier()`. This applies additional drawing operations in `lab_img_render()`. In this PR, this is used for overlaying hover effects on window buttons and rounding the corner buttons.
- The cache in `lab_img` is refcounted and can be shared by multiple `lab_img`s when they are duplicated with `lab_img_copy()`. In this PR, `lab_img`s for builtin normal/hovered …

ssd: rework titlebar button rendering 

---

src/theme.c

...from WLR_ERROR to WLR_INFO to avoid 'false' logging when Openbox themes contain the padding.height settings. Whilst this option is not supported, the visual appearance is very close to that of Openbox with common themes.
The background to this is that Labwc theme specification has diverged slightly from that of Openbox with respect to titlebar padding to support more contemporary looks whilst avoiding breaking changes. For full details see commit: e16e78e7a4a6e40c8184edd7bb483b0f395482d0
Suggested-by: @Consolatis

theme: demote padding.height warning

---

docs/labwc-actions.5.scd
include/labwc.h
src/action.c

This is a simple action that warps the cursor to the middle of the currently focused view. Useful when moving windows or changing focus using keyboard shortcuts.

"WarpCursor" action

---

include/labwc.h
src/output.c
src/view.c

I'm opening a PR as I just recalled an old discussion: #1620
`output_usable_area_scaled()` doesn't make sense; the geometry returned from `output_usable_area_in_layout_coords()` is already divided by the output scale, so we don't need to divide it again.

src/output.c: remove output_usable_area_scaled()

---

src/img/img.c

Fix the cut-off icons reported in #2450. I think I was careless when writing that part.

img: fix scaling for rendering large image in non-square rectangle

---

docs/labwc-config.5.scd
include/input/key-state.h
include/labwc.h
include/window-rules.h
src/action.c
src/config/rcxml.c
src/input/cursor.c
src/input/key-state.c
src/input/keyboard.c
src/interactive.c
src/menu/menu.c
src/osd.c
src/seat.c
src/view.c
src/window-rules.c

First, this PR reverts #1226 and #2377, because:
- Not sending modifier release events (#1226) for keybinds (for not showing firefox's menu bar) is very problematic with some applications (#1537, #1507).
- Forcing users to define `wantAbsorbedModifierReleaseEvents` window rule (#2377) to fix it is also undesirable, since it doesn't provide a good out-of-the-box experience and requires users to read through our documentation.
After some discussion in #2448 and #2452, we decided to follow KWin's approach that always sends modifier release events, but clears keyboard focus when activating window switcher (typically triggered by Alt-Tab) to prevent firefox from showing menu bar. Of course, this doesn't work for other actions like `Execute` and makes existing Alt-* keybinds show firefox's menu …

Always send modifier release events, and clear focus on Move/Resize, window switcher and menu interactions

---

src/debug.c
src/desktop-entry.c
src/osd-field.c
src/view.c
src/xdg.c
src/xwayland.c

...when app_id is NULL.
Make sure view_get_string_prop() never returns NULL because it is so easy to misuse. Same for the respective xwayland/xdg impl methods in case anyone decides to (incorrectly) call them directly in future.
Fixes: #2453

view: fix NULL string_prop crash

---

docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

...to avoid surprises on Acer Aspire One laptops where the numeric keyboard does not physically exist but "overlaps" the qwerty keyboard.
Reported-by: staryvyr on IRC
Note: We do not like changing defaults, but feel that there is a good reason for this one.

keyboard: set numlock to off by default

---

include/labwc.h
include/osd.h
src/action.c
src/desktop.c
src/input/keyboard.c
src/osd.c
src/seat.c

1. Remove the call to `osd_review_restore()` in `desktop_cycle_view()`. I guess this is just a cruft from days when the next view to cycle is determined by traversing scene-nodes (ref. #1479).
2. Make `osd_preview_restore()` private in `osd.c` and call it inside `osd_finish()`. I renamed it to `restore_preview_node()`.
3. Replace `seat->server->osd_state.cycle_view || seat->server->input_mode != LAB_INPUT_STATE_PASSTHROUGH` with just `seat->server->input_mode != LAB_INPUT_STATE_PASSTHROUGH`. I missed to do this when rebasing #2455.
4. Refactor to not update values in `server->osd_state` outside `osd.c` by adding `osd_begin()` and `osd_cycle()`.
5. Make `desktop_cycle_view()` private in `osd.c`, renaming it to `get_next_cycle_view()`.
The primary goal in this PR is (4). In the future, …

osd: some refactor

---

docs/labwc.1.scd
src/desktop-entry.c

...to avoid error messages like these:
00:00:00.109 [sfdo-desktop] 1:1: Name is unset
00:00:00.109 [sfdo-desktop] Failed to load /usr/share/applications/lxqt-panel.desktop
00:00:00.136 [sfdo-desktop] 1:1: Exec is unset while DBusActivatable is unset or false
00:00:00.136 [sfdo-desktop] Failed to load /usr/share/applications/qemu.desktop

desktop-entry: demote all sfdo-desktop logging to WLR_DEBUG

---

src/input/cursor.c
src/osd.c

This PR cleans up the cruft and comments from e45fe08 (ref. #2475).
Background:
- With e45fe08, the keyboard focus is always moved to the switched window on finishing window switcher, even with `<focus followMouse="yes">`. Since `followMouseRequiresMovement` was not implemented at that time (behaved like it was always "no"), e45fe08 was necessary to allow users users who use `followMouse="yes"` to move the keyboard focus with window switcher.
- 9a9e20d added `followMouseRequiresMovement`, but it kept the behavior described above even with `followMouse="yes"` and `followMouseRequiresMovement="no"`.
- 398b80b accidentally invalidated e45fe08, which means the keyboard focus is now always moved to the window below the cursor on finishing window switcher with `followMouse="yes"` and …

Remove cruft related to window switcher and keyboard focus

---

include/input/keyboard.h
src/input/keyboard.c
src/server.c

Currently we may end up in an endless loop of Reconfigure requests if the Reconfigure action was called by a keybind. If the reconfigure takes too long (which may happen on slow systems with libsfdo full debug logging for example) the reconfigure might be triggered again and again.
To prevent that, simply cancel all keybind_repeat timers on reconfigure.
---
Only slightly tested.

keyboard: cancel keybind_repeat on reconfigure

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/output.c

rcxml: add core.autoEnableOutputs option
Currently, labwc automatically enables outputs at startup and when new
outputs are connected. Make this behavior optional (but still enabled by
default).
With autoEnableOutputs disabled, tools such as kanshi can be used to
give finer-grained control of which outputs are enabled and when.
Personally, I use this to avoid re-enabling outputs that disconnect and
reconnect during powersave, but I can imagine other use-cases for it
also.
The first two commits address modesetting failures that are revealed by
this option but could also be merged separately.

rcxml: add core.autoEnableOutputs option

---

README.md
docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all
include/config/default-bindings.h
include/labwc.h
src/action.c
src/input/keyboard.c
src/osd.c

Closes #2462.
Before this PR, keystrokes were interpreted based on following hard-coded rules while the window switcher is active:
1. Up/Left arrow keys cycle the window forward.
2. Down/Right arrow keys cycle the window backward.
3. Other keystrokes cycle the window in the initial direction specified by `NextWindow`/`PreviousWindow` actions. But while Shift key is pressed, the direction is inverted.
...and keybind actions were never executed.
However, this lead to a counter-intuitive behavior for new, especially pre-Openbox users. For example, in the following keybinds, after the user activates the window switcher with `Super+n`, `Super+p` cycles the window _forward_:
```xml
<keybind key="W-n">
<action name="NextWindow" />
</keybind>
<keybind key="W-p">
<action name="PreviousWindow" /> …
```

osd: make window switcher more Openbox-like in terms of key precessing

---

docs/labwc-menu.5.scd
include/menu/menu.h
src/menu/menu.c

For example:
```xml
<?xml version="1.0"?>
<openbox_menu>
<menu id="root-menu" label="" execute="obmenu-generator"/>
</openbox_menu>
```
Fixes: #2238
Intended for after `0.8.1`

menu: support pipemenu with the toplevel `<menu>` element

---

include/common/scaled-img-buffer.h
include/img/img.h
include/ssd-internal.h
src/common/scaled-img-buffer.c
src/img/img.c
src/ssd/ssd-titlebar.c
src/theme.c

This PR implements the approach I proposed in https://github.com/labwc/labwc/pull/2481#issuecomment-2569384105.
Like #2481, this PR makes `lab_img` outlive `theme_finish()` by refcounting, but without adding new APIs:
- When creating a `scaled_img_buffer`, `lab_img` is replicated via `lab_img_copy()`
- When destroying a `scaled_img_buffer`, `lab_img` is destroyed via `lab_img_destroy()`
Let me explain how this works.
After startup, `theme` struct references `lab_img`, which references `lab_img_cache` with `refcount=1`. Here, `lab_img_cache` is the wrapper for `lab_data_buffer` or `RsvgHandle` and represents the actual content of the loaded image file.
When a window is opened and its decoration is created, the `lab_img` is copied via `lab_img_copy()` and a new `scaled_img_buffer` …

img: fix UAF on Reconfigure by refcounting (attempt 2)

---

include/img/img.h
src/img/img-svg.c
src/img/img.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c

Closes #2450.
16dbdc64 changed the padding around the app icon in the titlebar to be applied both vertically and horizontally rather than only horizontally because it was more natural from a developer's perspective, but some users complained about the smaller icons in certain configurations.
So let's undo the change in 16dbdc64 and apply the icon padding only horizontally for now.
We can add configurations for the icon padding (or icon size independent from `window.button.{width,height}`?) later.

img: apply padding around window icon only horizontally

---

src/img/img-png.c

Cairo surfaces loaded with `cairo_image_surface_create_from_png()` are not always ARGB32 format. So this PR converts non-ARGB32 surfaces to ARGB32 to not abort in `buffer_adopt_cairo_surface()`.

img: don't abort with non-ARGB32 PNG files

---

src/common/set.c

I encountered with segfault when I tried https://codeberg.org/vyivel/keymap-replacer while fcitx5 is running (it didn't happen without fcitx5 for some reason).
This was because `lab_set_remove()` didn't expect keycode 0. When keycode 0 is passed to it, `set->size` could be negative as the first branch in the loop `if (set->values[i] == value)` could be taken over and over.
So this PR changes `lab_set_remove()` with the wlroots' approach: https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/util/set.c#L16.
Another possible approach is like below. Maybe this is slightly easier to debug, but I prioritized the simplicity in this PR. I don't have a strong preference on it though.
```c
void
lab_set_remove(struct lab_set *set, uint32_t value)
{
/* Find the matched element */
int found = …
```

set: prevent possible segfault when keycode 0 is released

---

src/output.c
src/server.c

Fixes #2465 by placing `osd_tree` above `menu_tree`.
This also prevents layer-shell surfaces from covering the OSD. I'm not sure whether to be higher, I prefer server-side component to be higher.
Before (higher-first):
- preview outlines (just above menu)
- menu
- layer-shell (top/overlay/popup)
- osd
After (higher-first):
- osd
- preview outlines (just above menu)
- menu
- layer-shell (top/overlay/popup)

osd: prevent preview outlines to be above OSD

---

include/input/ime.h
src/input/ime.c

This PR fixes a problem after 683f67b that Ctrl modifier state is stuck when pressed Ctrl+F (shortcut for word-search) in Firefox while Fcitx5 is running, which makes mouse scrolls zoom in/out the UI even after Ctrl key is released.
This doesn't affect the code path without input method running. Below is the detailed explanation:
<details><summary>details</summary>
When Ctrl+F is pressed, an input box is opened in the application and Fcitx5 creates a new virtual keyboard
(VK), whose initial modifiers is empty. Then prior to 683f67b, the key/modifiers events flowed like this:
- The compositor detects F key-release
- Modifiers (Ctrl pressed) are notified via `wlr_input_method_keyboard_grab_v2_set_keyboard()`
- F key-release is forwarded to IM
- IM sends modifiers (Ctrl) back to the …

IME: fix stuck Ctrl when pressed Ctrl+F in Firefox with Fcitx5

---

include/common/scaled-scene-buffer.h
src/common/scaled-scene-buffer.c

This fixes an issue with buffers not updating when an output is configured for a new scale. It also supports windows being on more than 2 outputs at once and in general simplifies the code.

scaled-scene-buffer: use outputs_update signal

---

src/theme.c

theme_name is NULL when <theme><name></name>...</theme> is in rc.xml
--8<--
I'd  guess trying to load e.g. `~/.local/share/themes/(null)/labwc/themerc`
is not a feature.

theme: don't try to load "themerc"s if theme_name is NULL

---

include/input/keyboard.h
src/input/cursor.c
src/input/keyboard.c
src/interactive.c
src/regions.c
src/seat.c
src/workspaces.c

And make mousebind handlers use that one.
Also remove `keyboard_any_modifiers_pressed()` and replace its usage with the new function.
Without this patch we would only request the modifier state of the keyboard group which makes mousebinds involving keyboard modifiers break for virtual keyboards like when using wayvnc. Same story for hiding the workspace overlay or snapping to regions.
Also includes a commit to set the repeat info for new virtual keyboards as we usually use the keyboard group for synchronizing that property.
Fixes:
- #2511
- #2513

keyboard: add keyboard_get_all_modifiers()

---

include/common/scaled-scene-buffer.h
src/common/scaled-font-buffer.c
src/common/scaled-img-buffer.c
src/common/scaled-rect-buffer.c
src/common/scaled-scene-buffer.c
src/server.c

A possible solution for the problem in #2518 that icon theme updates are not applied to the titlebar icons on reconfigure if multiple windows with the same app-id are present.
This PR moves `cached_buffers` in `scaled-{font,rect,img}-buffer.c` into `scaled-scene-buffer.c` and clears it at the beginning of Reconfigure to prevent them from being reused by newly created scaled_scene_buffers.

scaled-scene-buffer: block sharing of buffers created before reconfigure

---

src/config/rcxml.c

and internally replace `LAB_SSD_BUTTON_WINDOW_ICON` with `LAB_SSD_BUTTON_WINDOW_MENU` when libsfdo is not linked.
Extracted from #2518.

rcxml: ignore duplicated buttons in `<titlebar><layout>` individually

---

src/ssd/ssd-titlebar.c

d916a78 caused a regression that `<font place="InactiveWindow">` doesn't work.
I don't know why I made such a mistake...

ssd: fix InactiveWindow font not working

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/common/scaled-icon-buffer.h
include/common/scaled-img-buffer.h
include/config/rcxml.h
include/ssd-internal.h
src/common/meson.build
src/common/scaled-icon-buffer.c
src/common/scaled-img-buffer.c
src/config/rcxml.c
src/ssd/ssd-part.c
src/ssd/ssd-titlebar.c
src/theme.c

- The 3rd commit is just a refactor of `lab_img`. The horizontal padding in titlebar app icon is now applied by horizontally shrinking and shifting the icon buffer rather than adding empty spaces in the buffer in `lab_img_render()`.
- The 4th commit adds `str_equal()`. This is used by `_equal()` in `scaled_img_buffer` and `scaled_font_buffer`.
- The 5th commit introduces `scaled_icon_buffer`. Its benefits are:
- The best icon file is now dynamically chosen for each output scales.
- The titlebar app icons for the same application now shares its buffers and file handlers. This will also work for menu icons (#2509).
- The 6th commit adds `<theme><fallbackAppIcon>` used by `scaled_icon_buffer` when the icon for an app-id cannot be loaded. Its default value is 'labwc', which means we now fall …

Introduce scaled_icon_buffer and <theme><fallbackAppIcon>

---

docs/labwc-config.5.scd
docs/labwc-menu.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/menu/menu.h
src/config/rcxml.c
src/menu/menu.c

Can be tested with a toplevel "applications" menu (or some usual pipe menu)
```xml
<menu id="applications" label="foo" execute="labwc-menu-generator --icons --pipemenu" />
```
or a usual static menu item
```xml
<item label="Terminal" icon="foot">
<action name="Execute" command="foot" />
</item>
[..]
</menu>
```
Open questions:

menu icon support

---

NEWS.md
scripts/rip.c

@Consolatis We talked some time ago about doing this. Have eventually got around to it :smile: Thought I'd better do it before starting the `NEWS.md` update for `0.8.3` to safe myself some time.

Add helper to extract refs from `NEWS.md`

---

src/server.c

This fixes a UAF caused by trying to update the xcursor in a output destroy handler, in turn caused by destroying the backend.
Fixes:
- #2539

server: on exit, destroy backend first

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/ssd.h
src/config/rcxml.c
src/ssd/ssd-extents.c

When themes call for thick borders, having an even thicker extended area can be annoying, especially when trying to activate windows behind another when only the target window's border is visible. Let's provide a mechanism for adjusting or disabling the extension.
I'm open to suggestions for better configuration placement or option naming.

ssd: expose resize.minimumArea parameter

---

include/action.h
src/action.c
src/menu/menu.c

Fixes #2526.
`server->menu_current` should be cleared before calling `actions_run()` as it may internally call `menu_open_root()`. Clearing it after `actions_run()` leads to an inconsistent state where a menu is opened but `server->menu_current` is
`NULL`. It even lead to a segfault when the item opening another menu is contained in a pipemenu, because `menu_open_root()` calls `destroy_pipemenu()` when `server->menu_current` is set, which makes accessing `item->actions` a UAF.
This PR also replaces some code that ensures the menu is closed in `menu_open_root()` with `assert(!menu->server->menu_current);`.

menu: fix unexpected behavior when a menu is opened from another menu

---

.github/workflows/build.yml

Also disable it for now because we can just use the shipped version of libwlroots-0.18-dev rather than needing to build it ourselves.

CI: fix Debian build, wlroots package got renamed

---

docs/labwc-config.5.scd

fits better on 80-column terminal and is more consistent in style
especially, see the difference in windowSwitcher custom content lists:
`scdoc < docs/labwc-config.5.scd | nroff -mandoc -rLL=79n -rLT=79n -Tutf8  | less -R`
the 'S', 's' and 'i' look better (line breaks and no extra space between 'S' and - and 'i' and -)
(if your `andoc` had exactly same rules it could produce identical results as with me)
(and, thanks to strace(1) -f -ooo -s128 -e trace=execve for the nroff command line)

docs: labwc-config.5.scd: dedent windowSwitcher content lists

---

include/overlay.h
src/overlay.c
src/seat.c

Prevents a leak notification on exit. I think we can merge this within the cooldown period as side effects are unlikely.
CC @tokyo4j

src/overlay.c: clean up timer on exit

---

src/layers.c

Should fix a segfault detected by @cillian64 in #2576.

src/layers: handle layershell unmap without any outputs left

---

src/output.c

This works around a wlroots issue: https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3946
Fixes:
- #2576

output: set custom output mode on wlopm --on

---

src/output.c

This prevents a unnecessary output commit without buffer, showing up as black flash when repeatedly calling wlopm --on.
---
Reported by @cillian64 in #2579.
Should be fine to merge within the cooldown period as chances of this having side effects is minimal.

output: early return on wlopm if requested state is already set

---

src/output.c
src/server.c

See https://github.com/labwc/labwc/issues/2465#issuecomment-2661511564.
Honestly I'm not 100% sure this PR doesn't introduce another regression... but I believe the issue is something we should fix before 0.8.3.
Testing is appreciated.

osd: prevent preview outlines from overlapping OSD in first output

---

.github/workflows/build.yml

I've renamed `wlroots` to `wlroots018`, similar to Void. As labwc uses `latest` package set CI may break once [downstream package build](https://pkg-status.freebsd.org/beefy22/build.html?mastername=141amd64-default&build=1bb147345dca) finishes.
Without the rename it was expected to happen during wlroots 0.19 release unless labwc switched to the new API at exactly the same time.

CI: unbreak FreeBSD after a package rename

---

include/ssd-internal.h
src/ssd/ssd-titlebar.c

Before this PR, nothing was rendered in window icon button if the application doesn't set its app_id (e.g. nested kwin_wayland). This was my oversight in #2518.
This PR makes sure the fallback icon (set via `<theme><fallbackAppIcon>`) is shown instead, by removing `ssd->state.app_id` and the early-return in `ssd_update_window_icon()`. Note that `view_get_string_prop(view, "app_id")` returns an empty string if app id is not set, and passing an empty string to `scaled_icon_buffer_set_app_id()` always renders the fallback icon.
Removing `ssd->state.app_id` doesn't affect performance because `scaled_icon_buffer` caches app_id and `scaled_icon_buffer_set_app_id()` does nothing when a duplicated app_id is passed.

ssd-titlebar: show fallback icon when no app_id is set

---

docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

...to make it easier to snap windows on the edge between two monitors.
Fixes: #2602
@Consolatis @jlindgren90 @ahesford @tokyo4j - at the back of my mind there is something telling me that we picked `1` to avoid some other behaviour, but I have tested it with `10` on a multi-output setup and it seems to work really well. Just wanted to see if I could jog your memories on anything. If not, I suggest we try this value.

config: increase default <snapping><range> to 10

---

src/action.c
src/desktop.c
src/foreign-toplevel/foreign.c
src/input/cursor.c
src/osd.c
src/view.c
src/xdg.c
src/xwayland.c

- Don't call `cursor_update_focus()` every time the OSD is updated as it is no-op while window switching. Instead, they should be called at the beginning/end of window switching. This change functionally does nothing. Ref: https://github.com/labwc/labwc/pull/2584#issuecomment-2663425104
- Make it harder to mess up the window stacking order while window switching by adding a check for `server->input_mode` in `desktop_focus_view()` and `view_minimize()`. Especially the check in `view_minimize()` should prevent panels from minimizing a window while window switching.
- Allow only `PreviousWindow`/`NextWindow` actions while window switching. This should catch some actions that could not be filtered by the 2nd commit e.g. `SendToDesktop`. This was suggested by @Consolatis in IRC.
Both/either of …

Some fixes about focus or stacking order management while window switching

---

include/menu/menu.h
src/action.c
src/menu/menu.c

Split from #2531.
In this PR, scene-nodes of (sub)menus are lazily generated when they are being opened. This removes the need to call `update_client_list_combined_menu()` and `update_client_send_to_menu()` every time a root menu is opened. This also fixes the incorrect menu position with following configuration:
```xml
<menu id="foo" label="foo">
<item label="aaaaaa"/>
<item label="bbbbbb"/>
</menu>
<menu id="foo" />
<menu id="foo" />
</menu>
```
This PR also:
- Removes `menu_free_from()` in favor of simplicity.
- Allows linking to static menu from pipemenu. I think #2339 was enough to prevent ~static menus from opening in unexpected position~ circular menus.
- Renames `menu_configure()` to `menu_reposition()`.
- Asserts `server->menu_current != NULL` in …

menu: lazily generate menu scenes

---

include/menu/menu.h
src/menu/menu.c

In this PR, top-level pipemenus are dynamically generated rather than generating only on initialization.
But this PR also includes many refactors about how menus are generated and opened. Notably:
- All the menu scene-graphs are now lazily generated and repositioned when being opened. This fixes the problem of incorrect submenu position in configurations like:
```xml
<menu id="foo" label="foo">
<item label="aaaaaa"/>
<item label="bbbbbb"/>
</menu>
<menu id="foo" />
<menu id="foo" />
</menu>
```
- `struct menu` for pipemenus are created on initialization rather than after the execution of pipemenu script
- `update_client_list_combined_menu()` and `update_client_send_to_menu()` are called only when the corresponding menus are being opened
I admit this is a dangerous …

Pipemenu rework

---

include/common/box.h
include/magnifier.h
src/action.c
src/common/box.c
src/common/scene-helpers.c
src/config/rcxml.c
src/magnifier.c
src/server.c

...in preparation for fixing #2591.
- Functions defined in `magnifier.c` are renamed to have the prefix `magnifier_`.
- Use `wlr_output.swapchain.format` to obtain buffer format.
- Make sure magnifier scale never goes below 1.0. This should remove the need for `CLAMP()` macro defined in `magnifier.c`.
- Refactor `magnifier_draw()` (previously `magnify()`) to make it easier to follow.

magnifier: refactor

---

include/decorations.h
include/labwc.h
include/layers.h
src/decorations/kde-deco.c
src/decorations/xdg-deco.c
src/idle.c
src/input/cursor.c
src/layers.c
src/output.c
src/seat.c
src/server.c
src/xdg.c
src/xwayland.c

This ensures all event listeners are removed before the emitting wlroots object is being destroyed. This will be enforced with asserts in wlroots 0.19 but there is no reason to not do it right now either.
This change in wlroots 0.19 is implemented via commit 8f56f7ca43257cc05c7c4eb57a0f541e05cf9a79
"Assert (almost all) signals have no attached listeners on destroy"

project wide: clean up event listeners on shutdown

---

src/input/cursor.c
src/server.c
src/workspaces.c

project wide: clean up event listeners on shutdown (part 2)

---

include/labwc.h
include/osd.h
src/osd.c
src/output.c

This PR is a preparation for icons in the window switcher (https://github.com/labwc/labwc/discussions/2172#discussioncomment-12297481) which will be achieved by using `scaled_icon_buffer`. Also, this PR may reduce the overhead by not redrawing the whole osd when the selected item is updated.
This PR adds `output->osd_scene` which has 2 fields:
- `tree`: a scene-tree of per-output osd inserted as a child of `output->osd_tree`.
- `items`: a list of `osd_scene_item`s which are used to toggle the highlights for selected window item. In the future, `osd_scene_item` may be extended to support filled highlights for selected window item, or mouse interaction.
A concern about this PR is the ugly look of the window switcher when `osd.window-switcher.width` is too small:
|Before|After|
|-|-| …

osd: draw window switcher with scene-nodes

---

src/common/string-helpers.c

char **s not needed to get trailing whitespace trimmed, and rtrim() does not return anything
if there is leading whitespace in *s in call to string_strip(), there is less chars left to scan in rtrim().
---
noticed this while doing something; if it supposed to be as it is, i can amend this commit w/ comment

string-helpers: rtrim() with just char *s, call it later in string_strip

---

src/magnifier.c

[On behalf of @Consolatis]
Fixes
```
../src/magnifier.c:153:3: error: missing initializer for field ‘clip’ of ‘struct wlr_render_rect_options’ [-Werror=missing-field-initializers]
153 |   };
|   ^
In file included from ../subprojects/wlroots/include/wlr/render/wlr_renderer.h:14,
from ../subprojects/wlroots/include/wlr/types/wlr_output.h:17,
from ../src/magnifier.c:5:
../subprojects/wlroots/include/wlr/render/pass.h:115:27: note: ‘clip’ declared here
115 |  const pixman_region32_t *clip
```

src/magnifier: fix compile on ancient GCC versions

---

src/common/scene-helpers.c
src/magnifier.c

Fixes #2082 and #2591.
But I'm setting this PR as draft since this PR causes huge overhead for reallocation of the temporary buffer when the magnifier spans 2 outputs with different scales/transforms.
Possible solutions are:
1. Use a single temporary buffer with the biggest size (https://github.com/labwc/labwc/issues/2082#issuecomment-2292441444)
2. Always draw magnifier only in the output that contains the cursor and reallocate the buffer when the cursor moves between outputs
3. Allocate temporary buffers for each output (e.g. adding `output->magnifier_buffer`)
I'm not sure which one to choose, but I personally like (2.) since it will be the easiest to implement, like:
```diff
diff --git a/src/magnifier.c b/src/magnifier.c
index 9bf3c599..86c9cc4d 100644
--- a/src/magnifier.c
+++ …
```

magnifier: scale/transform the magnifier

---

docs/labwc-theme.5.scd
docs/themerc
include/theme.h
src/osd.c
src/theme.c

Suggested in https://github.com/labwc/labwc/pull/2621#issuecomment-2727469687.
This allows users to make the icon in window switcher bigger (or smaller) than the font size, which enables more Openbox-like appearance.
Example:
```
osd.window-switcher.item.icon.size: 50
```
```xml
<windowSwitcher>
<fields>
<field content="icon" width="15%" />
<field content="title" width="85%" />
</fields>
</windowSwitcher>
```
The default value is set to `font_height(&rc.font_osd)`, as it is right now. @johanmalm suggested deriving from the icon size in the titlebar (https://github.com/labwc/labwc/pull/2621#issuecomment-2727469687), but I personally don't think it's intuitive that changing the button size in titlebar changes the icon size in window switcher. This is not a strong preference, though.
This PR …

osd: add osd.window-switcher.item.icon.size

---

src/desktop-entry.c

This PR localizes application names in the window switcher set via `desktop_entry_name` or `%n` specifier.
Ref: #2607

desktop-entry: localize application names

---

src/config/rcxml.c

Fixes #2646.
Also handles duplicated `<windowSwitcher><fields>` entries so that users can overwrite the window switcher layout defined in `/etc/xdg/labwc/rc.xml` with `~/.config/labwc/rc.xml`, without overflowing contents.

rcxml: handle duplicated `<theme><titlebar><layout>` and `<windowSwitcher><fields>` entries

---

docs/labwc-theme.5.scd
docs/themerc
include/theme.h
src/theme.c
src/workspaces.c

Adds a theme option to configure border width of workspace boxes in osd.
Previews:
- master defaults
- new defaults
- example osd.workspace-switcher.boxes.border.width: 8
Note that master boxes are not square and 1px off-center (blue line).

osd: workspace switcher boxes improvements

---

docs/rc.xml.all

There is no "labwc" manpage in section 5 (man 5 labwc may fail or show e.g. labwc-action manpage).
Replaced one 'we' with passive form, to match the common style in docs/.
--
For the 'unwefify' part I did just somewhat straightforward active->passive change, but
there is change from 'contents' to 'content' - one reason is that it fits into 80 chars as
2 chars less (is->are would be the other). Also the 'content' match the 'content=...' in there.
One page that shows the difference of meaning of that with 'contents' alternative can be
seen in
https://textranch.com/c/many-kinds-of-things-or-many-kinds-of-thing/

docs: rc.xml.all: Fix reference to labwc-config manpage. Unwefify.

---

src/osd.c

Intended to be merged before the next release.
Fixes a regression in #2620 that emits errors like:
```
[../labwc/src/common/scaled-font-buffer.c:26] font_buffer_create() failed
```
...when `osd_field_get_content()` doesn't set non-null text.
Can be tested with the following configuration (`output` shows nothing when only one output is connected):
```xml
<windowSwitcher>
<fields>
<field width="100%" content="output" />
</fields>
</windowSwitcher>
```

osd: suppress errors with null window switcher fields

---

docs/labwc-config.5.scd

docs: list all supported font weights

---

src/view.c

Taking the simplistic approach of waiting until the view is mapped to minimize it. A more optimal but invasive approach could be to modify the `view->impl->map` functions to directly support map-while-minimized, but this would require some careful disentangling of the concepts of "minimized" and "unmapped", which overlap a bit in labwc.
Fixes: #2627
@tokyo4j if you could test that this fixes the issue you saw, I'd appreciate it.

view: handle initially minimized views (simple approach)

---

src/config/touch.c

I'm not sure if this is the best fix for the problem I have found, but it is the shortest...
If multiple touch configurations for the same device are defined - so more than one is defined in /etc/xdg/labwc/rc.xml, or one is defined in /etc/xdg/labwc/rc.xml and another is defined in ~/.config/labwc/rc.xml, I would expect the one which is read in last to be the one which takes effect. So I would expect the config in the local file to override that in the global file, or a config at the bottom of the global file to override one higher up in the file.
But what happens is that the first config found is the one which takes effect. This means that it is impossible to override a global config for a touch device with one in the local config file; the one in the global file takes precedence.
This …

Parse touch configs in reverse order to enable overriding

---

include/osd.h
src/config/rcxml.c
src/osd-field.c

Before this patch, window switcher fields could overflow if the sum of `<windowSwitcher><fields><field width="">` exceeds 100%.

rcxml: validate total osd field width

---

docs/labwc-actions.5.scd
include/input/cursor.h
include/labwc.h
src/action.c
src/input/cursor.c

Solution for https://github.com/labwc/labwc/discussions/2672
Simple keybinding example:
```xml
<keybind key="A-W-s">
<action name="ToggleScrollWheelEmulation" />
</keybind>
```
But this should also work for mouse bindings, like enabling emulation on button down and disabling on button up.
Includes https://github.com/labwc/labwc/pull/2704

feat: add scroll wheel emulation for cursor motion

---

.github/workflows/build.yml
scripts/ci/smoke-test.sh
src/main.c

...rather than emitting ugly errors like:
```
labwc: ../src/buffer.c:85: buffer_adopt_cairo_surface: Assertion `cairo_image_surface_get_format(surface) == CAIRO_FORMAT_ARGB32' failed.
```
Ref: #1526, [labwc-git AUR](https://aur.archlinux.org/packages/labwc-git#comment-984158)

Gracefully exit when no fonts are installed

---

src/xwayland.c

We used `view_toggle_maximize()` before which was always wrong. It didn't matter much because it's only relevant for repeated client side maximize requests.
With wlroots 0.18.x we still only get the `request_maximize` event when either both axis are maximized or not but with wlroots 0.19 we will get the event on any change of the two bools.
Split off from
- #2388
CC @jlindgren90

xwayland.c: support both axis for client side maximize requests

---

src/common/graphic-helpers.c
src/common/scaled-icon-buffer.c
src/common/scaled-img-buffer.c
src/common/scaled-rect-buffer.c
src/common/scaled-scene-buffer.c
src/menu/menu.c
src/osd.c
src/ssd/ssd-border.c
src/ssd/ssd-part.c
src/ssd/ssd-shadow.c
src/ssd/ssd-titlebar.c

This PR ensures that the sizes set in `wlr_scene_{rect,buffer}` never goes negative, which crashes in wlroots 0.19.
The 1st commit temporarily updates `wlroots.wrap` to depend on my fork of wlroots which has cherry-picked the commits that added abortions for negative sizes. This should be dropped before merging.
The 2nd commit guards against negative sizes in menu scenes (possible with `menu.width.{min,max}: 1`). It checks the lengths marked with red in the diagram below:
Likewise, the 3rd commit handles negative sizes in window switcher OSD (possible with `osd.window-switcher.width: 1`):
The 4th commit handles negative sizes in SSD by just adding `MAX()` macros. Another possible solution suggested by @Consolatis in IRC is to enforce minimal window size so that sizes of components like …

Guard against negative sizes in `wlr_scene_rect/buffer`

---

.github/workflows/build.yml
include/labwc.h
include/view.h
include/xwayland.h
meson.build
src/buffer.c
src/common/scene-helpers.c
src/desktop.c
src/input/cursor.c
src/input/ime.c
src/input/tablet.c
src/input/touch.c
src/magnifier.c
src/server.c
src/view.c
src/workspaces.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c
subprojects/wlroots.wrap

You know the drill.
Not intended to be merged anytime soon but it can be used to develop against the wlroots master branch for changes proposed there. Feel free to push chase commits to this branch (include the wlroots MR in he commit subject) but please don't do force pushes.
I do not recommend running this branch outside of dev work.
Upstream list of breaking changes:
https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3869
Issues:
JFYI @jlindgren90

Update for wlroots 0.19

---

docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

We enabled xwayland persistence for wlroots < 0.18.2 to prevent crashes, but it's no longer needed since we now depend on wlroots 0.19.

config: drop xwayland persistence workaround for wlroots < 0.18.2

---

include/view.h
include/xwayland.h
src/desktop.c
src/view.c
src/xwayland-unmanaged.c
src/xwayland.c

For testing/discussion. Depends on a wlroots change ~~that I haven't submitted yet~~ submitted here:
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4384
Offer focus by sending WM_TAKE_FOCUS to a client window supporting it. The client may accept or ignore the offer. If it accepts, the surface will emit a focus_in signal notifying the compositor that it has received focus. The compositor should then call `wlr_xwayland_surface_activate(surface, true)`.
This is a more compatible method of giving focus to windows using the Globally Active input model (see `wlr_xwayland_icccm_input_model()`) than calling `wlr_xwayland_surface_activate()` unconditionally, since there is no reliable way to know in advance whether these windows want to be focused.
Previous experimental wlroots …

xwayland: add/use wlr_xwayland_surface_offer_focus()

---

subprojects/wlroots.wrap

Make revision= track the 0.19 branch rather than a specific tag.

wlroots.wrap: use branch not tag

---

src/action.c
src/desktop.c
src/edges.c
src/server.c
src/ssd/resize-indicator.c

To address:
- https://github.com/labwc/labwc/discussions/2739
For longer cases, factor out the logic to new functions. For very short cases, just move the declaration before the switch.

treewide: remove empty statements in switch cases

---

include/view.h
include/xwayland.h
src/xdg.c
src/xwayland.c

This eliminates a bit of logic, including an extra XWayland connection.
See also:
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4553

xwayland: use wlr_xwayland_surface_has_window_type()

---

src/layers.c
src/xdg-popup.c
src/xdg.c

Our documentation (https://github.com/labwc/labwc/blob/master/CONTRIBUTING.md#naming-conventions) states that handlers should have prefix `handle_`.

Rename some handler functions to be more consistent

---

src/layers.c

Written trying to solve an issue reported with layershell clients getting blurry after system resume when using an output scale. Didn't fix that issue but still feels like the correct thing to do.

src/layers.c: send fractional scale before map

---

src/osd-field.c

osd-field: fix odd behaviors with `title` and `output` fields

---

include/layers.h
src/layers.c
src/node.c

...rather than unmap because that is the approach of sway and it also avoids wshowkeys crashing.
Fixes: #1153

layers: arrange layers on destroy

---

src/xdg.c

In some cases, we would schedule a configure event but not record that we had done so, leaving `view->pending_configure_serial` incorrect. This caused incorrect handling of in-flight commits that had not yet taken the new configure into account, such as assuming that the client had ignored the configured size and incorrectly resetting `view->pending`.
Fixes: #2774

xdg: add missing tracking of configure serials

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/ssd/ssd-shadow.c

This patch introduces optional drop shadows for tiled windows. The feature is controlled via configuration, allowing users to enable or disable shadows on a per-preference basis.
related issue https://github.com/labwc/labwc/issues/1797

ssd: add configurable drop-shadows for tiled windows

---

src/common/scaled-icon-buffer.c

This PR fixes the issue that window icons become the fallback one after Reconfigure, by setting `scaled_icon_buffer->view_{app_id,icon_name,icon_buffers}` in `scaled_icon_buffer_set_view()`.
The reason why the window icons were displayed before Reconfigure is that applications usually enable decorations and then set app_id which fires `handle_view_set_icon()`.
Demonstration of the issue:
https://github.com/user-attachments/assets/7e316a9a-c2a5-4409-a534-56536af89225

scaled-icon-buffer: fix window icons not loaded after Reconfigure

---

src/xdg.c
src/xwayland.c

This prevents a crash observed by the scaled-icon-buffer listening to the `view->events.set_icons` signal before it is initialized. For this to happen, the application needs to use the kde decoration protocol and set it on the xdg_surface before creating the xdg_toplevel.
Fixes:
- #2798

Ensure the view signals are initialized early

---

src/view.c

Discovered via `-Db_sanitize=address` with `Ctrl-C` of a nested instance with foot still running.

view.c: free icon name on view destroy

---

src/common/scaled-icon-buffer.c

`handle_view_set_icon()` calls `scaled_scene_buffer_request_update()` internally.

scaled-icon-buffer: don't render twice in scaled_icon_buffer_set_view()

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/libinput.h
meson.build
src/config/libinput.c
src/config/rcxml.c
src/seat.c

closes #2647.
i took most of the docs directly [from libinput](https://gitlab.freedesktop.org/libinput/libinput/-/blob/49eb6cb8ab2695a4ac8883d2be5148472563b8db/src/libinput.h?page=6#L5071-5074), i hope that's fine.
i tested it locally and it worked fine, but i haven't done extensive testing.

libinput: implement threeFingerDrag feature

---

docs/labwc-config.5.scd
include/input/tablet.h
src/config/tablet.c
src/input/tablet.c

Those are regular mouse buttons, but attached to a tablet tool (which looks like a mouse).
Not tested since I don't have such a device.
Closes #2775

input: support tablet tool mouse buttons

---

include/labwc.h
src/server.c

- Move global variables (`compositor`, `sig{hup,int,term,chld}_source`) into `struct server`
- Remove `sig{int,term,chld}_source` in `server_finish()`

server: some minor fixes

---

include/xwayland.h
src/view-impl-common.c
src/xwayland-unmanaged.c
src/xwayland.c

#2811 fixed an issue with WeChat but unfortunately exposed multiple focus-related bugs, affecting at least JetBrains CLion (probably other apps too).
These bugs were introduced by the addition of `view_offer_focus()` in #1142 but had remained masked due to treating NORMAL and DIALOG type windows as always wanting focus.
The general approach of #1142 still feels right to me, but it introduced some asynchronous behavior (labwc offers focus, client accepts it some time later) which is more of a headache to deal with, and broke some assumptions in the code.
Please see the individual commit messages for details.

CLion focus fixes

---

include/view.h
src/desktop.c
src/view.c
src/xwayland.c

desktop: give focus to a modal dialog rather than its parent

---

src/input/touch.c

Having a hover effect visible without interaction looks out of place when there is no cursor (the cursor becomes hidden for/after touch interaction until the next mouse or tablet interaction). Just clear the hover effect after touch-up to prevent this. Note that hover effects are still there during touch-move and touch-down.
We can end-up in such a hover-effect-without-cursor situation when using a touch screen and
- opening a labwc root/client window
- tap on an SSD maximize button
- since the tap closes the menu, but doesn't (yet) maximizes, the (invisible) cursor is still on the maximize button and keeps the hover effect alive.
This PR clears the hover effect once the tap is completed (no finger anymore on the touch screen).
I'm not 100% sure if `ssd_update_button_hover()` is meant to …

input: clear SSD hover effects after touch-up

---

meson.build
src/xdg.c
src/xwayland.c

Support `_NET_WM_ICON` property without waiting for [wlroots MR](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5079)
Just copied from https://github.com/consolatis/labwc/tree/feature/x11_icons

[No wlroots change required] xwayland: support _NET_WM_ICON

---

include/layers.h
src/layers.c
src/xdg-popup.c
src/xdg.c

Fixes:
- #2845
----
Testing appreciated (especially with layershell popups). Didn't spot any issues but only tested it lightly.

Destroy xdg_popups when its parent is destroyed

---

src/theme.c

What do you think of changing the default menu button from this:
to this:
With `icon` being the default, I don't suspect most users would notice it.
I feel the downward arrow just looks nicer.

theme: change builtin menu fallback button to arrow

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/default-bindings.h

...because Alt- keybinds should be for clients to use and the A-<arrow> default combination is a frequent user complaint because it prevents some common usage patterns like alt-left/right in web browers.
#2825

config: deprecate some key- and mousebinds

---

src/workspaces.c

When configuring labwc for the first time I encountered a - not really a bug but - odd behavior, where if you drag a window and switch workspaces, the window will not carry over. I think that this is an objectively incorrect solution, because you end up dragging a window that you can't even see, and when you switch workspaces while dragging a window, you probably imagined something else to happen.
I initially wanted that behavior because it would allow me to save on the SendToDesktop buttons, which I had to put on an awkward mouse button, because they just didn't fit anywhere else. 
Anyways, I have written a patch, because I'm using Gentoo and I can apply them immediately without needing to do anything besides tell my pkg manager about it. Despite that I think this patch might be useful …

Allow dragged views to be moved to other workspaces

---

include/layers.h
src/layers.c
src/node.c

Supersedes #2864.
Fixes #2858.
This PR reverts #1154 and fixes #1153 instead by simply skipping the being-unmapped surface in `arrange_one_layer()`.
Adding `being_unmapped` in `lab_layer_surface` aside from `mapped` doesn't feel very clean, but I think this is simpler than #2864.
I confirmed that destroying an output with layer-shell clients doesn't cause UAF and unmapping an layer-shell client (by running `kitten quick-access-terminal` twice) doesn't terminate the client.

layers: fix UAF when an output with layer-shell surfaces is destroyed

---

include/snap-constraints.h
src/resistance.c
src/snap-constraints.c
src/snap.c

With negative screen or window resistance (attraction), snapping can cause "flickering" in clients (like `foot`) that enforce constraints on sizes. As labwc tries to snap a window to an edge, the client may substitute its own size that does not quite reach the edge; this can leave the cursor in a position that, when it moves slightly, will cause the client to bounce rapidly between a size that puts its resize edge near the cursor and one that puts its resize edge near the snapping edge.
A similar issue appeared earlier with "grow to edge" or "shrink to edge" operations, which was handled by caching the "desired" size set by labwc and using that for subsequent edge checks. When the client overrules a configure request with a different size, we still remember our "intended" size, and use …

resistance: refactor snap constraints, use in interactive resistance

---

README.md

I would like you to add this mention about sway-audio-idle-inhibit, it is an idle screen inhibitor that prevents the screen from turning off based on audio, I tested it on Labwc and it worked very well.

Added information about idle screen inhibitor.

---

CONTRIBUTING.md

The Arch package is now an official Arch package with a new maintainer.
The Github account of the Artix Linux maintainer has been deleted.

docs: update package maintainer list

---

src/xwayland.c

Probably slipped through since most window icons are square anyway.
cc @Consolatis

xwayland: fix swapped width/height in _NET_WM_ICON stride calculation

---

src/img/img-svg.c

img_svg_render() calls g_object_unref() on the RsvgHandle in its error path, but the handle is owned by the shared lab_img_data struct and will be double-freed later by lab_img_destroy().
The double-free was introduced when img_svg_load() was split from img_svg_render(). The g_object_unref() should have been removed from img_svg_render() but was missed.
Fixes: 16dbdc64e58d66011bbf319b92de844dab0ca8d9
("ssd: rework titlebar button rendering")
cc @tokyo4j

img: fix apparent double-free in img_svg_render() failure path

---

docs/labwc-actions.5.scd
include/view.h
src/action.c
src/view.c

Following up from discussion #2869, this converts the view_edge enum to bitfields (similar to view_axis enum above), and adds a VIEW_EDGE_ANY value which combines all valid options.
This allows the user to query for any snap directions without using multiple query statements, ie:
```xml
<keybind key="W-Down">
<action name="If">
<query tiled="any" />
<then>
<action name="UnSnap" />
</then>
<else>
<action name="Iconify" />
</else>
</action>
</keybind>
```
This has been compiled and tested locally with no issues or aberrant behaviour.

actions: added query tiled=any comparison for rc.xml simplification

---

include/common/string-helpers.h
include/common/xml.h
include/osd.h
scripts/checkpatch.pl
src/common/meson.build
src/common/string-helpers.c
src/common/xml.c
src/config/rcxml.c
src/osd-field.c
t/meson.build
t/xml.c

- Remove state-machine variables in `rcxml.c`
- Convert all the attributes into nested/non-nested nodes so that we can just traverse `node->children`. This should also fix https://github.com/labwc/labwc/pull/2603#issuecomment-2708643312
- Support nested `If` actions
- Support `CDATA`
- Remove ordering constraint of attributes in `<keybind>`, `<mousebind>` and `<windowRule>` (#2391)
TODO:

rcxml: big refactor

---

include/common/xml.h
src/common/xml.c

Before this patch, first text nodes like the spaces between `<a>` and `<b>` below were also travered by LAB_XML_FOR_EACH(), with their keys "text":
```xml
<a>  <b>foo</b></a>
```

common/xml: let LAB_XML_FOR_EACH() skip first child text nodes

---

docs/labwc-config.5.scd
src/output.c

It is not really useful for other output backends and just results in no outputs being enabled at all. (This is mainly an annoyance for developers normally running with drm but occasionally nested.)

output: make autoEnableOutputs=no apply only to drm outputs

---

src/view.c

If they are not empty, then we are headed for use-after-free shortly. An assert() failure is easier to debug than UAF, so let's fail early.
Inspired by:
https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/8f56f7ca43257cc05c7c4eb57a0f541e05cf9a79

view: assert internal signals are disconnected before destroy

---

src/input/ime.c

Preparation for #2892.
I'm pretty sure that this doesn't cause any regressions, but feel free to delay merging this as this doesn't change any functionalities.

ime: don't use data argument in handle_input_method_commit()

---

src/xdg.c

Fixes: #2938
Either commit will actually fix the issue with mousepad, but I think we should do both:
- We shouldn't be setting a fallback position at all for views that aren't mapped yet. Just let the map handler take care of it.
- In the corner case where we really do need a fallback position (the initially-maximized case), we can still make the fallback position relative to the view's current output to reduce the surprise factor.

Fix xdg-shell views moving between outputs due to configure timeout

---

src/input/ime.c

Fixes #2978 by partially reverting #2894.
Perhaps we can revert this PR again in wlroots 0.20 by reordering the emitted signals, I'm not sure (ref: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/5107#note_3042631)

ime: fix segfault when IME is killed

---

src/common/scaled-icon-buffer.c

This causes blurry icons on non-integer scales and triggers an assert within cairo when using a output scale < 1.
Fixes:
- #2983

scaled-icon-buffer: prevent accidental downcasting of scale

---

src/osd.c

`wlr_scene_node_destroy(&output->osd_scene.tree->node);` does nothing for null pointer, but ASAN is unhappy about accessing `(NULL)->node`, saying: `runtime error: member access within null pointer of type 'struct wlr_scene_tree'`.

osd: add null-check for output->osd_scene.tree

---

src/menu/menu.c

This PR allows `client-list-combined-menu` and `client-send-to-menu` as submenus of static menus by creating them first.
Their labels are changed to "Windows" and "Send to desktop" which are the same as Openbox.
This PR also fixes my stupid mistake in #2971 that broke `client-send-to-menu`.
Link: #2992

 menu: allow client-{list-combined,send-to}-menu as submenu of static menu

---

src/menu/menu.c

This PR allows overwriting the icon of item linking to another menu like below (the icon for `krita` instead of `mpv` should be shown):
```xml
<openbox_menu>
<menu id="static-menu" label="Static Menu" icon="mpv" />
<menu id="root-menu" label="Root">
<menu id="static-menu" icon="krita" />
</menu>
</openbox_menu>
```
For comparison, Openbox seems to ignore `icon` property in toplevel menu definition in the first place and always follows `icon` property inside the `<menu>` that links to a static menu. So when we have following `menu.xml`:
```xml
<openbox_menu>
<menu id="static-menu" label="Static Menu"
icon="/usr/share/icons/hicolor/32x32/apps/mpv.png" />
<menu id="root-menu" label="Root">
<menu id="static-menu"
icon="/usr/share/icons/hicolor/22x22/apps/krita.png" />
<menu id="inline-menu" …
```

menu: allow overwriting submenu icon

---

src/menu/menu.c

Sequence of events:
- `menu_finish()` frees the sub-menu first
- the `selection.menu` of the parent menu is now dangling
- `menu_finish()` frees the parent menu
- `menu_free()` calls `menu_close_root()` on the parent menu
- `menu_close_root()` tries to close the (freed) sub-menu
- boom
Extending `nullify_item_pointing_to_this_menu()` avoids the crash.
Fixes:
- #2997

menu: fix use-after-free at exit with sub-menu selected

---

docs/menu.xml
src/menu/menu.c

...because that is more flexible and how it is in openbox.
I have had in mind that we should do this since the original implementation, and #2994 just jogged my memory.

menu: use client-send-to-menu as 'Workspace' submenu

---

src/config/rcxml.c
src/seat.c

The first commit restores the old behavior prior to #2667 that empty values in `<libinput>` are ignored.
The second commit implements what I proposed as "future plan" in https://github.com/labwc/labwc/issues/3006#issuecomment-3197033177. Reconfiguring a libinput device with empty values now restores its default values, rather than leaving its old configuration before Reconfigure. This makes `rc.xml` more declarative.
I wonder whether we should allow empty values in other places (e.g. `<margin top="" />`). They were allowed before #2667, but I don't find empty values useful outside of `<libinput>`. If we allow empty values in all the configurations, we will need add `if (string_null_or_empty(identifier)) { continue; }` in `fill_region()`, `fill_window_rule()` etc., or we can skip nodes …

rcxml: allow empty values in <libinput>

---

src/desktop-entry.c

Use the base instead of the full string for the comparison.
The desktop_id_base is currently basically unused.
---
I noticed that something was weird when Godot would show the Zeal icon.
Debugging session:
---
I think the partial match search could be improved.
The id of the desktop file is: `org.godotengine.Godot4.4`. So there are various difficulties with it finding the correct icon ;).
But I am already pretty happy with it no longer showing a wrong icon, and instead showing the labwc icon (default.)

desktop-entry: fix partial string matching

---

src/interactive.c
src/view.c

When implementing single-axis maximize some time ago, I made the simplifying assumption that a view couldn't be resized while maximized (even in only one axis). And indeed for compositor-initiated resize, we always unmaximize the view first.
However, I didn't account for the client resizing the non-maximized axis, which we can't (and shouldn't) prevent. When this happens, we should also update the natural geometry of that single axis so that we don't undo the resize when un-maximizing.
P.S. xdg-shell clients resizing the *maximized* axis is still an unsolved problem, exacerbated by the fact that xdg-shell protocol doesn't allow clients to even know about single-axis maximize. That's the problem at the root of:
- #3018
P.P.S. the view_invalidate_last_layout_geometry() logic may need …

view: respect client-initiated resize of non-maximized axis

---

docs/labwc-actions.5.scd
src/action.c

Adds an option "toogle" to GoToDesktop.
In case the target equals current, we go back to the last desktop instead if configured.
This is inspired by the tweak available in xfwm4, see https://docs.xfce.org/xfce/xfwm4/wmtweaks:
"Remember and recall previous workspace when switching via keyboard shortcuts".
Example of rc.xml
```xml
<keybind key="C-F1">
<action name="GoToDesktop">
<to>1</to>
<toggle>true</toggle>
</action>
</keybind>
```
I like this option a lot because I have, e.g., my browser on Desktop 1 and code on another one. Quickly pressing Ctrl-F1 brings me to the browser to read up sth and pressing again Ctrl-F1 allows to be back in code.
If you like the contribution, I'd be happy to contribute also documentation and other parts if needed. First, wanted to understand if you are …

action: add toggle for GoToDesktop

---

include/config/rcxml.h
include/config/types.h
include/osd.h
include/output.h
include/view.h
include/window-rules.h
src/config/rcxml.c
src/img/img-xbm.c
src/input/cursor.c
src/view.c

- add `LAB_WINDOW_TYPE_INVALID` in place of literal `-1`
- document more clearly that `enum lab_view_criteria` is a bitset
- other one-off replacements of integer values/types for consistency
Note: variables of type `enum lab_view_criteria` are already used extensively throughout the code to contain combinations of the declared enum values. I am not introducing any new usage here, just changing the single `uint32_t` to be consistent with all the other usages.

tree-wide: use enum types/constants where appropriate

---

include/config/libinput.h
src/config/libinput.c
src/seat.c

I needed to debug an input configuration issue and found the debug output not-super-helpful, so I made some improvements:
- Print the name and "sysname" (e.g. event11) of the device being configured. Note that the name alone isn't enough since there can be multiple identically-named devices.
- Print the config category matched for each device.
- Print the config values (if any) being applied. For enums, only the numeric value is printed since I'm lazy.
- Don't print "pointer acceleration configured" if neither a pointer speed nor acceleration profile is configured (it's confusing).

seat: improve debug logging when configuring input devices

---

src/common/scaled-icon-buffer.c

Fixes https://github.com/labwc/labwc/pull/2981#issuecomment-3238675460.
This commit fixes that client-side icons were not loaded when the rendered icon size is larger than icon sizes from the client. This bug has become more likely to happen due to the new thumnail-style window switcher.
The cause was `abs(INT_MIN)` becomes `INT_MIN` due to integer overflow.

scaled-icon-buffer: fix large client-side icon not being loaded

---

clients/meson.build
meson.build

Moved to clients/meson.build as per the comment in meson.build.

meson.build: move lab-sensible-terminal install routine.

---

include/overlay.h
src/debug.c
src/input/tablet.c
src/input/touch.c
src/interactive.c
src/osd/osd-thumbnail.c
src/output.c
src/overlay.c
src/regions.c
src/resize-outlines.c
src/seat.c
src/workspaces.c

- Use a single `lab_scene_rect` for both overlay background and outlines, like I described in the TODO comment in #2809.
- Simplify the resource management by destroying the overlay tree when it's hidden. I think its overhead is pretty minimal.
- Share a single `lab_scene_rect` for both region/edge overlays.

overlay: refactor

---

include/view.h
src/input/cursor.c
src/interactive.c
src/view.c

When resizing in only one axis (horizontal/vertical), there's no reason to un-maximize the other axis.
Most of the supporting logic was landed already in:
- #3020
However, that PR fixed only the client-initiated case. Let's do the same for interactive resize.
The first commit is prep work, eliminating `view_restore_to()` and exposing `view_set_maximized()` instead.
Then all that remains is to make a small change in `interactive_begin()` (second commit).

interactive: un-maximize only axes that are being resized

---

docs/rc.xml.all
include/config/default-bindings.h

...because it is probably what most people expect and it makes the behavior consistent with that of Openbox.
Fixes: #3039

default-bindings.h: focus & raise on border press

---

src/view.c

I don't know the purpose of the removed lines, but they are from 4 years ago when labwc didn't use scene-graph API and I'm sure they are redundant.

view.c: remove cruft in view_apply_maximized_geometry()

---

include/common/array.h
include/common/mem.h
include/idle.h
src/common/mem.c
src/idle.c
src/server.c

A couple of trivial cleanups:
- Remove an unused parameter & struct member
- Make use of a function that exists already, rather than repeating it

Trivial cleanups

---

src/output.c

Introduced in #3062.
Its usage is guarded by a wlroots version check
which prevented the CI to detect the issue.
When compiled with a wlroots version > 0.19.0
(like the chase 0.20 PR) the error shows up.

src/output.c: restore drm lease include

---

src/desktop.c

Removes log spams when the cursor is on resize-indicator:
https://github.com/user-attachments/assets/27fdb17a-0fee-4966-9d4b-8604d79b3356
In #2993, I thought there are only window contents and SSD under `view->scene_tree` and forgot about the resize-indicator.
I also refactored the logic around it:
- Remove `ret.node->type == WLR_SCENE_NODE_BUFFER` check since it's already done by `lab_wlr_surface_from_node()`
- Eliminate duplicated call to `lab_wlr_surface_from_node()`

desktop.c: don't print errors when cursor is on resize-indicator

---

include/common/node-type.h
include/node.h
include/scaled-buffer/scaled-icon-buffer.h
include/scaled-buffer/scaled-img-buffer.h
include/ssd-internal.h
src/desktop.c
src/node.c
src/output.c
src/scaled-buffer/scaled-buffer.c
src/scaled-buffer/scaled-icon-buffer.c
src/scaled-buffer/scaled-img-buffer.c
src/ssd/ssd.c

This PR shouldn't change any behaviors.
The 1st commit removes `LAB_NODE_SCALED_BUFFER` node type and `scaled_{img,icon}_buffer_from_node()`. I remember those functions were required for updating window icons some time ago, but they are not used anymore.
The 2nd commit removes `LAB_NODE_TREE` node type. It was attached to `output->layer_popup_tree` etc., but I don't think they are needed. CC @johanmalm
The 3nd commit attaches `LAB_NODE_SSD_ROOT` to `ssd->tree` instead of `LAB_NODE_NONE`, as I described in https://github.com/labwc/labwc/pull/3050#discussion_r2328158193. I also updated `get_cursor_context()` to make my intent clearer.

node-type: some cleanups

---

.clang-format
include/config/rcxml.h
src/config/rcxml.c
src/interactive.c
src/osd/osd-thumbnail.c
src/ssd/ssd-titlebar.c
src/theme.c

Some more miscellaneous small cleanups. These are the last of what I've had collecting locally.
- A small refactoring to use fixed arrays for `rc.title_buttons_*`. These are just lists of `enum lab_node_type`, with a bounded size and no middle-insertions/removals, so linked lists are overkill. Also, the use of `wl_list_for_each[_reverse]` just to access the first or last entry in the list (corner button) was weird.
- Some little syntactic cleanups (add `const`, reorder initializers, add braces around a `case` block).
- Some minor tweaks to `.clang-format` to make it match our coding style a little better.

More small cleanups

---

src/view.c

Fixes #3077.
The problem was the branch at the line 230 was always taken.

view: fix <query monitor="current|left|right" />

---

README.md

...as it is very old and not relevant anymore.

README.md: remove high-level scope summary

---

docs/labwc-theme.5.scd
docs/themerc
src/theme.c

Extracted the first commit from #3118 for merging before 0.9.2 release.
Previously, the default values of `osd.window-switcher.style-thumbnail.item.active.{bg,border}.color` were blue. But they caused the selected window title in the window switcher to be unreadable due to duplicated colors of the text and background with Openbox themes like Numix.
Instead, this commit updates them to follow other themes configurations. The default border color of the selected window item is now `osd.label.text.color` with 50% opacity and the background is `osd.label.text.color` with 15% opacity.
For subpixel antialiasing to work, the background color is calculated by manually blending `osd.label.text.color` and `osd.bg.color`, rather than just updating the alpha with 50% or 15%.

osd-thumbnail: update default colors of selected window item
