include/labwc.h
src/cursor.c
src/view.c
src/xdg.c
src/xwayland.c

The maximize button on SSD works and the maximize button and double-clicking the title bar works on CSD
TODO: It currently does not factor taskbars (I tested with waybar) into account, and when unmaximizing a window it does not remember what the previous location or size was

Add basic maximize support

---

docs/meson.build
meson_options.txt

See swaywm/sway#3452. To be used by Gentoo and [FreeBSD](https://github.com/freebsd/freebsd-ports/commit/d1251e059251dd28901b71374eb78b5c68514cc3).
```
$ pkg install hs-pandoc
$ meson setup -Dman-pages=disabled _build
[...]
Program pandoc skipped: feature man-pages disabled
[...]
```

Allow downstream to disable manpages even if pandoc is found

---

docs/meson.build

Manpages may not be accessible by `man` command. [Affects](https://github.com/freebsd/freebsd-ports/commit/f633acc8477c5d07c28eab9353e56ed028d3012d) at least [FreeBSD](https://github.com/freebsd/freebsd-src/blob/releng/13.0/usr.bin/man/man.sh#L1015).
```
$ meson setup --prefix=/usr _build && meson install -C _build
[...]
Installing docs/labwc.1 to /usr/share/man/man.1
Installing docs/labwc-config.5 to /usr/share/man/man-config.5
Installing docs/labwc-theme.5 to /usr/share/man/man-theme.5
Installing docs/labwc-actions.5 to /usr/share/man/man-actions.5
[...]
$ man labwc
No manual entry for labwc
$ man labwc-config
No manual entry for labwc-config
```

docs: move manpages to proper section directories

---

meson.build

Regressed by fd4ea3542fdc. From [error log](https://github.com/johanmalm/labwc/files/6321069/labwc-0.2.0.log):
```
Neither a subproject directory nor a wlroots.wrap file was found.
Subproject  wlroots is buildable: NO (disabling)
meson.build:50:2: ERROR: All keyword arguments must be after positional arguments.
```

Unbreak build with system wlroots 0.13

---

subprojects/seatd.wrap
subprojects/wlroots.wrap

This simplifies building as there's no need to manually
git clone subprojects anymore.

meson: Use wrap files to manage dependencies

---

meson.build

did not build with '<0.15.0', so bumped to  '<=0.15.0'

meson: bump wlroots dependency version number

---

src/server.c

This makes primary selections work at least with wayland-native Emacs (using the pgtk backend) and Firefox. I haven't tested others.
I can't claim credit for fixing this. I found the following in a Wayfire release notes page
> primary-selection protocol
> This protocol is needed for middle-click-paste to work. The implementation of the protocol is mostly done by wlroots, so Wayfire needs just a couple of lines for it to work. However, enabling it initially caused crashes in all GTK applications. After hours of debuggingg, it turned out to be a bug in GTK3, and I had to change the ordering of globals (wayland protocol objects) so that the primary-selection global is one of the first advertised. Phew!
and although the symptoms aren't the same, the fix seems to work anyway …

workaround Gtk primary selection bug by changing order of globals

---

src/keyboard.c

Change the code that detects when to stop cycling the view,
so that instead of looking for the left Alt key release it
looks for all modifiers released (thus. will work whether you
have this action bound to Alt-Tab, C-Tab, Meta-Tab, etc)
To do this we move the test from keyboard_key.notify to
the later signal keyboard_modifiers.notify, because the xkb_state
has been updated by then and the modifier state will be
accurate

fix cycle_view for bindings other than Alt_L

---

src/output.c

Symptom: the screen outside of the active window intermittently blanks and unblanks (looks like it's correlated somehow with mouse pointer events)
Cause: style cleanups in ea3ea497837f  changed the use of the preprocessor symbol DEBUG, which is now defined to (0) even when debugging should not not be enabled, so change from testing it with `#ifdef` to `#if`

fix madly flashing background

---

meson.build

If `-or-later` is not specified, it can be generally assumed that it's `-only`, this however makes it clear.

Specify GPL-2.0-only

---

include/labwc.h
src/action.c
src/desktop.c
src/view.c

Implements 3 actions present in openbox but not yet implemented in labwc and changes the default target for keyboard actions to the focused window rather than the topmost mapped window.

improve actions

---

src/output.c

I tested this using swaybg running under a labwc session nested under another labwc session.
Closes #99.

update layer surfaces on output geometry changes

---

src/keyboard.c

I had a bug where cycle view would not close and I was unable to switch to a TTY as it was open.
Signed-off-by: Joshua Ashton <joshua@froggi.es>

keyboard: Fix cycle view taking precedence over TTY switch

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/mousebind.h
src/config/mousebind.c
src/config/rcxml.c
src/cursor.c

This will add support for the iconify, maximize, and close mouse contexts, as well as for the press, click, release, and double click (already supported) mouse events.
I moved the default actions of the iconify, maximize, and close buttons to click mouse bindings. This felt more natural to me.
I also changed up the formatting of labwc-config(5) a bit because `'TitleBar'` wouldn't display with mandoc's or busybox's man commands. I'm not sure if this is the case for man-db's man.

More mousebinding support

---

include/labwc.h
meson.build
src/subsurface.c
src/view-child.c
src/xdg.c

`server_{init,finish}()` still collide with seatd (at least, with 0.5.0) - I'll fix that in a separate PR.

Add support for static wlroots

---

src/output.c

When `labwc` is started in its default configuration, all display outputs are initially disabled.  `sway` does not have the same issue.  In comparison with the `sway` code, it appears the `labwc` is missing a call to `wlr_output_enable()`.
Fixes the following error with `wlroots-git` 0.14.0.r391.g585a908a-1:
[DEBUG] [types/output/output.c:603] Tried to modeset a disabled output

Enable new outputs (before setting mode)

---

include/labwc.h
src/action.c
src/config/rcxml.c
src/cursor.c
src/desktop.c

This makes it possible to move a window by dragging its titlebar.  Tested working with my existing Openbox config.
I'm new to the `labwc` code, so apologies if I missed anything.
Example config snippet:
<mouse>
<context name="Titlebar">
<mousebind button="Left" action="Drag">
<action name="Move"/>
</mousebind>
</context>
</mouse>

Basic support for Drag/Move action

---

src/xdg.c
src/xwayland.c

When a window title changed dynamically (for example when running
"cd" within an xfce4-terminal), the titlebar did not immediately
update to show the new title.  (The titlebar would update as soon
as the mouse cursor moved.)
Calling `damage_all_outputs()` might not be the most optimal fix,
but it at least seems to work.

Force repaint after window title changes

---

src/output.c

The mouse cursor was invisible after starting `labwc` (and only appears once the mouse is physically moved).
The root cause seems to be that `wlroots` tracks cursor state on a per-output basis (see the `wlr_output_cursor` module) and doesn't update it correctly when outputs are changed.  So after adding a new output, the `wlr_output_cursor` on that output is invisible, while a stale cursor image is displayed on a previous output.  As soon as the mouse is moved again, the cursor image "jumps" from the previous output to the new one.
Long-term, it may be better to work on fixing the root cause of the issue in `wlroots`, but that would be a bit too involved for me at the moment.

Fix invisible cursor at startup

---

src/output.c

When an output is added or removed, the position of the other
outputs can also change, resulting in windows moving between them.
We need to redraw all the outputs (not just the new one) to prevent
stale/corrupted screen contents.

Fix graphical artifacts after adding/removing outputs

---

include/labwc.h
src/action.c
src/cursor.c
src/keyboard.c
src/menu/menu.c

This requires `action()` to know the resize edges to use, so thread them through.

Implement Resize as an action

---

src/config/rcxml.c

These were being ignored before. The only menu currently supported by labwc (from what I could tell) is "root-menu", but even that cannot be triggered by mouse bindings without this fix.

Parse menu names from Menu mouse-bindings

---

include/ssd.h
src/config/mousebind.c
src/cursor.c
src/desktop.c
src/ssd.c

This changes mouse event handling to better match Openbox (in that mouse bindings on the Frame context swallow the event while others do not) and support more mouse contexts.
After these changes, mouse bindings should be expressive enough to remove some hard-coded logic in favor of default bindings.

Implement Frame, Client, and Root mouse binding contexts

---

src/cursor.c

I just noticed this was broken as fallout from my last PR. Sorry about the regression.

[bugfix] forward click events to layer surfaces

---

src/cursor.c

This was broken when we added `ssd_part_type`s other than NONE that are not decoration. See discussion on PR #138.

[bugfix] Correctly detect when cursor is over titlebar

---

src/action.c
src/config/rcxml.c
src/cursor.c

Now that we have more flexible event handling, we can move a fair amount of logic to default configuration.
This should be carefully tested to make sure that behavior is identical, but I haven't been able to detect a difference. Remember to test with `labwc -c /dev/null` or similar so that the default config is used.

Unhardcode defaults

---

src/action.c
src/keyboard.c

A couple of improvements to the Alt-Tab window switcher:
- Pressing Alt-Tab a single time should switch to the next window
- Pressing Escape should cancel the window switcher
These changes both make `labwc` work more like OpenBox and other stacking WMs.
Thanks!

Alt-Tab switcher improvements

---

src/foreign.c

This is required for taskbars to behave as expected.

Raise activated foreign windows

---

src/view.c

This was causing (among other issues) windows from foot, chromium, and other programs that change their titles to lose their window icons when minimized and reactivated using waybar.

[bugfix] Query passed prop, not 'title'

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/libinput.h
src/config/libinput.c
src/config/rcxml.c
src/seat.c

This is a standard libinput option that wasn't exposed yet. Docs included.

Add tapButtonMap libinput setting

---

src/xdg.c
src/xwayland.c

To reproduce, open an editor from a terminal, minimize it, then hit ^C in the terminal.
The crash can be avoided if we simply don't unmap xdg or xwayland views if they are not currently marked as mapped.

[bugfix] Don't crash when a minimized window closes

---

src/osd.c

This happened while running Xwayland *over* waypipe, so is likely not a common case, but is possible.

[bugfix] Fix crash in osd.c when props are NULL

---

include/key-state.h
src/key-state.c
src/keyboard.c
src/meson.build

When key press events are handled by compositor keybindings, do not
forward the corresponding release events to clients.

keyboard: absolve release event if press was bound

---

include/labwc.h
src/action.c
src/foreign.c
src/view.c

I've basically copied #140 + the action handler for Close.
While doing that I also wrapped view->impl->close(view) in a view_close(view) function which AFAIU seems to be the desired design. The action handler for Close now uses view_close(view) as well.
I've only tested the PR using mate-panel (including context menu PR) but it should work with any foreign-toplevel client.

Implement foreign toplevel close

---

include/config/mousebind.h
src/config/mousebind.c
src/config/rcxml.c

Issue arises when using the default config from docs/rc.xml.all.
Without this patch only the last action defined inside a `<mousebind>` will have an effect.
Without a config or when defining the same `<mousebind>` multiple times with each containing only a single `<action>` the issue does not exist.

config/rcxml: Allow multiple <action>s inside of a <mousebind>

---

docs/rc.xml.all

This makes labwc feel way more intuitive when using the default rc.xml config.
Might be something for an issue instead:
Repeating Focus/Raise everywhere we interact with a Frame points to labwc missing a context or similar.
Something along the lines of
```
<context name="Frame" filter="unfocused" passthrough="yes">
<mousebind button="Any" action="Press">
<action name="Focus">
</mousebind>
</context>
<context name="Frame" filter="unraised" passthrough="yes">
<mousebind button="Any" action="Press">
<action name="Raise">
</mousebind>
</context>
```
Or as alternative:  
- restore raiseOnFocus to work without force-enabling followMouse
- a new dynamic context called FrameUnfocused which passes events to Frame/Client but allows to `mousebind` so it can be focused on Press which then in turn …

docs/rc.xml.all: Add focus + raise to TitleBar movement / maximize

---

src/output.c
src/view.c

`wlr_output_layout_get()` seems to return `NULL` for disabled outputs.
Fixes: #174

Check the return value of wlr_output_layout_get() for NULL

---

src/seat.c
src/xdg.c

Handlers for the "destroy" signal need to unregister themselves from the signal (using `wl_list_remove()`) before invoking `free()`.
Invalid write of size 8
at 0x487DF27: wl_list_remove (in /usr/lib/libwayland-server.so.0.20.0)
by 0x4906FF0: wlr_signal_emit_safe (signal.c:32)
by 0x48EA304: reset_xdg_surface (wlr_xdg_surface.c:430)
by 0x48EA3D6: UnknownInlinedFun (wlr_xdg_surface.c:464)
by 0x48EA3D6: xdg_surface_handle_resource_destroy (wlr_xdg_surface.c:282)
by 0x4877899: ??? (in /usr/lib/libwayland-server.so.0.20.0)
by 0x487DEBF: ??? (in /usr/lib/libwayland-server.so.0.20.0)
by 0x487E3DF: ??? (in /usr/lib/libwayland-server.so.0.20.0)
by 0x487830D: wl_client_destroy (in /usr/lib/libwayland-server.so.0.20.0)
by 0x48783F6: ??? (in /usr/lib/libwayland-server.so.0.20.0)
by 0x487B1C9: …

Fix use-after-free errors detected by valgrind

---

src/view.c

Before this change a window that had been minimized showed up with states Minimized and Activated.
For foreign-toplevel clients like taskbars that could mean to handle multiple windows at once having a 'activated' state even though they were clearly minimized.
I am not 100% sure this PR won't have negative side effects as we are now additionally calling `set_activated(view, false)` in xdg.c / xwayland.c. To fix the issue at hand it would have been enough to call `wlr_foreign_toplevel_handle_v1_set_activated(handle, false)` in view.c but that seemed like a half fix where other parts of the code would still think this window is actually active. So I chose the generic `view_set_activated(view, false)` (which calls into `view->impl->set_activated(view, false)`) instead.
There may be a better …

view.c: Remove 'activated' flag when minimizing a view

---

src/view.c

Before: window -> maximize -> fullscreen -> unfullscreen would reset pre maximized state
Now: window -> maximize -> fullscreen -> unfullscreen -> unmaximize works as expected
This feels like a hack though.
I tried something like this as well:
```
view_move_resize(view, view->unmaximized_geometry);
if (view->maximized) {
view->maximized = false;
view_maximize(view, true);
}
```
but view->x and friends were still based on the fullscreen dimensions so it again overwrote the original premaximized state.
That would also cause a double resize which may not look that great for the user.
Maybe somebody has a better idea how to handle that (one could add something like view->unfullscreen_geometry but that feels like overkill).

view:c Do not overwrite unmaximized dimensions on fullscreen

---

src/foreign.c

Closes #172
I switched to `if (view) { .. }` because it saves a return line but I could change the PR if you prefer the check with return directly after `wl_container_of(..)`.

src/foreign.c: verify associated view is still valid

---

include/labwc.h
src/desktop.c
src/xdg.c
src/xwayland.c

Activate is used by Steam for bringing up/focusing the chat windows, and minimize is used on the CSD by Steam and many apps.

xwayland: Implement activate and minimize

---

src/view.c

This will resize the window to the proper boundary.
Fixes #137.

Remaximize views when toggling decorations

---

include/labwc.h
src/output.c
src/view.c

labwc currently doesn't handle output layout changes very well:
- Windows can end up "lost" completely offscreen
- Maximized/fullscreen windows can end up spanning multiple outputs
Currently, `new_output_notify()` and `output_destroy_notify()` contain logic
to update the cursor and force a repaint when outputs are added or
removed.  This logic in fact needs to run on any output layout change,
so consolidate it into a new function, `output_update_for_layout_change()`.
Then add a second new function, `view_adjust_for_layout_change()`, which
adjusts window placement to account for the new layout.
The behavior is roughly as follows:
- Normal windows that end up offscreen are centered on the closest
output (making use of the existing `view_center()` logic)
- Maximized windows are re-maximized …

Adjust views to account for output layout changes

---

include/action.h
include/config/keybind.h
include/config/mousebind.h
include/labwc.h
include/menu/menu.h
src/action.c
src/config/keybind.c
src/config/mousebind.c
src/config/rcxml.c
src/cursor.c
src/keyboard.c
src/menu/menu.c

I converted all actions to a `wl_list` containing `struct action`. That is: keybindings, mousebindings and menus.
Seems to work so far. For example this now works:
```
<keybind key="A-1">
<action name=ToggleDecorations" />
<action name=ToggleMaximize" />
</keybind>
```
Struct currently looks like this:
```
struct action {
uint32_t type;
char *arg;
struct wl_list link;
};
```
~~Open questions:~~
~~- Should `action_create(action_str)` get a `wl_list` pointer as second argument and add itself to that list?~~
~~Currently it is the responsibility of the caller to add the created action to its list.~~
~~Do not merge the PR as is, it contains debug statements in action.c and changed the global loglevel to INFO.~~
Is the approach generally usable or should it be changed in design or …

Allow multiple actions at once

---

src/config/rcxml.c
src/menu/menu.c

- Reset `current_mousebind` when assigning a new `current_mouse_context`
- Reset `current_*_action` when creating a new `{key,mouse}bind` or `menuitem`
- Reset `current_*` in `rcxml_finish()`
- Check for `current_*` before trying to create a new action
- Check for `current_*_action` before trying to set `action->arg`
- Check for `current_mouse_context` before creating a new mousebind
- Complain to the user about most invalid config entries

More robust rc.xml parsing

---

src/interactive.c

By @skyne98 in #122:
> As an additional point, I think it is important to allow users to drag the windows which were double-clicked back into their original forms (and sizes), making them not full-screen again.
I gave a try at implementing that feature.
The PR uses the fractional position of where the cursor is located related to size and position of the maximized window and scales it down to the unmaximized state.
The window will then be positioned on both axis based on the calculation and the current cursor position so it will not suddenly jump around and (at least for me) it feels natural to drag, both when moving by grabbing the title bar and when moving with `A-BTN1` or a generic `Move` keybind.
I had used `struct border` before to determine the required offsets but then it would …

Unmaximize on Move

---

src/cursor.c

Fix two separate bugs that predate, but were exposed by, ae43d4b9d1c8fb1a758fa9f212f629a72e6d7c27 ("Unmaximize on Move"):
1. Double-clicking on the titlebar and then moving the mouse (while still held after the second press) would trigger both a DOUBLECLICK and then also a DRAG binding, resulting in the window maximizing and then immediately unmaximizing.
2. Clicking on the maximize button would trigger a CLICK binding but also leave a DRAG binding active, resulting in the window unmaximizing and moving as soon as the mouse moved, even though the mouse button was no longer held.
More details in the commit messages.

Fix stuck mouse drags when maximizing a window

---

docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/cursor.c
src/interactive.c

Basic support for window snapping by "throwing" the window onto an edge.
See #122 for context.
rc.xml.all got two new options:
```
<snapping>
<range>1</range>
<TopMaximize>yes</TopMaximize>
</snapping>
```
Whenever a move ends within `range` of `usable_area`, `view_snap_to_edge()`  for the given edge is called (or `view_maximize()` if we are dealing with the top edge and TopMaximize setting is set to true) .
A range of 0 ~~(or not setting the new config at all)~~ disables the feature.
~~Warning: only tested using a single screen.~~

Allow mouse movements to trigger SnapToEdge

---

src/seat.c

This will still prevent touchscreens or other absolute pointers to
function correctly after switching the TTY when using a multi
screen setup. But that is still better than segfaulting.

Short term solution to prevent segfaulting on TTY switch. See #206.

---

include/action.h
src/action.c
src/config/rcxml.c
src/menu/menu.c

Removes some code duplication and makes it easier to extend `struct action` by adding further arguments.

Centralize freeing of action lists

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/output.c

Add the 'cycleViewPreview.core' option to rc.xml to enable previews of
the selected view when cycling between windows. Default this option to
be disabled to match current behavior.

output: Add option to preview the contents of the current cycle_view

---

src/ssd.c

\+ change width calculation of `LAB_SSD_PART_TITLE` to use `button_width` instead of `corner_square`
I could change `int16_t` into a usual `int` if you prefer.

src/ssd.c: Clarify button dimension calculations

---

src/output.c

I am still on my quest to use an old tablet as secondary screen (and possibly as second input as well).
After getting [wayvnc](https://github.com/any1/wayvnc) to work [without virtual pointer and keyboard protocols](https://github.com/any1/wayvnc/pull/126) for now, I discovered it was really spiking the labwc CPU time.
I've seen this before, its listed in my random todo list as 'wdisplays using 200% CPU'.
So I got into debugging the screencopy implementation and found two issues:
- one is an outdated `#ifdef DEBUG` statement which is actually always defined on the top of `src/output.c` and causes full damage on each frame. Thus the screencopy protocol will always send the frame, even though nothing has actually changed
- the other is that moving the cursor in the main screen somehow gets …

src/output.c: fix debug flag for full frame damage

---

include/labwc.h
include/ssd.h
src/cursor.c
src/desktop.c
src/output.c
src/ssd.c

Part two of #222:
- Detect button enter/leave events and only damage the current output if happened
- Use proper `enum ssd_part_type` for `desktop_surface_and_view_at()`
- Move `is_button()` from `src/output.c` into `src/ssd.c` and make it public
This could be further optimized by damaging only the old/new button regions on button enter/leave.
By the way, thanks for this comment:
`/* Required for iconify/maximize/close button mouse-over deco */`
This made it really easy to figure out what was going on and - way more important - why it has been going on.

Reduce damage on cursor_move

---

meson.build

Patch releases only contain backwards compatible changes (mainly bug
fixes) so we want to allow them. This fixes the build with the recently
released wlroots 0.15.1 and uses the same version constraints as other
projects that depend on wlroots (e.g., Sway).

build: Relax the version constraint for wlroots to accept patch releases

---

src/server.c

Every new application started after the SIGHUP will get the new environment. SIGHUP will not delete anything from the environment because that would require tracking every key we set (and what the original value was before we set the new one). I am not sure it is worth doing that.

Reload environment on SIGHUP. Partly fixes #227

---

include/labwc.h
src/osd.c
src/output.c

I've tested this successfully with a single monitor, and two monitors with different scales. I'm still attempting to fix menu and titlebar text with multiple outputs, but I was hoping to get a little bit of feedback before I continue working on them.
By scaling the OSD using the greatest scale for all the outputs, we end up scaling down the OSD texture for outputs with any other scales. Downscaling a texture is significantly less noticeable than upscaling (which we currently do), but it is noticeable.
With my current patches, menu text would follow a similar design, so I wanted to know if anyone had any opinions on this before I continue working on it.

OSD: Scale OSD to the largest output scale

---

src/cursor.c
src/desktop.c

This is necessary for menus in X11 apps to work properly.
Otherwise, any region of the menu that extended out beyond the main
application window was not receiving any mouse input.
Adapted from sway's code.

Implement cursor input for unmanaged XWayland surfaces

---

src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

- `src/ssd/`: don't access `view->surface->current` directly but instead use `view->{w,h}`
- `src/ssd/ssd_titlebar.c`: only store title state if it has been changed

[scene] Two small SSD fixes

---

include/action.h
src/action.c
src/cursor.c
src/keyboard.c
src/menu/menu.c

- rename `action()` to ~~`call_actions()`~~ `actions_run()`
- fix open brace after function definition (another. yay.)
- use `__func__` in log message
- break long lines (using tabwidth 4, tabwidth 8 yields yet another 158 lines that are > 80 columns)
For some of the long line fixes I am not sure if it actually helps readability to split them.
So If you prefer to not fix the long lines for now I can drop the last patch from the PR.
`layer.c` has been ignored (3 lines > 80, nothing else).
Other than `layer.c` and the `#define FOR_EACH_END }` "macro" the checkpatch.pl output is now empty for all of the `include/` and `src/` trees.
Edit:
Removed the break-long-lines patch bc40d60e75c255374727bf35387071370db61815 from the PR.
I think it makes various things harder to understand than just …

[scene] Various checkpatch fixups

---

include/labwc.h
src/xwayland.c

Prevents a single action like ToggleDecorations + ToggleMaximize to
position the view somewhere with negative coordinates when unmaximizing.
It may still position the view on negative coordinates but later commit
events will fix the position. This issue only exists on xwayland because
there are no configure serials which we could use to ignore all
repositioning until we are at the latest desired state.

[scene] xwayland.c: Fix positioning with multiple queued configure events

---

include/ssd.h

Instead, just tag the struct so we can reference it.

[scene] include/ssd.h remove unnecessary struct definition

---

src/xwayland.c

Prevents a single action like ToggleDecorations + ToggleMaximize to
position the view somewhere with negative coordinates when unmaximizing.
It may still position the view on negative coordinates but later commit
events will fix the position. This issue only exists on xwayland because
there are no configure serials which we could use to ignore all
repositioning until we are at the latest desired state.
Same logic as #252 but backported to v0.5

xwayland.c: Fix positioning with multiple queued configure events

---

src/desktop.c

\+ Move check for unmanaged X11 surfaces down a bit so we now check for:
- overlay popups
- overlay layer
- other layer popups
- unmanaged X11 surfaces
- top layer
- usual views
- bottom layer
- background layer
Should finally fix #226 when using a wayland native dbus notification daemon.

Implement cursor input for overlay popups

---

src/debug.c
src/desktop.c

- src/desktop.c: Fix "a label can only be part of a statement and a declaration is not a statement".
- debug.c: use node descriptors

[scene] two small fixes

---

include/menu/menu.h
include/node.h
src/cursor.c
src/desktop.c
src/menu/menu.c
src/node.c

No loops or recursion within the menu hot path (motion / click) anymore :)
\+ `menu_call_actions()` and `menu_process_cursor_motion()` only have a single argument left: `wlr_scene_node *node`

[scene] Convert menu to node_descriptors

---

src/ssd/ssd_extents.c

.. so it doesn't leak into panels / neighboring outputs.
Could be further improved for tiled states or checking against output's `usable_area` values so it also adjusts sizes of individual parts of the resize extents (down to 0 if necessary).

[scene] ssd: Disable resize extents while in maximized or fullscreen state

---

include/labwc.h
protocols/meson.build
protocols/wlr-output-power-management-unstable-v1.xml
src/output.c
src/server.c

This allows using tools like `https://github.com/lilydjwg/dpms-off/` and the `output-power-management` example from wlroots. In conjunction with `swayidle`, the latter can make idle blanking work the way users generally expect.

Support wlr-output-power-management protocol

---

README.md

- made it first in the array of 'output managers' because since the
`scene_graph` merge it's the only way I have found to reliably
turn off/on outputs.
- it supports "wlr-output-power-management-unstable-v1"
- as does labwc since c23397f
- works with swayidle/swaylock

README.md: add `wlopm` to "6. Integrate" (recommended programs)

---

include/config/rcxml.h
include/ssd.h
src/main.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c
src/theme.c
src/view.c
src/xwayland.c

If I missed something please point it out / edit this post.
z-index / color changed for screenshots only:
- green: resize extents (z-index changed for debugging only)
- red: cairo drawn border on corner buttons
- blue: usual scene node borders

ssd: some small rework

---

src/menu/menu.c

- menu.c: Handle out of screen submenus. Fixes #276
- menu.c: Handle keybinding based Reconfigure while menu is shown

menu.c: Handle out of screen submenus + reconfigure while menu is shown

---

src/xwayland.c

Makes labwc aware of the size increments specified in WM_SIZE_HINTS.  Typically, X11 terminal emulators will use WM_SIZE_HINTS to make sure that the terminal is resized to a width/height even divisible by the cell (character) size.

xwayland: Honor size increments from WM_SIZE_HINTS

---

include/labwc.h
src/meson.build
src/seat.c
src/touch.c

This is mostly plumbing; the most interesting logic is in `touch_get_coords`.
This introduces a bit of duplication in `seat.c` where `new_touch` is almost a copy-paste of `new_pointer`. If someone would like this factored differently just let me know.
This doesn't implement anything fancy like pointer emulation, but by my testing makes touch work in GTK3 programs including drop-down menus.

Implement touch support

---

src/seat.c

Fixes this crash, observed when changing TTY back to labwc, running 06042337d6b746c29218268272c85a0129f9d4be:
```
Thread 1 "labwc" received signal SIGSEGV, Segmentation fault.
0x00007ffff7680e4d in __strcasecmp_l_avx () from /usr/lib/libc.so.6
#0  0x00007ffff7680e4d in __strcasecmp_l_avx () at /usr/lib/libc.so.6
#1  0x000055555557b8bc in output_by_name (server=0x7fffffffe0e0, name=0x0) at ../src/seat.c:133
output = 0x555556134440
#2  0x000055555557b9a4 in new_pointer (seat=0x7fffffffe1b0, input=0x55555682eef0) at ../src/seat.c:154
output = 0x0
dev = 0x555555fe0cd0
#3  0x000055555557bad6 in new_input_notify (listener=0x7fffffffe218, data=0x555555fe0cd0) at ../src/seat.c:183
seat = 0x7fffffffe1b0
device = 0x555555fe0cd0
input = 0x55555682eef0
caps = 2
#4  0x00005555555f5b64 in …
```

Fix crash when changing TTY

---

docs/labwc-actions.5.scd
docs/menu.xml
include/labwc.h
src/action.c
src/debug.c
src/menu/menu.c
src/server.c
src/view.c

See http://openbox.org/wiki/Help:Actions#ToggleAlwaysOnTop
If not already set to always on top, the view will reparent onto a new `server->view_tree_always_on_top` tree or onto the usual `server->view_tree` if already set to always on top.
This also means always-on-top views will show up above fullscreen'd  applications which I think is what the user would expect.
If we were to change this we'd need yet another server view_tree for fullscreen applications.
This commit shouldn't change anything regarding layershell clients like panels or notifications.

Add ToggleAlwaysOnTop action

---

include/labwc.h
src/resistance.c
src/view.c
src/xdg.c

With the wlroots scene-graph API, the padding variable is no longer
needed for windows with Client Side Decoration (CSD).

xdg-shell: remove view->padding

---

include/labwc.h
src/view.c
src/xdg.c
src/xwayland.c

Consolidates all of the view destruction code for xwl + xdg into one function.
Fixes several notable bugs along the way:
- Fixes a crash when alt tabbing when a selected view gets destroyed.
- Fixes the OSD not updating to reflect a view has been destroyed.

view: Refactor view destruction

---

include/labwc.h
src/view.c
src/xdg.c
src/xwayland.c

As a follow up to #299:
- Move XDG / XWayland specific cleanups back into their own files
- Update the OSD when the destroyed view was the currently selected one
- Handle NULL return from `desktop_cycle_view()`
- Rename `view_handle_destroy()` to `view_destroy()` (it actually frees the view)
Open questions:
- Maybe I am lost here but it seems we are cleaning up some random subset of event listeners for XDG / XWayland. Shouldn't we either clean up all of them or none of them?
- @johanmalm are you fine with having the generic `view_destroy()` in `src/view.c` or should we move it somewhere else?

view: Refactor view destruction some more

---

src/view.c
src/xdg.c

...on first map so that view->unmaximized_geometry is known even if an
xdg-shell application started in maximized mode.
Fixes issue #305
Reported-by: @01micko

xdg-shell: set view position before view_maximize()

---

CONTRIBUTING.md
NEWS.md
include/labwc.h
meson.build
meson_options.txt
po/LINGUAS
po/POTFILES.in
po/de.po
po/es.po
po/it.po
po/labwc.pot
po/meson.build
po/sv.po
src/main.c
src/menu/menu.c

- adds labwc.pot and po files for de, es, it and sv
- added notes in NEWS.md and CONTRIBUTING.md
- addresses #269
- conditional upon `msgfmt` being installed
- can be disabled at build time

nls: add native language support

---

include/labwc.h
src/xwayland-unmanaged.c
src/xwayland.c

This is needed to allow X11 applications to create surfaces as
non-override_redirect and then change them to override_redirect later
Without this gitk-menus and rofi are treated as xwayland-views with
associated server-side-decoration and forced positioning.

xwayland: handle set_override_redirect events

---

meson.build
subprojects/wlroots.wrap

Make the subproject wrap file declare the dependencies it provides.
Remove the manual subproject invocation and allow Meson to select whichever wlroots it finds which satisfies the version requirement -- either a system one via pkg-config, or the subproject fallback.
Use a dependency-generic method of acquiring wlroots configuration info -- enabled features are present in the pkg-config file and additionally exported as declare_dependency() variables, so there is no need to do C preprocessor checks for it.
This ensures that Meson best practices are followed, and also...
Fixes #318

meson: use proper dependency fallback for wlroots

---

meson.build
subprojects/wlroots.wrap

Make the subproject wrap file declare the dependencies it provides.
Remove the manual subproject invocation and allow Meson to select
whichever wlroots it finds which satisfies the version requirement --
either a system one via pkg-config, or the subproject fallback.
Use a dependency-generic method of acquiring wlroots configuration info
-- enabled features are present in the pkg-config file and additionally
exported as declare_dependency() variables, so there is no need to do C
preprocessor checks for it.
This ensures that Meson best practices are followed, and also...
Fixes #318
Backport of 2656cf525f677c59549ee42b966f542a13be19e8 (PR #321) to v0.5

v0.5-backport: meson: use proper dependency fallback for wlroots

---

meson.build

Future meson releases will change the default, so we explicitly set
check: false to maintain behaviour

v0.5 backport: build: set 'check: false' on run_command

---

src/cursor.c

- src/cursor.c: Ensure we send a release event for out-of-surface scrollng
- src/cursor.c: Ignore out-of-surface movement for surfaces without views
This is also in preparation for #342

out-of-surface fixes, the 187th edition

---

include/node.h
src/desktop.c

\+ Replace some tabs with spaces in `include/node.h`
Fixes: #278
Only tested with `gtk-layer-demo` but that turned from not-working into working so I expect `wapanel` to be fixed as well.
This PR uncovered two more issues with the previous cursor fix:
- with this PR we now have a (layer) surface without view which segfaults when doing the out-of-surface-thingie with a layer surface (as we are using the `view` geometry)
- when out-of-surface, we don't actually send the button release event to the correct surface which in case of the gtk-layer-demo causes the respective button to trigger continuously
For this reason I'll put the PR into draft mode until the two new issues are fixed.

desktop_node_and_view_at(): handle layer surfaces

---

src/common/font.c
src/menu/menu.c
src/osd.c
src/ssd/ssd_titlebar.c
src/theme.c

Various smallish fixes
When using a font size of 0, random stuff starts exploding so I tried to fix that in two commits:
- [[wip] deal with font_buffer creation failures](https://github.com/labwc/labwc/commit/be28373cda704e6f0e70365e3e7016f65a2f8f5e)
This commit deals in a general way with errors from creating a font_buffer.
- [[wip] font_buffer_create: clamp size](https://github.com/labwc/labwc/commit/16bf2f85e8e1e52d36276b88bf8f48f74cce0a23)
This commit prevents creating font_buffers with a size < 1x1 so it shouldn't actually trigger above fallback paths.
Before merging these two commits I'd welcome some second opinions.
Also: some memory leak fixes
- [src/osd.c: Free buf.buf as its malloc'd in buf_init()](https://github.com/labwc/labwc/commit/b078bc95911a77f857a3226f047e7a5345efc074)
- …

Various smallish fixes

---

include/labwc.h
src/cursor.c
src/xdg.c
src/xwayland.c

\+ Backport of applications not setting the drag icon segfaulting labwc
Should, among others, fix #347 and #340

[v0.5] Some backports related to cursor focus

---

src/menu/menu.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

`wlr_scene_buffers` need an additional `wlr_scene_buffer_set_source_box()`
to be scaled correctly by wlroots based on the output scale.
With this commit the buffers are now scaled correctly but, especially
on higher scale factors, may be a bit blurry.
In the future we likely want a dynamic font label generator based
on the maximal scale of all the outputs the specific buffer is currently on.
Some inspiration for that could be
https://github.com/Nefsen402/sway/blob/scene-graph/sway/sway_text_buffer.c
Fixes #348

Fix dynamic output based scaling for menu and SSD

---

src/menu/menu.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c
subprojects/wlroots.wrap

As it turns out the reason for the workaround was a bug
in wlroots which got [fixed](https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3588) in the meantime.
So to keep things simple just revert the workaround and
depend on the wlroots fix instead.
meson subprojects update wlroots
This reverts commit e87aa19066e5dae6ddfe1f4c5d4537474083436a.

Revert "Fix dynamic output based scaling for menu and SSD"

---

src/action.c
src/view.c

Reported-by: @Flrian (thanks!)
I basically "double fixed" it by having our internal API check if the arg is `NULL` and also by having `actions.c` check it and then not even call our internal API. So we could replace the internal API checks with asserts() instead.
I am not sure about the best design / solution here.

Prevent missing direction arguments to segfault labwc

---

docs/labwc-actions.5.scd
include/labwc.h
src/xwayland-unmanaged.c
src/xwayland.c

Welcome back an [old friend](https://github.com/labwc/labwc/commit/ba4615d7add51e51df396f0894f4d6ab8185ae26):
So, some more backports for 0.5:
- [xwayland-unmanaged: focus parent surface on unmap](https://github.com/labwc/labwc/commit/0c9d47e56f2412d1b3e0fdfc097856c5ccc491ce)
- [xwayland: handle set_override_redirect events](https://github.com/labwc/labwc/commit/ba4615d7add51e51df396f0894f4d6ab8185ae26)
- [labwc-action(5): remove incorrect \<command\>](https://github.com/labwc/labwc/commit/9bc92381828e8882c0a629e5cc4031bd895e8f4a)
- [xwayland: call foreign-toplevel-destroy on unmap](https://github.com/labwc/labwc/commit/ff7de832ae350e1ed019be4709220c64c16528e9)

[v0.5] Next batch of backports 

---

src/config/keybind.c

This restores the intended behavior of keybinds set by `<default />`
to be overwritten by manually configured keybinds which come later in
the config.
In `src/keyboard.c`, `handle_keybinding()` is going backwards through
the list of keybindings and breaks after the first match.
`wl_list_insert(&list_node, item)` will insert the new item \*after\* the
`list_node` so if its called multiple times with the same `list_node` as
fist argument the result will be a reversed list. Using `list_node.prev`
instead will result in a non-reversed list.

src/config/keybind.c: fix keybind insertion order

---

src/xwayland-unmanaged.c

...in order to render all unmanaged surfaces above views just like sway
does it:
https://github.com/swaywm/sway/blob/e5728052b59fb5b476c78c9f18b812a85d7f4503/sway/desktop/render.c#L1148
Fixes issue #367

xwayland-unmanaged: put all surfaces under server->unmanaged_tree

---

src/xwayland-unmanaged.c

Fixes a segfault with starting Steam.

xwayland-unmanaged: Fix set_geometry using container_of of wrong member

---

include/common/scene-helpers.h
include/layers.h
include/menu/menu.h
include/ssd.h
src/common/scene-helpers.c
src/debug.c
src/desktop.c
src/layers.c
src/menu/menu.c
src/osd.c
src/output.c
src/server.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c
src/touch.c
src/view.c
src/xdg-popup.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c
subprojects/wlroots.wrap

These are likely the biggest changes regarding the scene-graph API we had to adjust to since moving to the scene-graph API in the first place.
I split everything into their own commits, each following a upstream commit so we are able to diagnose things better if something goes wrong. I had a quick test on each step along the way but when seeing the amount of changes required I think it makes sense for others to test and/or have a look at the single commits before merging this.
As always: use `meson subprojects update wlroots` to check out the corresponding wlroots upstream commit before building.
See https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3509/commits for the upstream commits.
I will push commit by commit into this branch so the CI triggers for all of them.

Chase wlroots: upstream scene_node refactoring

---

src/view.c

The layer-shell top-layer is disabled when running an application in
fullscreen mode, so if this is the case on view_destroy() we have to
re-enabled the top-layer again.
Reported-by: @heroin-moose
Fixes #377

view: if view->fullscreen on destroy, re-enable top-layer

---

src/osd.c

We should do our drawing in the "abstract" coordinate space (relative to unscaled w/h), but use output-scaled coordinates when allocating the buffer (`buffer_create_cairo` forwards its width/height directly to `wlr_buffer_init` without adjusting by `scale`). We also call `wlr_scene_buffer_set_dest_size` to inform wlroots that the buffer is scaled.

correctly scale window switcher

---

include/labwc.h
protocols/meson.build
protocols/wlr-output-power-management-unstable-v1.xml
src/output.c
src/server.c

Since someone on IRC noticed wlopm wasn't working for 0.5.2 I tried to add the relevant commits to it:
https://github.com/labwc/labwc/commit/5fd5024ca655d07d04cfb3e9c829c1764dd8ee01
https://github.com/labwc/labwc/commit/748b3d38e7ff8aee926f6ea4679b15a9265ea10d
https://github.com/labwc/labwc/commit/c23397f362930e97e616a75590c4111558891381

[v0.5] Backport - add support for wlr-output-power-management

---

include/buffer.h
include/common/font.h
include/common/scaled_font_buffer.h
include/common/scaled_scene_buffer.h
include/menu/menu.h
include/ssd.h
src/buffer.c
src/common/font.c
src/common/meson.build
src/common/scaled_font_buffer.c
src/common/scaled_scene_buffer.c
src/menu/menu.c
src/osd.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

This adds an auto scaling font buffer to labwc and converts menu and ssd_titlebar to use it.
I tried to put everything into small and digestible commits.
First three commits could likely be split out of this PR.
I am mostly satisfied with the auto scale buffer state for now, I'd just need to remove the debug logs.
Something that might be interesting for the future is to generalize this some more and instead of having an scale adapting font buffer we'd have an abstract scale adapting 'thing' that gets a config struct when initialized containing callbacks that will get called whenever a new buffer needs to be rendered. The 'thing'  would then only be responsible for setting the appropriate scaled buffer on output_enter/leave events and request new buffers if the node had been moved to an …

Add autoscaling font buffer

---

README.md
src/action.c

Also update documentation to say `killall -s SIGHUP labwc` to make
it work on Void Linux.
Fix #393

action.c: use kill() instead of spawning killall

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/menu.xml
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
include/workspaces.h
src/action.c
src/config/rcxml.c
src/desktop.c
src/foreign.c
src/keyboard.c
src/menu/menu.c
src/meson.build
src/osd.c
src/server.c
src/view.c
src/workspaces.c
src/xdg.c
src/xwayland.c

This ~~is just a simple test implementation for workspaces~~ implements workspaces.
I'd welcome some more testing and review.
2 new actions:
- `SendToDesktop` `target` (move current view to workspace `target`, also available via window menu)
- `GoToDesktop` `target` (change active workspace to `target`)
Workspaces have to be defined in `rc.xml`. Example:
```xml
<desktops>
<popupTime>1000</popupTime>
<names>
<name>Workspace a</name>
<name>Workspace b</name>
<name>Workspace c</name>
</names>
</desktops>
```
Actions have to use `to` for their `target` argument, a `target` can be defined as:
- `left` / `right`
- the workspace index, beginning from 1
- the full name of the workspace
Example:
```xml
<keybind key="W-Left">
<action name="GoToDesktop" to="left" />
</keybind>
<keybind …
```

Add workspaces

---

include/labwc.h
src/output.c
src/server.c

Apps such as Gamescope eventually want to offer a DRM lease option to use planes and handle all of getting to the screen themselves.
This implements logic to allow leasing of desktop displays

Allow leasing desktop displays

---

docs/labwc-actions.5.scd
include/labwc.h
src/workspaces.c

Actions GoToDesktop and SendToDesktop now support the new direction
called "last" that corresponds to the last used workspace (see Openbox
help[1] for reference).
[1]: http://openbox.org/wiki/Help:Actions#GoToDesktop

workspaces: Allow switching/sending to the last used workspace

---

src/osd.c

Making sure long window titles don't overflow the selection box
Closes issue #406
Written-by: @johanmalm

src/osd.c: fix max text width

---

src/seat.c
subprojects/wlroots.wrap

meson subprojects update wlroots
Chases wlroots 91943a68a6976ef7c4cc70afc07954a00fae678b
wlr_input_device: remove anon union field
- Fixes #415

Chase wlroots: wlr_input_device refactor

---

include/ssd.h
src/server.c
src/ssd/ssd.c
src/xdg.c
src/xwayland.c

- Fixes #409
I'd welcome some testing to make sure this doesn't break anything else like center positioning or starting maximized.
While testing this I discovered Wayland native applications starting in fullscreen mode like `foot -F` actually keep their SSD for unknown reasons, that appears to be the case even without this PR though so its unrelated.

src/ssd/ssd.c: Keep view->margin in sync when toggling decorations

---

include/labwc.h
src/interactive.c
src/layers.c
src/view.c

This looks worse than it actually is, most of the changes are just moving the existing functions up.
What actually changed:
- `struct view` got a `uint32_t tiled` member (private use in `view.c`, using internal `enum view_edge`)
- `view_snap_to_edge()` got split into two parts, the original public one mainly doing the output change logic and modifying `view->tiled`, the other internal one (`view_apply_tiled_geometry(view, output)`) just getting and applying the layout
- `view_adjust_for_layout_change()` now additionally calls `view_apply_tiled_geometry(view, NULL)`
- `view_snap_to_edge()` was modified to use `wlr_output_layout_adjacent_output()` for its output changing logic instead of working based on coordinates
- when moving or resizing a tiled window, `view->tiled` is reset, so future …

Convert SnapToEdge to use view_apply_xxx_geometry framework

---

include/labwc.h
src/interactive.c
src/view.c

Follow-up and depends on
- #426
Replaces
- #401
Contains all commits from #426, will rebase once that one is merged.

Restore original geometry when moving a tiled window

---

include/labwc.h
src/xwayland-unmanaged.c
src/xwayland.c

- Add missing call to wlr_scene_node_set_position() in
unmanaged_handle_commit() -- this fixes moving unmanaged XWayland
windows.
- Update view->pending_move_resize when we receive a configure request
for a managed XWayland surface -- this fixes moving managed but
undecorated XWayland windows.
- Also update view->pending_move_resize when we move a surface while a
configure request is already pending -- this fixes a discrepancy
between displayed and actual position for XWayland windows that try to
set their own initial position, but then get overridden by labwc's
positioning.
Moving undecorated XWayland windows is still really glitchy -- it appears
that an XWayland window gets sent incorrect mouse motion coordinates when
there is a pending configure request moving the window itself.
Fixes …

(Partly) fix handling of client-initiated configure requests

---

src/output.c

Without this fix we will never react to output configuration changes
via wlr-randr and friends.
If `output_config_apply()` commits the new config, `handle_output_layout_change()`
is called but doesn't do anything because the config is still pending.
This patch moves the code into its own function `do_output_layout_change()`
which additionally gets called after all output configs are committed.
The original handler is turned into a wrapper around `do_output_layout_change()`.
Reported-by @heroin-moose

src/output.c: Always react to new output configuration

---

README.md

- Use &nsbp; in links with spaces
- Change headings from verbs to nouns
- Combine build and install headings
- In 'What is this', use the text on the labwc website
- Remove video links; one wasn't working and the other were very old
- Use more recent screenshot
- Simplify the 'labwc supports the following' bullet points
- Split dependencies into build and run-time
- Remove dependecy version numbers and let meson.build be the source of
truth
- Simplify config file table by taking out middle column
- Split the configuration section into configuration and theming
- s/roadmap/scope
- Change man page links from docs/ to labwc.github.io/

README.md: refresh and refactor

---

src/common/buf.c

Allow underscore in environment variable names.
Closes issue #439
...who both found the bug and told us how to fix it :)

buf.c: fix bug in environment variable expansion

---

include/common/fd_util.h
src/common/fd_util.c
src/common/meson.build
src/common/spawn.c
src/main.c

This defaults to 1024, which is tiny, but is a requirement
for processes using the deprecated `select` function.
We must reset this back whenever we fork to start a new process,
as this is inherited, and breaks applications using `select` otherwise.

main: Increase FD limit

---

include/labwc.h
src/server.c

For some reason wlroots will reset the seat assigned to xwayland
to `NULL` whenever Xwayland terminates. This patch restores the seat
whenever Xwayland is ready again.
Fixes
- #166
- #444
Thanks @droc12345 for figuring out the actual issue.
Testing welcome.

xwayland: (Re)set seat when xwayland is ready

---

include/labwc.h
src/xwayland-unmanaged.c

This is a similar fix to 065c37d3f5ee but for unmanaged windows.  The issue
could be seen for example when moving the undocked Search Tool window in
Audacious.  For unmanaged windows, we don't track any pending move/resizes,
so just process all client configure requests immediately.
Video of the issue:
https://user-images.githubusercontent.com/1244737/180612621-461f4503-faa3-4a00-ab4b-411929985478.mp4

xwayland: Process unmanaged client configure requests more quickly

---

docs/environment
docs/labwc.desktop
src/config/session.c

This allows xdg-desktop-portal-wlr to work out of the box for screen-recording.
If systemd or dbus is not available the environment update will fail gracefully.
This patch will set `XDG_CURRENT_DESKTOP=wlroots` but a user may change this by
either having the environment variable set before starting labwc or by having
a different value set in `~/.config/labwc/environment`.
Based on PR #461 by @Joshua-Ashton

src/config/session.c: Update dbus / systemd activation environment

---

src/action.c

Fixes #410
Backport of c49f4e735d98fbb942db2acc834a9173e2e6bdca

src/action.c: Fix includes for kill() and getpid()

---

docs/labwc-menu.5.scd
docs/menu.xml
src/menu/menu.c

Allow highest level menu definitions - typically used for root-menu and
client-menu - to be defined like this:
<openbox_menu>
<menu id="">
</menu>
</openbox>
Previously this required a label attribute (which was not used for
anything and could be an empty string) as show below:
<openbox_menu>
<menu id="" label="">
</menu>
</openbox>
Closes issue #472

menu: do not require label attribute for highest level menu definition

---

src/ssd/ssd_titlebar.c

Before this commit the window title could overflow in certain conditions,
usually when rapidly resizing. This commit fixes it by completely hiding
the corresponding scene node when there is no space available.
Reported-by: `<peperino>` via IRC

src/ssd/ssd_titlebar.c: Completely hide title when running out of space

---

README.md
docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

...because too many have exited the compositor by mistake trying to get
out of alt-tab cycling or similar.

keybind: remove default alt-escape for Exit

---

src/output.c

function output_destroy_notify lack free operation

func output_destroy_notify add free

---

include/labwc.h
src/view.c
src/xdg.c
src/xwayland.c

@Consolatis @jlindgren90 Can you think of any reasons why we should stick with `double`? Everything else related seems to be int. Even `struct wlr_xwayland_surface_configure_event` uses `int16_t` for x and y.

view: view_move() s/double/int/ for x and y

---

include/labwc.h
src/osd.c

src/osd.c: Add preview outlines

---

src/keyboard.c
src/osd.c

Two separate fixes for the Alt-Tab (window switcher) OSD, short and sweet. Hopefully I didn't miss anything.
- Fix extra Alt-Tab OSD being shown if there is a disabled output (e.g. laptop display when docked)
- Fix Alt-Tab OSD remaining displayed after pressing Alt-Tab then Escape

osd+keyboard: Two small Alt-Tab fixes

---

src/common/font.c
src/theme.c

Missed these two when adding `common/graphic-helpers.c`.
The change in `common/font.c` is disputable as it adds another function call. Will revert if desired.

src/{common/font,theme}.c: Switch to cairo helpers

---

include/labwc.h
include/ssd.h
src/desktop.c
src/ssd/ssd.c
src/view.c

`view_set_activated()` takes a Boolean parameter `activated`.
`ssd_set_active()` needs a Boolean parameter as well, otherwise `view_set_activated(false)` results in calling `_ssd_set_active(true)`.
Partially fixes #494.

view/ssd: Handle view_set_activated(false) case correctly

---

src/osd.c

This makes the border visible when alt-tabbing maximized windows and
prevents it from rendering on other outputs or on top of exclusive
layer-surfaces such as panels.
Closes issue #496

osd: position preview border within SSD max extents

---

subprojects/wlroots.wrap

meson subprojects update wlroots
Chases wlroots fa7d2cb8d60ed48c44c707106c03682056ddfaca
wlr_scene: Only consider visible parts of the node when culling background
Fixes #501

Chase wlroots: Culling

---

include/common/scene-helpers.h
include/labwc.h
src/action.c
src/common/scene-helpers.c
src/desktop.c
src/keyboard.c
src/osd.c
src/view.c

~~I am still not 100% satisfied with the implementation.~~
First commit basically just replaces `server->cycle_view` with `server->osd_state.cycle_view` so can be skipped for review.
What I don't really like:
- `view_destroy()` starts to look like a OSD clean up routine, maybe we should have an additional `osd_view_destroyed()` handler or something like that that we can call from `view_destroy()` (similar to `ssd_destroy()`)?
What is missing: 
All in all this is one of the very few things that actually got harder by the move to the scene-graph API.

Feature/tab preview: restore functionality after the move to scene-graph

---

docs/labwc-config.5.scd
src/config/mousebind.c
src/config/rcxml.c
src/cursor.c

This loads default mousebinds and provides a way to keep config files
simpler whilst allowing user specific binds.
Note that if no rc.xml is found, or if no <mouse><mousebind> entries
exist, the same default mousebinds will be loaded even if the <devault />
element is not provided.
Example usage (with a slight spelling error):
```xml
<mouse>
<default />
<context name="Root">
<mousebind button="Right" action="Press">
<action name="ShowMenu" menu="desktop-menu" />
</mousebind>
</context>
</mouse>
```
Co-Authored-By: @johanmalm

src/config/rcxml.c: Add support for <devault /> mousebinds

---

src/xwayland-unmanaged.c

Previously, when unmapping and not finding another unmanaged surface
to give keyboard focus to we were not doing anything. With this patch
we will give focus to the topmost mapped view which is the same
behavior that also happens when an usual X11 surface unmaps.
This fixes dmenu when being exited with ESC.
Reported-by: @Flrian

src/xwayland-unmanaged.c: Give keyboard focus back to topmost mapped view

---

src/xdg.c
src/xwayland.c

Currently all XWayland views are centered, regardless of whether the application requested a specific window position. This breaks applications that save and restore their own window positions, and is particularly bad for usability when the application displays multiple windows (e.g. Audacious in Winamp mode), since they all get stacked on top of each other.
Two changes here:
- Honor the ICCCM window position hints
- Fix a bug where `wlr_scene_node_set_position()` might never be called
v2: Use `view_adjust_for_layout_change()` to make sure the window is still on-screen.

Honor XWayland client window positions

---

src/config/rcxml.c

Some trackpads do not honour tap if we only enable it on touch-devices.

rcxml.c: enable tap be default on non-touch devices

---

docs/labwc-config.5.scd
docs/rc.xml.all
src/config/rcxml.c

...to comply with [Openbox 3.6 spec](http://openbox.org/wiki/Help:Configuration#Theme)
"OSD" is still honoured to maintain backward compatibility

config: s/OSD/OnScreenDisplay/ in <theme><font place="OSD">

---

include/labwc.h
src/action.c
src/cursor.c

@Consolatis noticed in https://github.com/labwc/labwc/pull/544#discussion_r971306613 that `Resize` does not work when triggered from a keybind.  This fixes the issue by making `cursor_get_resize_edges()` public and calling from the keybind path also.
An alternative would be always to use a fixed value of `resize_edges` (e.g. `BOTTOM | RIGHT`) for the keybind case, rather than querying the cursor.
There is a very minor merge conflict with #545, due to renaming `determine_resize_edges()`.

action: Select resize edges for Resize triggered by keybind

---

src/keyboard.c
src/seat.c

Fix a couple different use-after-free bugs due to unregistering a `wl_listener` after the event sender is already destroyed.
Off-topic: `QObject::connect()` solved this whole class of bugs a long time ago, by breaking the event connection as soon as either the event sender or recipient is destroyed.  Unfortunately a universal fix of that kind would probably require converting both `wlroots` and `labwc` to C++.

Fix uses-after-free on exit

---

src/keyboard.c

Stack trace:
#0  xkb_keymap_ref (keymap=keymap@entry=0x0) at ../libxkbcommon/src/keymap.c:61
#1  0x00007f53a344ab99 in wlr_keyboard_set_keymap (kb=kb@entry=0x5571af8cb9a0, keymap=keymap@entry=0x0)
at ../types/wlr_keyboard.c:174
#2  0x00005571ade057e0 in keyboard_init (seat=0x7ffca0389680) at ../src/keyboard.c:229
#3  seat_init (server=0x7ffca0389570) at ../src/seat.c:307
#4  server_init (server=0x7ffca0389570) at ../src/server.c:308
This is one of the more common `SIGSEGV` that still shows up after #552.  There are many others out of our control (especially in `libfontconfig` and `radeonsi_dri`) but let's fix what we can.

keyboard: Fix SIGSEGV that showed up in out-of-memory fuzzing

---

include/labwc.h
src/output.c

This fixes an issue with the `wlr_output_cursor` not being properly initialized on new outputs, because `wlr_output_layout.events.change` is triggered too soon, before the `wlr_output_cursor` exists.
May possibly help with #561.

output: Call do_output_layout_change() at end of new_output_notify()

---

include/common/scaled_scene_buffer.h
include/workspaces.h
src/common/fd_util.c
src/common/graphic-helpers.c
src/common/scaled_scene_buffer.c
src/config/rcxml.c
src/debug.c
src/desktop.c
src/interactive.c
src/osd.c
src/output.c
src/server.c
src/view.c
src/workspaces.c

...based on https://github.com/johanmalm/checkpatch.pl
```
src/server.c:161: ERROR: space required before the open parenthesis '('
src/server.c:473: CHECK: Blank lines aren't necessary after an open brace '{'
src/desktop.c:228: WARNING: function definition argument 'struct wl_list *' should also have an identifier name
src/output.c:289: CHECK: Blank lines aren't necessary before a close brace '}'
src/interactive.c:20: WARNING: suspect code indent for conditional statements (8, 17)
src/interactive.c:27: WARNING: Statements should start on a tabstop
src/config/rcxml.c:607: CHECK: Blank lines aren't necessary after an open brace '{'
src/config/rcxml.c:638: CHECK: line length of 91 exceeds 90 columns
src/config/rcxml.c:639: CHECK: Blank lines aren't necessary after an open brace '{' …
```

Fix minor coding-style violations

---

src/desktop.c
src/osd.c

This might happen when closing the last
application "to tray" like VLC, Discord or Steam.
Reported-by: @Flrian
@jlindgren90 testing for regressions of the original use-case of detached search window appreciated.

src/osd.c: Prevent showing invalid window

---

src/xwayland-unmanaged.c

Since xwayland commit 9e4b7948df5a9a67632bb606150ec171b5519672 there is a one-second delay between XWayland surfaces being unmapped and destroyed.  This revealed that we were not actually handling the unmap() signal correctly for unmanaged surfaces.
Fixes: #597
Thanks @Consolatis for the suggestion.

xwayland: Hide unmanaged nodes on unmap()

---

include/labwc.h
src/key-state.c
src/keyboard.c
src/seat.c

It seems that every Wayland client is expected to implement its own
key-repeat logic, rather than doing it server-side as in X11.  This
means that labwc also has to implement its own key-repeat logic for
compositor keybindings.
This is a very simplistic timer-based implementation.  It doesn't
attempt to synthesize accurate timestamps, and may lag depending
on system load, but it appears to get the job done.
I also fixed a potential array overflow in key-state.c (separate commit).
Fixes: #462

keyboard: Implement key repeat for keybindings

---

subprojects/wlroots.wrap

This fixes an assert on output test when
running with the headless backend.
meson subprojects update wlroots
Chases wlroots 05454618cd2d49fb3a5f0c560b0d2c455cf32467
xwayland: split headers
Fixes #605

Chase wlroots: output test assert

---

src/keyboard.c

This makes the rate of labwc keybind repeats match that of regular key repeats.

Use 1000/rate msecs for keybind repeat event source delay

---

src/config/rcxml.c

Currently, the `rc.xml` parser applies font settings in a `<font>` tag with an unknown value for its `place` attribute to all fonts. This means that whatever the final unknown-`place` `<font>` tag is in a user's `rc.xml` applies to all text drawn by labwc.
Instead, only treat `<font>` tags with an empty or missing `place` attribute as applying globally, and warn when encountering unknown `place` attribute values (which will help us find font places to support).

Distinguish no and unknown font places

---

src/view.c

view: survive setting fullscreen with no outputs

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/mousebind.h
include/labwc.h
src/config/mousebind.c
src/config/rcxml.c
src/cursor.c

Note that this changes `Scroll` mousebinds from taking a "button" attribute to taking a "direction" attribute. ~Also note that while this enables trackpads to activate scroll bindings, they are currently hyper-sensitive; we should probably compare the accumulated scroll offset against some (libinput-based?) measurement.~
I've now implemented thresholding that makes smooth scrolling emit events at a reasonable speed.

Support smooth scroll and horizontal scroll

---

src/seat.c

Without this patch, reconfiguring keyboard repeat rate/delay at runtime does not work. However, I've left this as a draft because I don't understand the role of the `keyboard_group` here. Is `seat->keyboard_group->keyboard` guaranteed to be present in the `seat->inputs` list, or should it be handled separately (as commented-out)?

Correctly update kbd repeat rate by filtering input devices

---

meson.build

Meson adds `-Wl,--as-needed` (unless `-Db_asneeded=false`) by default. For example, packaging log diff:
```diff
=>> Checking shared library dependencies
0x0000000000000001 NEEDED               Shared library: [libc.so.7]
0x0000000000000001 NEEDED               Shared library: [libcairo.so.2]
0x0000000000000001 NEEDED               Shared library: [libglib-2.0.so.0]
0x0000000000000001 NEEDED               Shared library: [libgobject-2.0.so.0]
0x0000000000000001 NEEDED               Shared library: [libinput.so.10]
+ 0x0000000000000001 NEEDED               Shared library: [libintl.so.8]
0x0000000000000001 NEEDED               Shared library: [libm.so.5]
0x0000000000000001 NEEDED               Shared library: [libpango-1.0.so.0]
0x0000000000000001 NEEDED               Shared library: …
```

build: drop pixman dependency after wlr_scene switch

---

src/config/rcxml.c

Previously mosuebinds for the same context using the same button but different modifiers would be merged, e.g. only the last one would survive the merge. This commit adds the missing check for keyboard modifiers.
Fixes #630
Reported-by: @lidgnulinux

src/config/rcxml.c: Check for modifiers when merging mousebinds

---

src/ssd/ssd.c
src/view.c
src/xdg.c
src/xwayland.c

`map()` in `xwayland.c` called `ssd_create()` but did not call `view_apply_maximized_geometry()` afterward, resulting in the decorations being displayed off-screen.
Rather than calling `view_apply_maximized_geometry()` in more places, let's reuse the existing call in `view_set_decorations()`, and extend `ssd_update_geometry()` to call `ssd_create()` when needed.
I also included a second commit which simply deduplicates some code, by having `view_toggle_decorations()` call `view_set_decorations()`.

Fix positioning of initially-maximized XWayland views

---

include/labwc.h
src/action.c
src/cursor.c
src/foreign.c
src/interactive.c
src/view.c
src/xdg.c

There are a couple of sketchy things going on here:
- interactive_begin() pokes its own values into view->natural_geometry to force view_maximize() to set a particular geometry.
- interactive_end() "fixes" view->natural_geometry after calling view_maximize() to save the original geometry from the start of the interactive move/resize.
Let's adjust/expand the API of view.c so that the interactive.c can avoid this "back door" of overwriting view->natural_geometry directly.
This also addresses an issue where the natural_geometry was not saved correctly when dragging and snapping a window to a screen edge.
Fixes: #633

interactive: Clean up natural_geometry hacks

---

src/ssd/ssd_titlebar.c

Inactive window button pixmaps weren't being added to the SSD scene graphs. I added them to ssd_title_create() and tried to match the selection logic for how the corner buttons were being added.

ssd: Make inactive window buttons follow theme color

---

include/ssd.h
include/view.h
include/workspaces.h
src/action.c
src/interactive.c
src/resistance.c
src/server.c
src/ssd/ssd.c
src/view.c
src/workspaces.c
src/xdg.c
src/xwayland.c

I'm trying to make the code a bit easier to understand through better organization. We already have some "modules" of a sort: a "view" module, an "ssd" module, etc. This change simply makes the code follow some rules such as:
- `struct ssd` is only modified by the "ssd" module (ssd.c and related files)
- `struct view` is only modified by the "view" module (view.c and related files)
The changes in detail are:
- Move `ssd::enabled` to `view::ssd_enabled` since it's written by view.c, not ssd.c
- Move `view::margin` to `ssd::margin` since it's written by ssd.c, not view.c
- Add `view_set_untiled()` rather than writing to `view::tiled` outside view.c
- Rename and move `workspaces_send_to()` to `view_move_to_workspace()` since it modifies `struct view`
Elsewhere, I have been experimenting with …

view/ssd: Minor refactoring to make code more modular

---

include/view.h
src/xdg.c
src/xwayland.c

...for XDG toplevels and XWayland views to only include applicable wl_listeners for each type of view.

view: create derived structs

---

include/view.h
src/cursor.c
src/desktop.c
src/osd.c
src/view.c
src/xdg.c
src/xwayland.c

Following up on a suggestion in #641.
- Add `view_get_xdg_surface()` + `view_get_xwayland_surface()` accessors that `assert()` the view is of the expected type before returning.
- Fix a real bug in `xdg.c` `parent_of()` that dereferenced `view->xdg_surface->toplevel` without first checking `view->type`.
The goal of the new accessors is to catch similar bugs in future.

view: Move xdg_surface + xwayland_surface to derived structs

---

include/ssd.h
include/view.h
src/server.c
src/ssd/ssd.c
src/view.c

Fixes the pre-existing issue that @johanmalm noticed in #640, where decorations are shown around fullscreen views and can be visible on other outputs.
- Update `view_set_decorations()` and `view_set_fullscreen()` to disable decorations for fullscreen views
- Remove enable/disable logic from `ssd_update_geometry()` since it is now handled by `view_set_decorations()` and `view_set_fullscreen()`
Some minor fixes/cleanups as well:
- Use C99-style struct literals in `return` statements to eliminate unnecessary temporary variables
- Add an `active` argument to `ssd_create()` for consistency with `ssd_set_active()`
- Update `view->ssd.state` at the end of `ssd_create()` so that the next call to `ssd_update_geometry()` doesn't do unnecessary work
- Move `ssd_reload()` to `view_reload_ssd()` since …

view: Hide decorations for fullscreen views

---

include/ssd.h
src/action.c
src/debug.c
src/desktop.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_titlebar.c
src/view.c
src/workspaces.c

Split off from #640.
- Minimize includes in `ssd.h`
- Avoid repetitive `view->ssd.margin` pattern
- Use `struct ssd *` or `const struct ssd *` rather than `struct view *`
where convenient
- Add `ssd_debug` helpers
Part of the motivation is to make it easier to separate `struct ssd`
from `struct view` in a future commit (i.e. the rest of #640).

ssd: Cosmetic cleanups & add debug helpers

---

src/view.c

If `view->ssd_enabled` is false when calling `ssd_create()` then `ssd_thickness()` returns zeroes which are stored in `ssd->margins`.
The quick fix is just to ensure we set `view->ssd_enabled` before calling `ssd_create()`. At some point, it might be nice to refactor so that `ssd_create()` does not reference `view->ssd_enabled`.
Fixes #653 which was a regression caused by #650 (oops).

view: Fix SSD margin computation

---

include/labwc.h
include/ssd.h
include/view.h
src/action.c
src/cursor.c
src/debug.c
src/desktop.c
src/resistance.c
src/server.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_titlebar.c
src/view.c
src/xdg.c

Allocating these structs separately allows them to be made opaque in a later commit.
- Store a pointer to the `struct view` in `struct ssd`
- Pass `struct ssd *` instead of `struct view *` to ssd functions
- Add `ssd_get_margin()` convenience function
Split off from #640.

ssd: Allocate `struct ssd` and `struct ssd_hover_state` separately

---

include/ssd-internal.h
include/ssd.h
src/desktop.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

The basic idea is as the title says, to hide as much of the SSD logic so that it's only visible to the source files starting in `ssd_`.
Changes in detail:
- Add new ssd-internal.h header
- Move all ssd structs and internal functions to ssd-internal.h
- Allocate `struct ssd` and `struct ssd_hover_state` separately
- Add a few accessors to replace direct access into ssd structs
- Store a pointer to the `struct view` in `struct ssd`
- Pass `struct ssd *` instead of `struct view *` to ssd functions
- Add `view_reload_ssd()`, replacing `ssd_reload()` and surrounding logic
- Move some parts of debug functions to ssd.c
The fact that we now have both `ssd_new()` and `ssd_create()` isn't ideal (though the functions do have different purposes). Perhaps at some point we can revisit those and clarify …

ssd: Hide implementation details from the outside world

---

docs/labwc-theme.5.scd
include/common/scaled_font_buffer.h
include/menu/menu.h
include/theme.h
src/common/scaled_font_buffer.c
src/main.c
src/menu/menu.c
src/theme.c

This PR introduces four new theme variables:
- `menu.items.padding.x`
- `menu.items.padding.y`
- `menu.width.min` (menus will never be smaller than this)
- `menu.width.max` (menus will never be wider than this + padding)
Missing:
~~The way I wired this up is not optimal: When creating a new menu item the width will be compared to the stored width of the whole menu and if the new item width is wider, all existing items will be resized and the new width will be set for the menu.
This means that we may end up unnecessarily resizing items multiple times. However, this only happens while parsing `menu.xml` so it shouldn't be an issue in practice. Feels a bit hackish though.~~

menu: Dynamically adjust menu width

---

README.md

...because running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.

README.md: update build instructions

---

docs/labwc-actions.5.scd
src/action.c

This action forcibly disconnects clients, rather than requesting them to close. It's useful for when a client is misbehaving or frozen, but I'm not sure that it's necessarily the Right Thing. Specifically, it doesn't kill the process itself, which may be hung or unresponsive to a Wayland disconnection. Or, if the client supports "wayland robustness" (cf. David Edmundson), it might simply reconnect, which might not be the user's intention.
So, perhaps this action should instead be called "Disconnect". Perhaps I should instead (or additionally) implement a proper `Kill` action using `wl_client_get_credentials` to obtain the client pid. The [docs](https://wayland.freedesktop.org/docs/html/apc.html#Server-structwl__client_1a82a97cb3a66c1c56826a09a7b42453d9) for that function warn of potential …

[RFC] Implement Kill action

---

include/action.h
src/action.c
src/config/rcxml.c
src/menu/menu.c

This fixes being unable to use the `direction` argument in menu entries.
Reported-by: mahk via IRC

menu: Reuse action argument parsing from rcxml.c

---

src/view.c

Before this on my setup with a single monitor the following would happen:
1. Snap to Edge
2. Maximize
3. Snapping to the original edge would not work

src/view.c: dont switch output on SnapToEdge if view is maximized

---

src/osd.c

Fixes the OSD portion of #647.

Call `cursor_update_focus` when showing/hiding OSD

---

src/view.c

Found downstream when building everything with X11 disabled (not just labwc). See also [error log](https://github.com/labwc/labwc/files/10258590/labwc-0.6.0.log).

Unbreak build without Xwayland (in wlroots)

---

include/view.h
src/view.c
src/xdg.c

A cleaner fix for the second half of #647. Supersedes #676.

Avoid setting `view->w` and `view->h` before xdg view commit

---

docs/labwc-config.5.scd

docs: Fix small typo in labwc-config(5) manpage

---

include/config/libinput.h
src/config/libinput.c
src/config/rcxml.c
src/seat.c

Previously, if `rc.xml` defined only non-default libinput categories, no default category was created. This meant that `configure_libinput()` might totally skip configuring some devices even with default settings, like tap-to-click.
Fix this by making sure that a default category is always created.

rcxml: Make sure a default libinput category always exists

---

include/view.h
src/view.c
src/workspaces.c

Situation: Switching workspaces while having the keyboard focus on an always-on-top window
Options:
1. re-focus to the topmost window on the new workspace
2. re-focus to the topmost always-on-top window
3. if the focus is on an always-on-top window do not change focus at all, otherwise re-focus to the topmost window
`1.` is the current state which is kind of annoying because you'll loose the keyboard focus.
`2.` doesn't sound right either, imagine having some kind of chat or log-output set to always-on-top and giving it focus whenever switching workspaces
`3.` is the best UX option in my opinion thus what I implemented in this PR.

src/workspaces.c: prevent re-focus for always-on-top views

---

include/labwc.h
include/layers.h
src/desktop.c
src/layers.c
src/output.c

Related to issue #667
This will supersede PR #685 
TODO
Later
- Use ARRAY_SIZE macro

Use scene-node approach for layers and simplify usage of wlr_scene_node_at()

---

src/view.c

Reported-by: @Flrian via IRC
Debugged-by: @Flrian
Tested-by: @Flrian
Without this you can't snap a window to an edge, move it away and while still holding the mouse button snap it back to the same edge.

src/view.c: Allow snapping to the same edge

---

src/view.c

Before this patch following would cause the SSD to be rendered offscreen:
- snap a window to left or right edge
- toggle fullscreen to fullscreen
- toggle fullscreen to un-fullscreen
To fix that restore the SSD before calculating the new geometry.

src/view.c: on un-fullscreen restore SSD before applying previous geometry

---

src/view.c

So its visible by all the other view_apply_xxx_geometry() functions.
Just another minor refactoring, split from #433.

src/view.c: move up view_apply_natural_geometry()

---

src/layers.c
src/output.c
src/view.c

There might be more issues, most of this has been tested by running nested:
- `sleep 5; foot`
- `sleep 5; foot -F`
- `sleep 5; wtype -M logo f` (which is bound to `ToggleFullscreen` in my nested instance)
- `sleep 5; wl_framework/run_example wl_framework/examples/wl_example_panel.py`
and then closing the nested labwc window.

Fix various crashes related to no outputs available

---

include/labwc.h
src/layers.c
src/output.c
src/server.c

Move the desktop_arrange_all_views() call outside layers_arrange() into a new function, output_update_usable_area().  The new function currently does exactly what layers_arrange() used to, but will be expanded in a later commit.
Add output_update_all_usable_areas(), which is the same as calling output_update_usable_area() for each output, but only calls desktop_arrange_all_views() once.
Rebased and slightly modified by @Consolatis
---
Split off from #625 and addressed the review commits.
Further change:
- call `cursor_update_focus()` on layer surface commits which change something other than just the buffer content itself to keep the `pointer.enter` event working for new layer surfaces spawning under the cursor (and when moving / resizing layer surfaces).

output: Add output_update_usable_area/all_usable_areas()

---

include/labwc.h
src/view.c
src/xwayland.c

Also remove the `<xcb/xcb_icccm.h>` include as its already included by
`"labwc.h"` -> `<wlr/xwayland.h>` -> `<wlr/xwayland/xwayland.h>`.
Addresses https://github.com/labwc/labwc/pull/682#issuecomment-1357614626

src/view.c: move xwayland specific function to xwayland.c

---

include/labwc.h
src/ssd/ssd_part.c
src/view.c
src/xwayland.c

As discussed in https://github.com/labwc/labwc/pull/712#discussion_r1061114212
We could also move the macros from `labwc.h` to some other header, I don't particularly mind either variant.

include/labwc.h: Provide MIN/MAX macros

---

include/labwc.h
src/output.c
src/server.c

This restores the original approach of naming the argument `layout_changed` which fits much better than `enforce_view_arrange`. Especially when extending the function to also handle region updates once merged.

output: Use better arg naming for output_update_all_usable_areas()

---

include/labwc.h
include/view.h
include/xwayland.h
src/desktop.c
src/server.c
src/view.c
src/xwayland-unmanaged.c
src/xwayland.c

- Move xwayland-specific struct definitions to new `xwayland.h` header
- Move `xwayland_move_sub_views_to_front()` from `desktop.c` to `xwayland.c`
- Split out `xwayland_server_init/finish()` from `server_init/finish()`
- Rename `new_xwayland_surface` -> `xwayland_new_surface` and `xwayland_surface_new()` -> `handle_new_surface()` for consistency
- Add `mapped` argument to `xwayland_unmanaged_create()` so that we can make `unmanaged_handle_map()` private to `xwayland-unmanaged.c`

xwayland: Add xwayland.h and move more things to xwayland.c

---

src/output.c

Fixes (the size portion of) #681. The other half has an upstream fix as noted in the issue thread.

Ensure cursor is correctly scaled at startup

---

src/desktop.c
src/layers.c
src/seat.c

- Process layer-shell keyboard interactivity in the map and commit handlers only, rather than in layers_arrange(). This allows handling of the layer-surface that emitted the event rather than iterating over all surfaces in the output layer-tree, and therefore avoids having to guess which surface should have keyboard preference (and it might not be the last one added to the list which was the assumption previously).
- Prevent seat_focus_surface() from setting keyboard focus if a layer-shell surface with exclusive keyboard-interactivity has the focus.
- Set cursor_context type for layer-surfaces without node-descriptors in order to set keyboard focus correctly in cursor_button_press().
Tested satisfactorily with xfce4-panel and gtk-layer-demo.
Fixes #725 and #704

layer: improve keyboard-interactivity

---

src/output.c

The wlroots `wlr_output_layout` provides two different modes of operation:
- automatically
- manually
In automatic mode wlroots reacts to new / removed outputs and resolution
changes and then adjusts the output positions within the layout itself.
The manual mode disables this behavior and thus it is the whole
responsibility of the caller (e.g. us relaying whatever wdisplays /
kanshi provides) to ensure that the layout is somewhat sane. E.g. that
it doesn't have any holes between outputs and there are no overlapping
outputs.
The mode is set for each output individually. To use (and keep using)
the automatic mode, outputs have to be added via the `_add_auto()` variant
(which we do) and they are not allowed to be moved via `_move()` (which
we currently do and thus break the automatic …

src/output.c: only overwrite the automatic layout if necessary

---

meson.build
src/common/dir.c
src/common/scene-helpers.c
src/common/string-helpers.c
src/config/rcxml.c
src/config/session.c
src/cursor.c
src/debug.c
src/key-state.c
src/resistance.c
src/server.c
src/xbm/tokenize.c

Basically just copied over the compiler warning settings from wlroots and fixed those that came up for me.
We might want to keep `-Wmissing-field-initializers` and `-Wmissing-braces` though, wlroots disables these (which is what this PR is doing as well). See https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html for a description of both.
Another candidate to enable: `-Wunused-macros`, it only detects unused defines in `.c` files though.

Enable more compiler warnings

---

include/view.h
src/foreign.c
src/view.c
src/xwayland.c

I have a another branch waiting that depends on this PR which moves the foreign-toplevel output notifications over to the scene graph emitted events.
Only actual change besides some refactoring:
- implement the `destroy` handler (which just removes the event listeners, required for the follow up PR).

src/foreign.c: refactor

---

include/labwc.h
include/view.h
src/foreign.c
src/view.c

This is the 2nd iteration, the 1st one (using the `wlr_scene_buffer` `output_enter` / `output_leave` events) doesn't work because it will send an `output_leave` event whenever the window is completely occluded. It also required setting up a "click-through" `wlr_scene_buffer` on top of the view which required that its size kept getting synchronized with the actual view size.
This version now simply loops over all outputs and notifies the wlroots foreign_toplevel implementation about the current state.
The wlroots implementation takes care of
- de-duplicating the events (e.g. not send `output_enter` for the same output twice)
- listening to output destroy events, sending `output_leave` if the output was entered before
Benefits over our current implementation:
- will detect all outputs the …

src/foreign.c: track outputs

---

docs/rc.xml
include/config/keybind.h
include/config/mousebind.h
src/action.c
src/config/keybind.c
src/config/mousebind.c
src/config/rcxml.c
src/keyboard.c
src/menu/menu.c

Fixes #567
I did not really test this in depth so draft for now until it received some proper testing.
Changes this PR is doing:
- when creating a `None` action we don't actually create an action at all and just return `NULL` for the action
- we deduplicate keybinds the same as mousebinds (so we also get rid of the `_reverse()` when checking for keybinds + loop over slightly less entries in the keybind list for every key event)
- after the deduplication, all bindings with an empty action list are removed
This means that both of these variants now cause the creation of a keybind without any action which then first replaces all previous binding for the same key and finally gets removed because it has an empty action list, effectively removing an earlier binding set for `W-F4`:
```xml …
```

Allow clearing key/mouse bindings

---

include/view.h
src/xwayland.c

This fixes an issue when starting VLC in fullscreen mode (using XWayland). The VLC window would end up much smaller than the full screen, but undecorated.
The immediate cause appears to be that labwc receives, for the VLC view, a `request_fullscreen` event followed by a `request_configure` event (with the non-fullscreen geometry). I am not certain if this is the order VLC is actually sending the events, or if they get received out-of-order for some reason.
Anyway, the intent (judging from the behavior under Openbox) appears to be that the geometry sent via the `request_configure` event should be the natural geometry of the VLC window if/when VLC eventually leaves fullscreen mode.
Misc. notes:
- `view_is_floating()` is separate because I imagine that it may be useful in other places as …

xwayland: Fix size issue when starting VLC fullscreen

---

src/xwayland.c

Revises the logic for setting the initial geometry of XWayland views, so that we can save the natural geometry correctly even if `request_maximize` or `request_fullscreen` events are received before `map()`.
This way, an application that sets a recommended "natural" size at startup, while also requesting maximized/fullscreen, will restore back down to the recommended natural size after being unmaximized/leaving fullscreen.
Tested working with Audacious (Qt5), VLC (Qt5), and Claws Mail (GTK2).
VLC also needs https://github.com/labwc/labwc/pull/753 to work correctly when starting in fullscreen mode.

xwayland: Save natural geometry from initially maximized views

---

include/view.h
src/xdg.c

The pending move/resize logic in `xwayland.c` saw some fixes a while back in 80792d446f64a7ed01b04e39e11018b904413533 and 065c37d3f5eed86dc218c9722e245fa5fda9bd75. Portions of those fixes should have been applied to `xdg.c` as well. So I'm (very) belatedly circling back to make the logic in `xdg.c` consistent.
This removes the last use of the `pending_move_resize.update_x/y` flags, which can now be removed.
Please see commit messages for details.

xdg: Pending move/resize logic fixes

---

src/menu/menu.c

If a menu was opened via keybind while the cursor was on another, differently-sized output, the wrong usable area was used to position the menu.

menu: Compute usable area for the correct output

---

include/ssd-internal.h
include/view.h
src/action.c
src/cursor.c
src/foreign.c
src/interactive.c
src/resistance.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_titlebar.c
src/view.c
src/xdg-popup.c
src/xdg.c
src/xwayland.c

Wrap up separate `x/y/width/height` fields into `struct wlr_box` for convenience.
No functional change.

view: Use wlr_box for current/pending geometry

---

include/view.h
src/view.c
src/xdg.c

- Make sure that `view->pending_move_resize` is always up-to-date for mapped views
- Use `view->pending_move_resize` rather than `view->x/y/w/h` for view positioning logic
By using the pending (most recently requested) dimensions instead of the current (displayed) dimensions of the view for positioning logic, we can avoid race conditions that might occur if we try to reposition a view while there is a pending move/resize that has not been processed yet.
This *should* fix #671 (I have not verified the fix since reproducing the issue looks quite involved).
It also greatly simplifies the logic that was committed in #680 since we can now use `view_center()` again, still without touching `view->w/h` before commit. I did test that there is no regression of that fix.

view: Use pending geometry for positioning logic

---

src/xdg.c
src/xwayland.c

This is a minimal fix for the regression described in #760. It basically restores the status quo prior to 103a2a8f6c38a8eb664160e369477cad98003598.
- Don't overwrite pending size in `map()` if it was already set
- Don't reposition view in `map()` if maximized/fullscreen
Also, as future-proofing in case we one day allow initially-tiled views, replace explicit maximized/fullscreen checks with `view_is_floating()`.
I haven't attempted to address the separate (pre-existing) issue of `foot --maximized` always appearing on the top-left output (regardless of cursor position). There may also be issues with saving/restoring natural geometry for initially-maximized xdg-shell views -- I suspect that has never worked correctly (hence the `set_fallback_geometry()` workaround in `view.c`).

xdg: Fix positioning of initially-maximized views

---

include/labwc.h
src/server.c
src/xdg.c

This PR allows applications to activate themselves <b>if they provide a valid xdg_activation token</b> (e.g. raise to the top and get keyboard focus).
These tokens are given out by the xdg_activation protocol implemented in wlroots and can be configured by the client requesting the token in three ways:
- an "empty" token (apparently used to tell the compositor about "urgency")
- seat / input serial attached
- surface attached
Wlroots makes sure that
- <b>If</b> the client attached the seat / input serial: those two are valid.
- <b>If</b> the client attached a surface: that it has keyboard focus at the point where the request is finalized. There is a [patch](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/f6008ffff41f67e3c20bd8b3be8f216da6a4bb30) pending for backport to wlroots …

Add xdg-activation protocol

---

docs/labwc-config.5.scd

This probably solves this issue: #456 
I don't know what the policy about linking in man-pages is, but perhaps it would also be okay to link to the wev source page? Perhaps it would even be useful to mention the `xkbcommon-keysyms.h` header file.

docs: add hint for using wev

---

include/view.h
src/view.c

Also
- remove static inline (e.g. trust the compiler to optimize)
- move from `include/view.h` to `src/view.c`
As mentioned in https://github.com/labwc/labwc/pull/753#discussion_r1102841140 there is one other case where we do `static inline` + function implementation in a header file: https://github.com/labwc/labwc/blob/master/include/common/list.h
But in that case I would argue that we don't have a proper place to put it, creating a new `.c` file just to define that single function seems a bit excessive.

src/view.c: view_is_floating() add missing tiled_region_evacuate check

---

src/cursor.c

This is necessary because wlroots backported a patch containing
cursor name aliases to the 0.16 branch. That internal mapping
does not alias "grab" to "grabbing" because it is not technically
part of the cursor-names spec.
To keep the "grab" cursor working on systems with no cursor theme
available (or in an unusual location) change the trigger for our
internal cursor name aliasing to "grab".
See wlroots commit [1e345c74c3ca5d2575aa975d4d9af87cd0c7ba13](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/1e345c74c3ca5d2575aa975d4d9af87cd0c7ba13)
Alias existing cursor defaults to cursor-spec cursor names
for further details.

src/cursor.c: cursor names: use absence of "grab" to trigger fallback

---

src/view.c
src/xdg.c

It was not working before because in the case of wayland we are only dealing with sizes as wayland has no notion of a global position. A wayland client would thus not necessarily respond to a configure request which sets the same size again. This causes us to also not apply a new position set in view->pending because there may be no commit from the client in those cases.
We previously worked around this issue in some parts of the code to check our new sizes against the pending ones and if they were the same we would call view_move instead. That had two issues:
- Not all parts of the code did that which could end up delaying the positioning either to the next completely unrelated xdg commit event or to the next view_move call
- The code started to repeat itself, e.g. the same condition …

view: make view_move_resize always work

---

src/xdg.c

Before this patch, configuring a surface with a new size,
immediately followed up by one or more view_move() calls
would move the surface to the new coordinates immediately
without waiting for the resize. This caused visual glitches
when for example dragging a maximized window: the position
would change but the size was still that of a maximized
window.
This patch fixes that by just ignoring view_move() requests
(but still updating view->pending) if there is a configure
request pending. Once the client commit comes in the new
size will be applied as usual.
---
This PR is depends on
- #774
Will rebase and "undraft" once merged.
---
Void build error is unrelated to this PR

src/xdg.c: sync move with pending resize 

---

src/ssd/ssd_extents.c

`wlr_output_layout_get()` returns `NULL` for disabled outputs.
Backtrace (abbreviated):
#0  lab_wlr_output_layout_layout_coords at ../src/ssd/ssd_extents.c:33
#1  ssd_extents_update at ../src/ssd/ssd_extents.c:133
#2  ssd_extents_create at ../src/ssd/ssd_extents.c:95
#3  ssd_create at ../src/ssd/ssd.c:161
#4  decorate.part.0.lto_priv.0 at ../src/view.c:637
#5  decorate at ../src/view.c:636
#6  view_set_fullscreen at ../src/view.c:716
#7  view_adjust_for_layout_change ../src/view.c:745
#8  desktop_arrange_all_views ../src/desktop.c:52
#9  output_update_all_usable_areas at ../src/output.c:495
#10 output_update_for_layout_change at ../src/output.c:263
#11 do_output_layout_change at ../src/output.c:423
#12 do_output_layout_change at ../src/cursor.c:267
#13 output_config_apply at …

ssd: Fix segfault when disabling output with fullscreen view

---

src/desktop.c
src/view.c

While working on a different change, I noticed that in some cases (generally at labwc startup, when several windows are created at once) we were calling `view_compute_centered_position()` with an empty width/height. This occurs because `desktop_arrange_all_views()` has no regard for whether views are mapped or have an initial width/height set yet.
I don't think there were any user-observable side effects, but even so it seems best to avoid calling `view_compute_centered_position()` for views that have no initial width/height, since it's useless and (to me at least) unexpected, which could lead to surprises in future development.

desktop: Avoid centering views without initial geometry

---

include/view.h
src/view.c
src/xdg.c
src/xwayland.c

`view->impl->move()` is a specific case of `view->impl->configure()`. To reduce code duplication, we can use `view->impl->configure()` for pure moves (without resize) as well.
xwayland's `move()` function also possibly contained a race condition when there was a pending resize, as it used the current surface width/height rather than the pending width/height. Now we use the pending width/height so there is no race condition.
This may resolve the visual glitch @Consolatis mentioned in https://github.com/labwc/labwc/pull/775#issuecomment-1426973649. But I wasn't able to reproduce the glitch myself, so I can't verify.

view: Unify view_move()/view_move_resize()

---

include/regions.h
include/view.h
src/regions.c
src/view.c

Just a slight refactoring to follow the existing precedent that `struct view` fields are typically only modified within `view.c`.

view: Add view_evacuate_regions()

---

include/labwc.h
include/view.h
src/foreign.c
src/osd.c
src/output.c
src/resistance.c
src/view.c
src/xdg.c

A fullscreen view currently has its output specified twice by:
- `struct output *output`
- `struct wlr_output *fullscreen`
`view->fullscreen` may also become a dangling pointer if the output is disconnected, because `view_on_output_destroy()` clears `view->output` but not `view->fullscreen`.
To eliminate the redundancy and the dangling pointer, let's change `view->fullscreen` to a Boolean and rely on `view->output` to specify the output.
Along the way, change a few related usages of `struct wlr_output` to `struct output` as well.

view: Tidy up view->output/view->fullscreen redundancy

---

src/xwayland.c

The fix caused a couple of issues:
1. Ignoring client configure requests caused some clients to hang and not repaint correctly. We are supposed to synthesize a ConfigureNotify event when ignore/override a client configure request, but this isn't possible with current wlroots.
2. Setting `view->natural_geometry` from client configure requests resulted in overwriting good values with bad in some cases (e.g. with tiled xfce4-terminal in xwayland mode).
For now, revert the fix. This does allow clients to mess with view positioning for maximized/fullscreen/tiled views, but right now the alternatives seem worse.
The original specific issue (VLC undoing its fullscreen geometry) is arguably a bug in VLC anyway.
This reverts commit 09599861ac726b142a79ed60035809f04c151457.
Fixes: #785

Revert "xwayland: Fix size issue when starting VLC fullscreen"

---

include/labwc.h
include/view.h
src/output.c
src/view.c
src/xdg.c
src/xwayland.c

Fixes an issue where, if Thunar was started maximized, it would un-maximize to the top-left corner rather than the center. This occurs because we are storing a valid `natural_geometry.width/height` but leaving `natural_geometry.x/y` as 0,0.
In order to make `position_xdg_toplevel_view()` work without writing to `view->current` or calling `view_move()`, I made `view_compute_centered_position()` public again and added an `output` parameter.
Background/off-topic/related to #767:
Unlike `foot --maximized`, Thunar maximizes *at* map rather than sending a separate request *before* map. As a result, we are able to save the natural geometry, but also get a flicker at startup while the view adjusts to the maximized size. So currently it seems that either approach (Thunar vs. `foot` behavior) has …

xdg: Save natural_geometry.x/y with initially maximized view

---

src/view.c

Currently, `view_discover_output()` is only called by `view_moved()`. To be
consistent, we should also call `view_discover_output()` when the output
layout changes, since this can effectively "move" views to a different
output without actually calling `view_moved()`.
Letting `view->output` get out-of-date probably had minimal/obscure
effects in the current code, since in many cases we ignore `view->output`
altogether and find the nearest output "on the fly" with `view_output()`.
Nevertheless, I think it's still a bug and should be fixed.
Includes some slight refactoring in `view.c`:
- Add fullscreen case to `view_apply_special_geometry()`
- Split out private `set_fullscreen()` helper from `view_set_fullscreen()`
(similar to existing `set_maximized/view_set_maximized()` split)

view: Rediscover output in view_adjust_for_layout_change()

---

README.md

Fixes #690
@Joshua-Ashton @Flrian
As I can't test it myself, is this the right way to use gamescope for steam games?
Steam doesn't seem to provide any generic command prefix so I guess users have to modify the launch option of every single game they want to play unless I missed something.
Also not sure if we should mention `sudo setcap 'CAP_SYS_NICE=eip' $(which gamescope)` in there (and if labwc should try to renice to `-10` or something as well).

README.md: suggest using nested gamescope for gaming

---

src/xdg.c

Fixes the positioning issue with havoc mentioned in https://github.com/labwc/labwc/pull/794#issuecomment-1437427670.
Calling `position_xdg_toplevel_view()` from inside `handle_commit()` makes me a little nervous honestly, because it seems unexpected to be setting `view->pending` there. But it seems to work, and right now I can't think of any specific reasons not to do it. I'd appreciate someone else giving me a sanity check here, to make sure this doesn't break anything.

xdg: Use wlr_xdg_surface_get_geometry() to get size

---

include/labwc.h
src/output.c
src/view.c
src/xdg.c
src/xwayland.c

Just a small cleanup:
- Factor out a generic bit of code from `view_output()` as `output_nearest_to()`.
- Reimplement `output_from_cursor_coords()` as `output_nearest_to_cursor()`.

output: Add output_nearest_to()

---

include/labwc.h
include/view-impl-common.h
include/view.h
include/xwayland.h
src/desktop.c
src/keyboard.c
src/meson.build
src/view-impl-common.c
src/xdg.c
src/xwayland.c

Ref: https://github.com/labwc/labwc/pull/720#issuecomment-1374831834
Do later:
- Add view_impl apply_size_constraints to replace `xwayland.c`'s `xwayland_apply_size_hints()`
- `s/xwayland_server_init/xwayland_init/`
- `{xwayland,xdg_toplevel}_view_unmap()` code is the same. Move to `view-impl-common.c`
- ~~Move desktop_move_to_back() to view.c for consistency~~

Refactor view implementations following PR #720

---

docs/labwc-actions.5.scd
include/action.h
include/labwc.h
src/action.c
src/keyboard.c

This can be used to better control Virtual Machines, VNC clients, nested compositors or similar. All keybinds other than `ToggleKeybinds` itself are disabled when first called, a 2nd call will restore handling of all keybinds.
Fixes #738
Fixes #810
---
I only had a quick test nested with this so a proper test would be appreciated as I don't really have that much use-cases for this feature myself. To test this it should be enough to add something like this to `rc.xml`:
```xml
<keybind key="Scroll_Lock">
<action name="ToggleKeybinds" />
</keybind>
```
This PR does not add an always-on-top status indicator about the keybinds currently being disabled, that could be done as well but would require a bit more code to properly react to output layout changes. Thus I am not sure if such an …

Add ToggleKeybinds action

---

include/view.h
src/foreign.c
src/view.c
src/xdg.c
src/xwayland.c

Needs more thorough testing but I'm looking for initial feedback on the approach.
This comes with two (intentional) behavior changes:
- Maximized/tiled views now try harder to remain on the same output if the output layout changes
- Initially maximized xdg-shell views now appear on the cursor output (resolves #767)
`view->output` is now used as follows (copy & pasting from `view.h`):
```
/*
* The output that the view is displayed on. Specifically:
*
*  - For floating views, this is the output nearest to the
*    center of the view. It is computed automatically when the
*    view is moved or the output layout changes.
*
*  - For fullscreen/maximized/tiled views, this is the output
*    used to compute the view's geometry. The view remains on
*    the same output unless it is disabled or …
```

view: Refactor view->output usage

---

include/view-impl-common.h
include/view.h
src/view-impl-common.c
src/xdg.c
src/xwayland.c

Currently, we anchor the right/bottom edge of the view whenever the top/left edge is moving (`current.x/y != pending.x/y`). Doing so doesn't make much sense when the right/bottom edge is also moving. In that case it's probably best to move the view (or at least its top/left corner) directly to its final position.
The most noticeable effect of this change is with views that don't accept their requested size exactly when tiled or maximized (examples: havoc, xfce4-terminal). Previously, their right-bottom corner would be aligned with the screen edge, leaving gaps on the left and top. Now the top-left corner will be aligned and the gaps will be on the right and bottom. This is still not ideal, but IMHO less surprising to the user.
I don't fully understand all of the `update_required` logic in …

view: Anchor right/bottom edge only when resizing via top/left edge

---

include/labwc.h
include/regions.h
src/cursor.c
src/interactive.c
src/keyboard.c
src/regions.c

When wanting to snap to a region when starting the move
operation with A-Left (or a similar mousebind which includes a
modifier), the modifier - or another one - must be pressed again.
Fixes #761
---
Also includes a fix for the wlr_keyboard `modifier` event coming from wlroots.
We were just lucky that it didn't cause any issues, we were casting a `wlr_keyboard` pointer to a `wlr_keyboard_key_event` pointer before.

Prevent cursor based region-snapping when starting a move with A-Left 

---

include/common/font.h
src/config/rcxml.c

Reported-by: \<umk3\> via IRC
---
Only slightly tested but confirmed working via IRC.
Original issue was that setting something to a non-default value, `Reconfigure`, then deleting that setting and `Reconfigure` again wouldn't reset the state back to the default. Thus it would differ vs. restarting labwc.

src/config/rcxml.c: reset default values on Reconfigure

---

.github/workflows/labwc.github.io.yml

This is the final piece of the puzzle to automatically regenerate and deploy https://labwc.github.io whenever there are new commits in this repository that change the man pages.
Before this actually works we need to create a new token that provides access to the labwc.github.io repository.
I've tested this on my forked repos using a Personal access token, to be exact a fine-grained token for just the labwc.github.io repository which required these rights (and only those):
- Read and Write access to `Contents`
- Read and Write access to `Pages`
- Read access to `Metadata` (automatically selected once the other two are selected)
Finally, that resulting token (`github_pat_...` for me) must be stored as a repo (or potentially organization) secret. The secret must be named `WEB_DEPLOY_TOKEN`. …

CI: automatically rebuild labwc.github.io

---

src/cursor.c
src/osd.c

Fixes a regression caused by the recent enhancement of followMouse behavior.
Fixes: #849
Reported-by: mitigate via IRC

followMouse: allow focus switching via A-Tab

---

include/view-impl-common.h
include/view.h
src/desktop.c
src/view-impl-common.c
src/view.c
src/xdg.c
src/xwayland.c

@Consolatis @jech How about this as a pre-commit for PR #829 
`view_minimize()` does not need to call `desktop_move_to_back()` because the stacking order is not changed and the windowSwitcher uses the scene-tree nodes anyway.
I thought of not keeping `server->views` in sync with view z-order, but xwayland sub-views still relies on it.

desktop: move scene-tree node in move-to-back

---

src/cursor.c

Previously, the cursor image was only updated on output loss when the cursor was on a labwc owned surface. This patch forces a re-enter of a client surface in the remaining case of cursor being over a non-labwc surface which causes the client to re-set its own cursor image.
This fixes a regression caused by 4dc99e2f3856650f3b61778f015a823cfae978d2.
Thanks to @Flrian for finding the root cause of the issue.
Fixes #820
Reported-by: @Flrian
Tested-by: @Flrian

src/cursor.c: fix invisible cursor on output loss / restore

---

include/labwc.h
include/view.h
src/action.c
src/cursor.c
src/desktop.c
src/foreign.c
src/keyboard.c
src/view-impl-common.c
src/view.c
src/xdg.c
src/xwayland.c

This avoids calling `view->impl` functions from `cursor.c` and `desktop.c`.

view: Add view_move_to_front/back() with _no_focus variant

---

include/labwc.h
src/desktop.c
src/xwayland-unmanaged.c

Check that an unmanaged surface trying to grab focus is actually a child of the topmost mapped view.  Without this patch League of Legends is reported to re-grab focus within milli-seconds of alt-tabbing away from the game.
Related-to: #874

xwayland: validate PID before activating unmanaged surface

---

src/output.c

Make sure that only the session lock layer is visible to a user. Fixes the issue with mako notifications being rendered above the swaylock window.

output: Make the session lock layer the topmost

---

src/server.c

Prevent wayland clients that request the X11 clipboard but closing their read fd prematurely to crash labwc because of the unhandled SIGPIPE signal. It is caused by wlroots trying to write the X11 clipboard data to the closed fd of the wayland client.
See https://github.com/labwc/labwc/issues/890#issuecomment-1524962995 for a reproducer involving xclip and wl-paste | head -c 1.
Fixes #890
Reported-by: @FuzzyQuills

Ignore SIGPIPE

---

src/common/match.c

match.c: fix g_utf8_casefold() memory leak

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/cursor.c

This implements the same config option as `underMouse` in Openbox.
Fixes #862
---
The implementation uses a different name for the config than Openbox (`followMouseRequiresMovement` vs `underMouse` which I hope is easier to understand and doesn't require looking it up in the docs). The default of the new config is set to `yes` to restore the previous behavior of `followMouse`.
If set to `no`, this PR currently prevents focusing new windows even if the cursor is at the place the new window spawns, I am not quite sure why that is. It also wasn't really tested in depth so draft for now. Practical testing (with reports including the tested variant of `yes`/`no`) welcome.
CC @bi4k8 @jech
Ref:
- #830
- #862

followMouse: add followMouseRequiresMovement

---

include/xwayland.h
src/xwayland-unmanaged.c
src/xwayland.c

This is a trivial cleanup to make `xwayland_view_create()` symmetrical with `xwayland_unmanaged_create()`, and avoid the need to access `view->impl` from xwayland-unmanaged.c.
The return value of `xwayland_view_create()` is no longer used, so return `void`.
No functional change.

xwayland: Add mapped argument to xwayland_view_create()

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/window-rules.h
src/config/rcxml.c
src/window-rules.c

Example config:
```
<windowRules>
<windowRule identifier="foot" title="foo"><action name="Maximize"/></windowRule>
</windowRules>
```
Observe that:
- `foot -T foo` starts maximized
- `xterm -T foo` starts normal

window-rules: support title criteria

---

docs/labwc-actions.5.scd
docs/rc.xml.all
include/workspaces.h
src/action.c
src/workspaces.c

Make wrap 'true' by default for both GoToDesktop and SendToDesktop, in order to default the current behaviour.
For GoToDesktop OpenBox defaults to wrap="yes", but I don't know whether OpenBox SendToDesktop does the same.
Note: this is an interface change.

action: support {Go,Send}ToDesktop 'wrap' option

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
include/labwc.h
include/view.h
include/window-rules.h
src/action.c
src/config/rcxml.c
src/desktop.c
src/osd.c
src/server.c
src/view-impl-common.c
src/view.c
src/window-rules.c
src/xdg-popup.c

Add
- ~~ToggleAlwaysBelow~~ `ToggleAlwaysOnBottom`
- `skipTaskar`
- `skipWindowSwitcher` (which isn't really needed for this because window-switcher doesn't show views in always-below-tree, but it seems more complete to include it here anyway in case we change the window-switcher behavior later)
Try it with (--EDITED--):
```
<windowRules>
<windowRule title="pcmanfm-desktop*" skipTaskbar="yes" skipWindowSwitcher="yes">
<action name="ToggleAlwaysOnBottom"/>
</windowRule>
</windowRules>
```
This example is not output-centered like a layer-shell implementation would be, but rather works across the whole work area.
In `pcmanfm-qt` desktop-preferences the following settings are useful:
- `Background` - individual wallpapers for each monitor. This looks better if you have outputs of different …

Add window rules and actions for `pcmanfm-qt --desktop`

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/labwc-theme.5.scd

Between, output, rounded and focused.
Added one inconsistently missing trailing period.
Inserted newline before last word in one line in
labwc-actions.5.scd in order to keep that line from passing 80-column boundary.

docs: fix some typos

---

include/cursor.h
src/dnd.c

Keyboard focus is not changed during drag, so we need to refocus the surface under the cursor and the end of a drag-and-drop operation.
This fixes the issue described in #939, but I'd appreciate if anyone has time to do some testing to make sure it doesn't break something else :smile:

dnd: refocus surface under cursor on drag-destroy

---

src/config/rcxml.c

Specify attribute name when adding default mousebind actions.
This is required because in src/action.c action GoToDesktop requires an argument with key 'to' and does not accept `action_get_first_arg()` because the action supports other optional attributes so we could not guarantee that 'to' is the first one.
Fixes: #948

config: fix bug with default scroll mousebind

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all
include/common/border.h
include/config/rcxml.h
include/ssd.h
include/window-rules.h
src/action.c
src/config/rcxml.c
src/layers.c
src/window-rules.c

Try with
```
<margin top="32" />
<windowRules>
<windowRule identifier="lxqt-panel" matchOnce="true">
<skipTaskbar>yes</skipTaskbar>
<action name="MoveTo" x="0" y="0" />
<action name="ToggleAlwaysOnTop"/>
</windowRule>
<windowRule title="pcmanfm-desktop*">
<skipTaskbar>yes</skipTaskbar>
<skipWindowSwitcher>yes</skipWindowSwitcher>
<action name="MoveTo" x="0" y="0" />
<action name="ToggleAlwaysOnBottom"/>
</windowRule>
</windowRules>
```
- ~~Hide always-on-top layer when running an application in full-screen~~ Moved to first post of #941

Add `<margin>` and `MoveTo` in support of `lxqt-panel`

---

src/action.c

Adding MoveTo showed better way to implement this than i have been using in my own fork, now this should work like openbox specification says.

add MoveRelative

---

docs/labwc-theme.5.scd
docs/themerc
include/common/graphic-helpers.h
include/theme.h
src/common/graphic-helpers.c
src/osd.c
src/theme.c
src/workspaces.c

--EDIT-- This list is now managed at #968 
Based on @1qh list in issue #879
- focused item background and text color
- position of desktop name (top/bottom)
- different font size for desktop switcher and window switcher
- size of the squares in desktop switcher
TODO:
- Consider allowing window-switcher width to be specified as a percentage of output width
- Calculate window-switcher width based on item-width + padding
- ~~Take into account output->scale~~
- osd.c: simplify the get_title() helper and associated `is_title_different()`
- Cope with many `nr_items` * `item_height` > `output_height`
- Show always on-top windows
- Consider showing multiple work-spaces in window-switcher (although config might get pretty hard
- Consider showing window thumbnails :smile:
Notes:
Have used …

OSD improvements

---

include/view.h
src/view.c
src/xdg.c
src/xwayland.c

This makes explicit the subtle behavioral difference between `xwayland_view_unmap()` and `handle_unmap()`.
With this change, the XDG and XWayland versions of `handle_map/unmap()` are now identical, which will make further refactoring possible.

view: add client_request flag to view->impl->unmap()

---

src/action.c
src/view.c

I noticed that if window is snapped to edge, resized with ResizeRelative, then moved with mouse it returns to size it was before snap to edge. Can be fixed by adding view_set_untiled.
Also both MoveRelative and ResizeRelative don't check if view is fullscreen or maximized, should we change that? I think they should be disabled at least for fullscreen.

Set untiled in ResizeRelative and maybe other fixes

---

include/action.h
src/action.c
src/config/rcxml.c
src/menu/menu.c

And assign argument names.
Missing:
Fixes:
- #894

More robust action argument parsing

---

docs/labwc-actions.5.scd
docs/labwc-theme.5.scd
docs/themerc
include/labwc.h
include/ssd.h
include/theme.h
include/view.h
src/action.c
src/keyboard.c
src/ssd/ssd.c
src/theme.c
src/view.c

Did some more work on the new `ToggleKeybinds` action so that it works per window (view).
I started with storing a list of surfaces in `struct seat` and only inhibiting keybinds when one of those surfaces had focus.
Then switched to storing a list of views instead of surfaces and finally ended up on just a simple `bool` for `struct view` + a counter for `struct seat`. The counter is just a performance optimization so we don't have to check further unless that counter is `> 0`.
I've also added a (pretty strange) SSD status indicator as a proof of concept:
I am not sure what the best approach for the status indicator would be, turning the whole border to another color isn't that easy because we'd actually have to redraw the rounded corners as well (as they are also part of the border). …

ToggleKeybinds per window

---

include/idle.h
include/labwc.h
src/cursor.c
src/idle.c
src/keyboard.c
src/meson.build
src/seat.c
src/server.c
src/touch.c

Should fix
- #980
Potential issues:
- It seems our implementation for the idle inhibitor is not complete, it looks like it should check if one of the active inhibitor surfaces is currently visible. I would have to look up the scene API again if there is an easy way for us to figure that out.
- We don't properly clean up the manager when shutting down labwc. This is arguably  a pretty minor issue as the memory is released on exit anyway. We could add that here by listening to the `wl_display` destroy event.

Add support for ext_idle_notify_v1 and combine both variants into a standalone manager

---

docs/labwc-actions.5.scd

Noticed when copy&pasted `<action name="ToggleKeybinds">` into `rc.xml` and reloaded config.
Btw nice improvement: this action fixes an accidental closing of lxqt-panel by shortcut.

Added missing closing tags

---

src/xwayland.c

Backtrace: https://github.com/labwc/labwc/pull/626#issuecomment-1637515904
I don't see the segfault with wlroots 0.16.2, but it doesn't hurt to cover our bases.

xwayland: Fix segfault at exit (seen with wlroots master)

---

src/common/scaled_scene_buffer.c
src/xwayland.c

Background: @Consolatis previously mentioned wanting to keep #626 as small as we can (and I agree). These are a couple of the smaller commits that can be merged without breaking compatibility with wlroots 0.16.
- Add a missing header (pulled in indirectly with wlroots 0.16 but no longer with 0.17)
- Remove some asserts that will no longer hold true with wlroots 0.17

Trivial wlroots 0.17 compatibility fixes

---

docs/labwc-theme.5.scd

...which has been supported for a long time but not been reflected in the man page.  Colors can be parsed as `#rrggbb aaa` with aaa representing a decimal alpha value. This could be used to hide a button, for example:
window.active.button.menu.unpressed.image.color: #000000 0
window.inactive.button.menu.unpressed.image.color: #000000 0
We could add a note on the web-site tips & tricks about this.
I have a feeling there is even an issue against this somewhere.

labwc-theme(5): describe color alpha value

---

include/view.h
src/view.c
src/xdg.c
src/xwayland.c

This behaviour is consistent with that of mutter and openbox.
Tested with mousepad's 'about' dialog
Fixes: issue #823

Show modal dialog above parent window

---

include/action.h
src/action.c
src/config/rcxml.c

This happens because of two separate bugs:
- The action validation failed to verify the data type of the argument
- When adding the fallback keybinds we add them as string but expect them being an int
This commit fixes the first bug.
Fixes 1ee8715d57ddb6b444e0b089879db6f837400539
actions: use enum for _ToEdge actions
The first commit will cause the action validation to work correctly / more strict and thus remove the keybinds.
The second commit will cause `action_arg_from_xml_node()` being used for the default mouse- and keybinds.
Sorry for everybody that might have been exposed to labwc suddenly crashing.

Fix crash when using _ToEdge actions when using the default keybinds

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/ssd-internal.h
include/ssd.h
include/view.h
src/config/rcxml.c
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_extents.c
src/ssd/ssd_titlebar.c
src/view.c

Fixes #813
Just a quick and dirty implementation with not that much testing.
TODO:

Add keepBorder `<theme>` option and enable it by default

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/resize_indicator.h
include/view.h
src/common/font.c
src/config/rcxml.c
src/interactive.c
src/server.c
src/ssd/meson.build
src/ssd/resize_indicator.c
src/view.c
src/xwayland.c

Partly fixes
- #1013
Current limitations:
- ~~only supports `<resize popupShow="Always / Never" />`~~
- ~~size hints are ignored, e.g. its either the position for a move operation or the size for a resize operation~~
- `popupPosition` is not supported and always set to `Center`, e.g. being centered within the window
- the OSD is using the same font as for the `A-Tab` window switcher, thus configuring the font weight affects both
- should we add another font place for this specific OSD? Having it in bold looks better IMHO but would cause `A-Tab` to be in bold as well
Deviations from Openbox:
- the position is shown as `100 , 250` rather than `100 x 250` (as that is a size and not a position).
The resize indicator is disabled by default.
Missing:
- does this OSD deserves its own font place …

Add optional resize / move indicator

---

include/view.h
scripts/checkpatch.pl
src/desktop.c
src/osd.c
src/view.c

...to reduce code duplication.
The function populates an array with views which meet any set of critera from:
- current-workspace
- no-always-on-top
- no-skipWindowSwitcher (window-rule)
Make src/osd.c use this new interface. Note that always-on-top views are still filtered out from the window-switcher and that desktop_cycle_view() needs to be re-worked before always-on-top views can be opted in.

Add view_array_append() and for_each_view()

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/osd.c

...to be consistent with window rules.
The use of 'app_id' for window-switcher fields is hereby deprecated.

config: s/app_id/identifier/ for window-switcher field

---

include/ssd-internal.h
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c

Partly addresses
- #1044
Main issues with this PR:
Regarding the corner button leakage.. I am not sure how to tackle this.
If wlroots 0.16 would already provide the scissor support for scene nodes we could just cut the border away from the buttons. There are two other options I see:
- create an additional no-border variant for every corner button (active / inactive, left / right, border / no-border)
- combine this with the long standing `unround-corners-on-maximize` issue and use a scene graph rect for the background of the corner buttons when maximized
Regarding the config setting: not sure if we need / want one or if we just disable borders / unround corner buttons on maximize

src/ssd: disable border and un-round corners on maximize

---

include/ssd.h
src/ssd/ssd.c
src/ssd/ssd_border.c
src/ssd/ssd_titlebar.c
src/view.c

The previous PR introduced an issue with tiling based actions like SnapToEdge and SnapToRegion using outdated SSD margin values when called via keybind while maximized. That resulted in wrong offsets for the tiled windows.
This commit restores the functionality by forcing a re-calculation of the SSD margin when changing the maximized state.
Thanks to @Flrian for reporting the issue via IRC.

src/ssd: fix tiling via keybind when maximized

---

src/osd.c

Fixes:
- #1050
Reported-by: @4ffy (thanks)

src/osd.c: prevent crash with theme setting osd.window-switcher.width: 0

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/libinput.h
src/config/libinput.c
src/config/rcxml.c
src/seat.c

Addresses #1064 with tap-and-drag support.
This PR also fixes a problem that enums initialized with -1 are bigger than 0 because gcc uses unsigned int as default backing type of enum.
This is my first time sending a PR to OSS, so excuse me if I made silly mistakes.

config: support <libinput><device category=""><tapAndDrag> & <dragLock>

---

docs/labwc-config.5.scd
include/window-rules.h
src/config/rcxml.c
src/window-rules.c
src/xdg.c
src/xwayland.c

This PR allows to use window rules to block self-activation requests from xwayland and wayland native windows.
It is different from preventing focus completely, e.g. manually selecting the window via `A-Tab` or similar still allows interaction with the window.
Example config:
```xml
<windowRules>
<windowRule identifier="*firefox*" ignoreFocusRequest="yes" />
</windowRule>
```
I have not tested this PR at all as I'd need to set up some testing environment which supports the xdg_activation protocol. It would take much longer than creating this patch in the first place, so testing would be much appreciated.
Outstanding questions / issues:
Support for them could be added pretty easily though because we already fetch the topmost mapped view in `unmanaged_handle_request_activate()` due to …

window-rules: add ignoreFocusRequest property

---

src/xdg.c
src/xwayland.c

When a view is destroyed (including override_redirect in the xwayland case), the view_destroy() handler is called which checks for a currently open A-Tab window switcher and causes an update there to remove the destroying view from the list. Before view_destroy() is called, both xwayland and xdg handlers reset the xdg_surface / xwayland_surface.
The window switcher update then creates a list of all windows which do not have the 'skipWindowSwitcher' window rule property set. If there is at least one 'matchOnce' window rule configured, this also tries to get string properties of the destroying view which already had their xdg_surface / xwayland_surface reset and thus run into an assert.
This patch fixes that so that the string_prop() handlers always return an empty string in those cases …

Ensure xdg and xwayland string_prop() handlers deal with destroying views

---

include/ssd.h
src/ssd/ssd.c
src/view.c

Before this patch we were using the internal .enabled flag of the titlebar tree node. This failed due to ssd_thickness() not having view->ssd assigned when initially called. Instead of assigning view->ssd within ssd_create() we just always use the view boolean flag directly. This fixes an issue where a border-only view that has been snapped to an edge or region would have a gap in the size of the titlebar on top after a Reconfigure.
Fixes
- #1083

src/ssd: use view->ssd_titlebar_hidden for ssd_thickness calculations

---

src/common/buf.c

common/buf.c: do not use memcpy for overlapping regions

---

include/view.h
include/xwayland.h
src/ssd/resize_indicator.c
src/view.c
src/xwayland.c

For views with a non-pixel size increment (e.g. X11 terminals), it's helpful to subtract the base size of the window (typically including menu bar, scrollbars, etc.) before computing the number of size increments (e.g. cells/characters). This way, the displayed size will exactly match the terminal grid (e.g. 80x25 or whatever).
`wlr_box` isn't really the best fit for size hints, so let's define a `struct view_size_hints` and a nice `view_get_size_hints()` function, wrapping `view->impl->get_size_hints()`.
This also seems like a great opportunity to make `view_adjust_size()` window-system-agnostic and eliminate `xwayland_apply_size_hints()`.

view: account for base size in resize indicator

---

include/labwc.h
include/view.h
src/action.c
src/cursor.c
src/desktop.c
src/foreign.c
src/keyboard.c
src/view-impl-common.c
src/view.c
src/xdg.c
src/xwayland.c

Our current approach to handling the focused/active view is a bit confusing. In particular, it's hard to be sure when `server->focused_view` is or isn't in sync with the real wlroots keyboard focus.
Try to clean things up a bit. In particular:
- Add comments to `server->focused_view` and `desktop_focused_view()` to clarify that they should match, but it's not guaranteed.
- `desktop_focused_view()` now prints a warning if it detects that `server->focused_view` is out of sync. We should keep an eye out for this warning, and if we see it, try to figure out why it happened.
- For consistency, use only "focus/defocus" as the verbs in function names rather than "activate". This is a bit arbitrary, but the idea is that focus is the primary action while the active/inactive state is a side effect. …

view: try to reduce confusion in focused_view tracking

---

include/key-state.h
src/key-state.c
src/keyboard.c

...and avoid failing to send release events to clients for any keys that were not absorbed by a keybind.
Do not match keybinds if there are other non-modifier keys (not part of any defined bind) pressed at the same time.
Only store non-modifier keycodes in the key-state.c 'pressed' array. This makes the call to wlr_seat_keyboard_notify_enter() in seat_focus() consistent with the equivalent in sway (in seat_keyboard_notify_enter()).
Fixes: issue #1091

keyboard: make keybind match stricter

---

src/keyboard.c

Do not withhold the release event associated with a keybind which executes a keyboard-input-inhibiting client like swaylock.
In other words, make release-events of absorbed keys (those used up by a keybind) de-register as such even though session-lock or input-inhibit is in-force.
Fixes: issue #1114

keyboard: fix release event bug after session lock

---

include/labwc.h
include/view.h
src/action.c
src/cursor.c
src/desktop.c
src/keyboard.c
src/seat.c
src/view.c
src/workspaces.c

- Connect to `wlr_seat_keyboard_state`'s `focus_change` event.
- Add `view_from_wlr_surface()`, which does what the name says.
- Use `focus_change` event along with `view_from_wlr_surface()` to update `server->focused_view` and set SSD states via `view_set_activated()`.
- Eliminate `desktop_focused_view()` since `server->focused_view` should be reliably up-to-date now.
- Eliminate `view_focus/defocus()` since we can now just call seat_focus_surface() directly.

seat: use focus_change event to update focused/active view

---

src/dnd.c
src/xwayland-unmanaged.c

These are a couple of commits authored by @Consolatis that are cherry-picked from #626. They are for wlroots 0.17 compatibility, but have no negative side effects with wlroots 0.16 either. So I think we might as well merge them in now.

various: stop using data argument of wlroots event callbacks

---

include/labwc.h
include/view.h
src/desktop.c
src/seat.c
src/session-lock.c
src/view.c
src/workspaces.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c

XWayland views can self-declare that they don't want keyboard focus via
the ICCCM WM_HINTS property. Most of the logic is already in place to
avoid giving focus to such views (e.g. taskbars).
Add a couple of missing pieces to make this work:
- Hook up `view_isfocusable()` to look at WM_HINTS for XWayland views
- Adjust `desktop_focus_topmost_mapped_view()` to skip unfocusable views
I also noticed that in several places, we will still focus and
raise a view regardless of `view_isfocusable()`. To fix this, make
`desktop_focus_and_activate_view()` return false if the view isn't
focusable, and don't raise the view to the front in that case.
Possible FIXME: a couple of places still call `workspaces_switch_to()`
before `desktop_focus_and_activate_view()`. Maybe switching workspaces
should also …

view/xwayland: avoid focusing views that don't want focus

---

include/key-state.h
src/key-state.c
src/keyboard.c

...with the equivalent function that returns the number of pressed keys.
s/key_state_nr_keys/key_state_nr_bound_keys/

key-state: rename function for consistency

---

src/xwayland-unmanaged.c
src/xwayland.c

`xsurface->data` is presumed to be a `(struct view *)` if set, so it must be left `NULL` for an unmanaged surface. Otherwise `view_from_wlr_surface()` may return a `(struct xwayland_unmanaged *)` where a `(struct view *)` was expected, leading to a crash.
valgrind backtrace:
Invalid read of size 1
at 0x48F8FFC: wlr_scene_node_set_enabled (wlr_scene.c:903)
by 0x124C9F: ssd_set_active (ssd.c:323)
by 0x124C9F: ssd_set_active (ssd.c:318)
by 0x124C9F: view_set_activated (view.c:215)
by 0x118851: focus_change_notify (seat.c:353)
by 0x487E01D: wl_signal_emit_mutable (wayland-server.c:2241)
by 0x48FC8F2: wlr_seat_keyboard_enter (wlr_seat_keyboard.c:298)
by 0x119E60: seat_focus.lto_priv.0 (seat.c:473)
by 0x1248FD: seat_focus_surface (seat.c:491)
by 0x1248FD: unmanaged_handle_map …

xwayland: do not set xsurface->data for unmanaged surface

---

include/session-lock.h
src/output.c
src/session-lock.c

Currently, if the output layout changes while the session is locked, the lock surfaces may end up wrongly positioned, which looks bad and may reveal some of the user's workspace underneath.
As an example, this is what my desktop looks like after docking my laptop:
To prevent this, reposition the session-lock scene trees and reconfigure the lock surfaces when the output layout changes.
P.S. It may also make sense to disable/destroy the lock surfaces for disabled outputs. I think the black rectangle in the picture was originally meant for the laptop display, which turns off when docked. (It's not visible after this change - maybe just hidden behind one of the other lock surfaces.)

session-lock: reconfigure for output layout changes

---

src/keyboard.c

I noticed that one currently can't switch to a different VT if the labwc session is locked. It seems undesirable to have to unlock one VT session just to switch to another one (which potentially belongs to a different user).
Assuming this was unintentional, can we allow switching VTs while locked? It appears to be as simple as reordering the two logic steps in `handle_compositor_keybindings()`.

keyboard: allow switching VT when locked

---

docs/labwc-theme.5.scd
docs/themerc
include/theme.h
src/theme.c

**Description:**
Openbox and Labwc currently calculate the title size based on the font size. This can be limiting for users who want to customize the window title's appearance. For instance, if someone desires a larger title height without increasing the font size, the current system doesn't provide an solution.
**Proposed Change:**
This pull request introduces a new configuration setting in the 'themerc' configuration file: `titlebar.height`. With this setting, users can now specify the desired title height independently of the font size. If the font size specified is larger than the `titlebar.height` setting, then will use the font size.
**How to Use:**
1. Edit your 'themerc' configuration file.
2. Add or modify the `titlebar.height` setting, specifying your desired title height.
3. …

Refactor title height to use 'titlebar.height' from themerc

---

src/config/keybind.c
src/keyboard.c

<b>keybinds: add support for Meta and Hyper modifiers</b>
The modifiers can be used in keybinds via `M-key` and `H-key`
Additionally adds support for:
- `Mod1` (same as `A`)
- `Mod3` (same as `H`)
- `Mod4` (same as `W`)
- `Mod5` (same as `M`)
This is compatible with the format used by Openbox.
(http://openbox.org/wiki/Help:Bindings#Syntax)
`Mod2` (`NumLock`) and `Caps` are still not supported due
to their locking behavior but could theoretically be added.
Fixes:
- #1061
This patch does not support the same changes for mousebinds.
----
<b>keyboard: prevent storing synthetic layout change key event</b>
Before this patch, we were storing the key in our pressed set
and didn't remove it which in turn caused all further keybinds
to fail. The behavior was dependent on the exact flow of press
and …

keybinds: add support for Meta and Hyper modifiers

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
src/config/rcxml.c
src/keyboard.c
src/seat.c

This should get us most of the way to solving #637. I haven't coded up the bits to hook it up to rc.xml; help with that would be welcome.
A minor surprise is that the initial NumLock state is re-applied (to all keyboards) if a new keyboard is hot-plugged. It's wlroots doing this behind our back, though with a little more code we could prevent it. In my opinion, it's a pretty minor issue (but then, I basically never turn off NumLock).

keyboard: set numlock automatically

---

include/labwc.h
include/menu/menu.h
src/action.c
src/main.c
src/menu/menu.c

...to make it easier to split menu.c into smaller chunks without exposing nr_menus variable.

menu: use wl_list instead of array

---

src/output.c

Use the same fix/workaround as in `output_update_for_layout_change()` to make sure that the cursor is also visible after (re-)enabling an output in `handle_output_power_manager_set_mode()`.

output: fix invisible cursor after wlopm --off && wlopm --on

---

include/view.h
src/desktop.c
src/view.c

Fixes:
- #1170
Reported-by: @stefonarch
Reported-by: @tsujan
Testing would be appreciated.

desktop.c: prevent switching workspaces for always-on-bottom windows

---

.github/workflows/build.yml

This prevents the FreeBSD runner to run for 6 hours in a bootloop.
Ref:
- https://github.com/vmactions/freebsd-vm/issues/74

CI: limit workflow runs to 20 minutes

---

include/view.h
src/seat.c
src/view.c
src/xwayland.c

Allows removing xwayland-specific stuff from seat.c.
Based on a suggestion from @Consolatis.

view: add view_is_related()

---

include/view-impl-common.h
src/view-impl-common.c
src/xdg.c
src/xwayland.c

The `unmap()` handlers should only call `desktop_focus_topmost_view()` if the unmapped view was the focused view. Unmapping a view that was not focused should not change the focus.
I expect this rarely had any effect in practice; it would only matter in a focus-follows-mouse config where some view other than the one on top was focused. But it still seems better to fix.
Rather than repeating the logic in two places, create a small `view_impl_unmap()` helper. Perhaps more common "unmap" logic could be moved there in future.

view: only focus topmost view if unmapped view was focused

---

include/labwc.h
src/desktop.c
src/seat.c
src/session-lock.c

We were checking for a locked session in `desktop_focus_view()`, but there are several other call sites of `seat_focus_surface()` which were missing such a check. Any one of those could cause the lock screen to lose focus (making the session impossible to unlock) or another surface to gain it (breaching the session lock).
To fix the issue, make any call to `seat_focus_surface()` no-op when the session is locked. Add a specific `seat_focus_lock_surface()` function which is the only way to bypass the check and is called only from session-lock.c.
This should fix #1166, but more eyes on this code are very much appreciated.

seat: move session-lock check down to seat_focus() level

---

include/view.h
src/desktop.c
src/view.c
src/xwayland.c

Commit 7e72bf975fb6 changed behavior to not automatically focus xwayland views using the "Globally Active" input model (WM_HINTS.inputs = false but WM_TAKE_FOCUS listed in WM_PROTOCOLS).
One undesired side effect of this change is that when a dialog is closed, the parent window is not re-focused if "Globally Active". This issue is seen for example with JDownloader. It can be solved taking a similar approach to what is done for unmanaged xwayland views: allow automatic re-focus between views sharing the same PID.
Note that it's difficult to completely solve all of the focus issues with Globally Active views without proper WM_TAKE_FOCUS support. Implementing proper support is difficult since it requires wlroots changes and would also mean waiting for a message round-trip in …

desktop: allow re-focus between "globally active" views of the same PID

---

src/xwayland.c

Assume that Globally Active xwayland views do want focus if they want window decorations (according to `_MOTIF_WM_HINTS`). This is a stop-gap fix to ensure that various applications (mainly Java-based ones such as IntelliJ IDEA) get focus normally and appear in the window switcher. It would be better to match based on `_NET_WM_WINDOW_TYPE` instead, but that property isn't currently available through wlroots API.
Fixes (partially): 7e72bf975fb65c8290b398d21b2ad9d87a22880f
("view/xwayland: avoid focusing views that don't want focus")
Fixes #1167 for the application mentioned (JDownloader) as well as IntelliJ IDEA. If there are X11 applications that use the Globally Active model + have client-side decorations + want normal focus (e.g. to appear in Alt-Tab), this won't help with those.

xwayland: assume views wanting decorations also want focus

---

src/xdg.c
src/xwayland.c

When a parent view has multiple sub-views (dialogs) visible, focusing one sub-view ought to raise it above the others. This doesn't currently happen -- focusing a sub-view raises the whole group of views together, but has no effect on the relative stacking order between them.
I thought I saw an issue ticket for this recently, but I can't find it now.
Anyway, this seems like a simple oversight in the `view->impl->move_to_front()` functions that's pretty easy to fix. `move_to_back()` appears to need similar logic, so add it there too.
Tested with HomeBank: the Import dialog pops up an additional Open File dialog, which before this change appears behind the Import dialog (and clicking on it does not raise it to the front). After this change, the Open File dialog appears in front as expected. …

view: raise/lower sub-view correctly relative to other sub-views

---

include/view.h
src/view.c
src/xwayland.c

X11 clients may request to be initially fullscreen or maximized by setting hints in the _NET_WM_STATE property. For some reason, we are currently only honoring fullscreen requests but not maximize.
The fixes issues with GTK apps (notably Firefox, but others as well) not starting maximized. (Qt apps seem to send a separate maximize request and weren't affected.)
Additionally (2nd commit), for views that are initially maximized or fullscreen and have no explicitly specified position, we need to center the stored natural geometry, or the view may end up partially offscreen once unmaximized/unfullscreened.

xwayland: fix some issues with initially maximized GTK apps

---

docs/environment
src/config/session.c

...to avoid users copying this file to ~/.config/labwc/ without editing it and ending up with Swedish keyboard layout (which has been reported by users more than once!)

docs/environment: comment out variables

---

docs/labwc-actions.5.scd
include/labwc.h
include/snap.h
include/view.h
src/action.c
src/meson.build
src/output.c
src/snap.c
src/view.c

I have been following your work for quite a while now (nice project, thanks a lot!), as I'm still stuck in X11 with openbox. For me there's just some small features which I'm painfully missing in order to control my window manager using the keyboard only.
A very common use case is to open a terminal "W-t", then align it to some other terminal using "W-arrow".
My rc.xml for this:
```
<keybind key="W-Left">
<action name="MoveToEdge" direction="left" snap="window"/>
</keybind>
<keybind key="W-Right">
<action name="MoveToEdge" direction="right" snap="window"/>
</keybind>
<keybind key="W-Up">
<action name="MoveToEdge" direction="up" snap="window"/>
</keybind>
<keybind key="W-Down">
<action name="MoveToEdge" direction="down" snap="window"/>
</keybind>
```
In addition to that, I want to align …

Allow snap to window in MoveToEdge; Add GrowToEdge, ShrinkToEdge

---

include/common/scaled_font_buffer.h
include/common/scaled_scene_buffer.h
src/common/scaled_font_buffer.c
src/common/scaled_scene_buffer.c

In preparation to also use the scaled_scene_buffer for theme components like rounded corner images and button icons.

scaled_scene_buffer: make dropping the buffer optional

---

include/labwc.h
src/server.c
src/xdg.c

...to have the event-handler functions in the same translation unit as the signal connector.

xdg: add xdg_shell_init()

---

CONTRIBUTING.md
include/common/macros.h
include/labwc.h
include/ssd-internal.h
include/xwayland.h
scripts/checkpatch.pl
src/action.c
src/config/rcxml.c
src/cursor.c
src/layers.c
src/output.c
src/ssd/resize_indicator.c
src/theme.c
src/view.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c

@Consolatis mentioned this as an idea in #814. It seems worth pursuing to me, since it makes the code a bit more readable IMHO (and forces us to be consistent with event handler function names).
No functional change.

view: macro-ize signal/listener connection

---

include/view-impl-common.h
src/view-impl-common.c
src/view.c
src/xdg.c
src/xwayland.c

The logic was the same for xdg-shell and xwayland views, so move it from the `view->impl` layer out to the `view_move_to_front/back()` functions.
`view->impl->move_to_front/back()` still exist for now, in case we want to add xdg/xwayland-specific logic in future, but they now move only one view and not sub-views.
Follow-up to #1181.

view: commonize sub-view logic in view_move_to_front/back()

---

src/regions.c

Add percentages (x + width, y + height) before scaling so that there is no gap between regions due to rounding variations.
I have a strong hunch this will fix #1169. Not tested though.

regions: perform rounding more carefully

---

include/labwc.h
src/view-impl-common.c
src/view.c
src/xwayland.c

Currently xwayland views are restacked on top of the XWayland server stacking order when activated (i.e. focused). This is wrong because focus/raise are independent concepts (though often occurring together). The stacking order should be updated when the view is raised/lowered, not when the view is focused.
Work is in progress elsewhere (#1142) that will result in views more often being raised without being focused. Without this fix, those views don't get restacked properly, resulting in clicks "passing through" to views underneath.
The first commit, on its own, fixes the issue but has a side effect of increasing our traffic to the X server a bit. The second commit ("view: avoid raising same view over and over") is an optimization to reduce that traffic a bit.

xwayland: update stacking order in move_to_front/back()

---

src/common/spawn.c

See the following issue for further information:
- #1209
Reported-by: @bdantas

src/common/spawn.c: Restore SIGPIPE default handler before exec

---

include/view.h

The type enum view_edge used to be defined in a .c file, so a structure member 'tiled' in struct view had to be defined to use another type.
Later (2023-08-02, commit 1ee8715) the definition of enum view_edge was moved to view.h, so now 'tiled' can be defined to use that type.

view.h: changed the type of tiled in struct view to enum view_edge

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/input/keyboard.h
include/labwc.h
include/view.h
src/config/rcxml.c
src/input/keyboard.c
src/view.c

Fixes
- #1076
Windows remember their last configured keyboard layout and restore that layout when getting focus.
New windows will use the default layout. Can be tested via something like this in `~/.config/labwc/environment` and pressing the "menu" key:
```
XKB_DEFAULT_LAYOUT=de,us
XKB_DEFAULT_OPTIONS=grp:menu_toggle,grp_led:scroll
```
Also requires enabling the feature in the first place:
```xml
<keyboard layoutScope="window">
..
</keyboard>
```
Missing:

keyboard: allow applying keyboard layout per window

---

include/view.h
src/view.c
src/xwayland.c

The `top_left_edge_boundary_check()` function in xwayland.c ensures that views trying to position themselves at 0,0 don't end up with a titlebar offscreen. However, it doesn't take into account the usable area and thus these views can still end up overlapping a top panel.
Also, there is no good reason for `top_left_edge_boundary_check()` to be xwayland-specific. This logic should really be part of `view_adjust_for_layout_change()`.
To fix all this, add a new `view_adjust_floating_geometry()` function, which replaces the existing similar (and duplicated) logic in `view_apply_natural_geometry()` and `view_adjust_for_layout_change()`.
`view_adjust_for_layout_change()` is already being called from xwayland's `set_initial_position()`, so `top_left_edge_boundary_check()` is now redundant and …

view: ensure that floating views don't overlap top panels

---

docs/labwc-actions.5.scd
src/action.c

...to enable unfocusing currently focused window on desktop click.
Works with:
```
<mouse>
<default />
<context name="Root">
<mousebind button="Left" action="Press">
<action name="Unfocus" />
</mousebind>
</context>
</mouse>
```
Fixes: #1230

Add unfocus action

---

include/view.h
src/action.c
src/interactive.c
src/view.c

In current implementation, window snapping triggered with mouse has some counter-intuitive behaviors in my (vertically aligned) dual monitor setup:
(a) Cannot snap a tiled window into another output
(b) Dragging a tiled window into another output forces snapping (related to (a))
(c) Snapping is triggered when the center of the window is in another output, even if the cursor is not on the edge.
(d) Snapping a tiled window to the same direction moves the window into the adjacent output and inverts its direction (mentioned in ![comment](https://github.com/labwc/labwc/blob/d2bcb94bae336c5ce9eb53e87c0cdfe1218d7733/src/view.c#L1379))
(a)-(c) occur because the cursor position relative to the output **the view belongs to** is used to determine if and in which direction the snapping is triggered. …

interactive: Make window snapping with mouse more intuitive

---

src/input/keyboard.c

Remove wlr_seat_set_keyboard() from `keyboard_modifiers_notify()` but leave it in `keyboard_key_notify()`
Fixes regression introduced in 984aeb0
Reported-by: @jlindgren90
Fixes: #1238

keyboard: fix shifted keystroke delay

---

include/input/key-state.h
src/input/key-state.c
src/input/keyboard.c

For discussion/consideration along with #1212 (not mutually exclusive) for solving #1208.
Before commit e77330bc3fe7, there were issues with keys becoming "stuck" if other keys were pressed at the time a keybinding was matched, because those other keys were included in the "bound" set and the release events were incorrectly eaten by labwc.
Commit e77330bc3fe7 solved that issue with the "big hammer" approach of preventing keybindings from working at all if other keys were pressed:
if (key_state_nr_pressed_keys() > 1) {
return false;
}
This is an alternate approach to solving the original problem, by (1) not including those other keys in the "bound" set and (2) making sure we always forward release events for un-bound keys to clients (even if a menu or OSD is displayed).
Details:
- Since we …

keyboard: avoid stuck keys due to keybindings (alternate approach)

---

include/common/array.h
include/view.h
include/xwayland.h
scripts/checkpatch.pl
src/view.c
src/workspaces.c
src/xwayland.c

Until we expose the workspaces to xwayland we need a way to
ensure that xwayland views on the current workspace are always
stacked above xwayland views on other workspaces.
If we fail to do so, issues arise in scenarios where we change
the mouse focus but do not change the (xwayland) stacking order.
Reproducer:
- If followMouse is enabled, raiseOnFocus must be disabled
- Open at least two xwayland windows which allow scrolling
(some X11 terminal with `man man` for example)
- Switch to another workspace, open another xwayland window
which allows scrolling and maximize it
- Switch back to the previous workspace with the two windows
- Move the mouse to the xwayland window that does <b>not</b> have
focus
- Start scrolling
- All scroll events should end up on the maximized window on
the other …

Keep xwayland stacking order in sync when switching workspaces

---

src/xwayland.c

Reproduce issue by:
1. Run an XWayland client
2. ToggleDecorations twice to hide deco
3. Minimize/unminimize from panel
4. Observe that deco is back
Reported-by: @Consolatis

xwayland: do not re-set deocrations on unminimize

---

.github/workflows/build.yml
include/common/scene-helpers.h
include/labwc.h
include/view.h
include/xwayland.h
meson.build
src/common/scene-helpers.c
src/decorations/kde-deco.c
src/decorations/xdg-deco.c
src/desktop.c
src/dnd.c
src/idle.c
src/input/cursor.c
src/input/keyboard.c
src/layers.c
src/output.c
src/server.c
src/session-lock.c
src/view.c
src/xdg-popup.c
src/xdg.c
src/xwayland-unmanaged.c
src/xwayland.c
subprojects/wlroots.wrap

This is a set of changes required to build with wlroots `master` / 0.17.0-dev (labwc `master` currently uses wlroots 0.16.x).
Perhaps it will be useful to other wanting to use wlroots-git. I plan to update/rebase it as further breaking changes are made on the wlroots side.

Update for wlroots 0.17

---

include/xwayland.h
src/output.c
src/xwayland.c

XWayland clients use the _NET_WORKAREA root window property to determine how much of the screen is not covered by panels/docks. The property is used for example by Qt to determine areas of the screen that popup menus should not overlap (see `QScreen::availableVirtualGeometry`).
Depends on wlroots MR (merged for 0.17):
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4406

xwayland: set _NET_WORKAREA property based on usable area

---

docs/themerc
src/theme.c

The current light gray color is very very very close to the pavucontrol notebook header color, but not enough for "seamless" appearance.
Before:
After:

Use the GTK+ 3 notebook header color as the default active title color

---

include/view.h
include/xwayland.h
src/interactive.c
src/output.c
src/view.c
src/xwayland.c

Account for space taken up by XWayland panels (as indicated by the
_NET_WM_STRUT_PARTIAL property) in the `usable_area` calculation.
This makes it possible to use labwc in a "transitional" setup, where it
replaces the X11 window manager and compositor, but most other parts of
a existing X11 desktop environment can still be used via XWayland.
(Some remaining drawbacks of such a setup would be the lack of desktop
icons, and native Wayland clients not showing up in X11-based taskbars.)
This is a draft because:
- it depends on a change to wlroots, something like https://github.com/jlindgren90/wlroots/commit/b8055330159b86d5e88d01596a16fc1a44361c97.
- I'm looking for feedback on whether this is useful to anyone else besides me.
The first commit, however, could be merged on its own (without any …

output,xwayland: Add support for _NET_WM_STRUT_PARTIAL

---

src/input/keyboard.c

All non-modifier keys cycle forward in the cycle view OSD which makes sense for e.g. tab but is not very intuitive for arrow-up or arrow-left. Handle those keys separately to provide a feel of navigation by arrow keys in the cycle view.
Sometimes I need a while to find the window in the OSD I want to focus to. Being used to navigate by arrow keys, I got slightly confused that both arrow-down and arrow-up cycle forward. This patch proposes to allow cycling backwards also by arrow-up or arrow-left, next to shift + any-key.
PS: This is no 0.6.6 material imho.

keyboard: allow back by arrow-up or arrow-left in cycle view OSD

---

src/output.c

Prevent carrying around the wlr_output->data pointer when destroying an output. The set_gamma handler may be called during the destruction of a wlr_output after our own destroy handler has already been called. This patch resets the wlr_output->data pointer in our destroy handler and adds a check in the set_gamma handler to verify the output is actually valid.
Fixes
- #1270
Reported-by: @Flrian

src/output.c: ensure we don't carry around a stale output pointer

---

include/labwc.h
protocols/meson.build
src/input/cursor.c

This protocol allows Wayland clients to request a buffer for a cursor shape from a compositor.
Tested with foot.

[WIP] Implement cursor-shape-v1 protocol

---

docs/labwc-theme.5.scd
include/button/button-xbm.h
include/ssd-internal.h
include/theme.h
src/button/button-xbm.c
src/ssd/ssd_part.c
src/ssd/ssd_titlebar.c
src/theme.c

I don't know if this is of interest, but I have been working with labwc on a system which used to run Openbox, and I have noticed a couple of features which Openbox has which are not implemented in labwc.
1) The window header bar button icon for "maximize" is only used on non-maximized windows; on windows which are already maximized, a different "restore" icon is shown.
2) Mouse pointer hover over a window header bar button is shown by a subtle change in the icon which is displayed, usually a slight increase in size.
Neither of these appear to be implemented in labwc at present, and their absence is noticeable when moving from Openbox. This PR implements both, allowing a "hover" icon to be supplied in the theme for each button, and allowing a "restore" icon to be defined for the maximize …

Add features to make window header icons more like those in Openbox

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/ssd/ssd_titlebar.c
src/theme.c

Thanks you @Consolatis for the help of how to implement it.
Is the scope repo automatically updated or should I do it?
It works:

feat: implement <font place="InactiveWindow"> (ref scope: 2.4.7)

---

src/layers.c

Previously we would only do that for the bottom layer.
Fixes
- #1293
Reported-by: @spl237

src/layers.c: move popups from the background layer to the top layer

---

src/output.c

...to just call wlr_scene_output_commit() as was previously the case and thus avoid freezing screens reported by a number of users.
Fixes: #1273

Partially revert ddc9047

---

docs/labwc-config.5.scd

...to include that it is a workaround which is usually not required.

labwc-config(5): update <margin> description

---

docs/labwc-actions.5.scd
include/labwc.h
src/action.c
src/output.c
src/server.c

It is now possible to use keybinds to add and remove virtual outputs (also called headless backend in wlroots terminology).
Closes #1279 
Thanks to @Consolatis for original PoC patch and guidance!

Implement key binds to control virtual outputs

---

docs/labwc-theme.5.scd
src/theme.c

- make button array definition easier to read
- use `max_toggled_hover` with `max_hover_toggled` the alternative
- do not support svg+png icons in max_hover_toggled format
Will wait until this is reviewed/merged and then move onto refactoring `button_xbm_load()` and sort out the fallback regression.
Will try to weave #1296 into it at that point.
Cc @spl237 - for awareness

Icon refactoring

---

src/output.c

This should make gcc with -march=native happy.
Closes #1307

Fix strncpy warning

---

docs/labwc-theme.5.scd

For general consistency and better readability as source.

docs/labwc-theme.5.scd: made text fit in max 80-column wide lines

---

CONTRIBUTING.md

Fixes "WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.", plus use `meson compile -C build/` like in README.md instead of `ninja -C build/`

CONTRIBUTING.md: update deprecated meson command

---

src/input/cursor.c

When assertions are disabled, providing an unexpected input to cursor_get_from_edge will cause the non-void function to terminate without a return value. This may be effectively unreachable in practice. However, returning a default cursor as a fall-through case will both silence a compiler warning and prevent catastrophy should the function ever be called with a permitted value.

fix: fall-through to default cursor in cursor_get_from_edge()

---

src/output.c

Fixes an assertion failure that occurred if reconfiguring outputs after an output had been disabled using `wlopm --off`.
Fixes: #1303

output: do not call wlr_scene_output_layout_add_output() twice

---

include/button/button-xbm.h
include/common/graphic-helpers.h
include/common/string-helpers.h
include/theme.h
src/buffer.c
src/button/button-xbm.c
src/common/graphic-helpers.c
src/common/string-helpers.c
src/ssd/ssd_titlebar.c
src/theme.c

- Remove builtin bitmap fallbacks for `_hover` icons
- For `_hover` buttons with an xbm/svg/png, just copy the non-hover variant and add an overlay
- Simplify `button_xbm_load()` by moving some of the fallback logic to `theme.c`

Icon refactoring4

---

src/xwayland.c

There are situations where the data pointer of a parent is NULL. Checking for NULL first fixes e.g. a segmentation fault in CLion when opening the settings window from a popup menu.
See also https://github.com/labwc/labwc/issues/1351#issuecomment-1867475324
Closes https://github.com/labwc/labwc/issues/1351

xwayland: Prevents usage of invalid data pointer

---

NEWS.md

The `s` is not needed.
From https://www.jetbrains.com/clion/

NEWS.md: Fix typo

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/placement.h
include/view.h
src/config/rcxml.c
src/meson.build
src/placement.c
src/view.c
src/xdg.c
src/xwayland.c

With under-cursor placement, new top-level windows will be centered under the cursor rather than centered on the active view. This works for xdg-shell and xwayland windows.
Currently, this tyep of placement can be faked with window rules:
```xml
<windowRule identifier="*">
<action name="MoveToCursor" />
</windowRule>
```
However, this has two drawbacks:
1. Child views of other windows (*e.g.*, dialogs) will open under the cursor instead of centered on their parent (which seems like a better placement for these views); and
2. The action defined by the rule will override preferred placement, which means that things like `xclock -geometry -0-0` will ignore the desired geometry.
Because the new `view_place_initial` just uses the `view_move_to_cursor` action, it takes a couple of actions …

Add "under-cursor" and "automatic" placement strategies

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/osd.c

It is now possible to specify whether to show full application identifier or the trimmed variant in window switcher OSD.
Closes #1073

Option to show full app_id in window switcher

---

include/input/cursor.h
include/input/drawing_tablet.h
src/input/cursor.c
src/input/drawing_tablet.c
src/input/meson.build
src/seat.c

This PR adds initial support for cursor emulation with a graphics tablet (https://github.com/labwc/labwc/issues/1060). No configuration options (yet), just mapping all of the tablet surface to the output area with a fixed button mapping.
All commits are based on @Consolatis  work from https://github.com/labwc/labwc/issues/1060#issuecomment-1786384495 and all findings in https://github.com/labwc/labwc/issues/1060 The commits have a co-author assigned.
I'm using this code for a week now (with https://github.com/labwc/labwc/issues/1060#issuecomment-1826875020 op top of it) and haven't noticed any issues.

Initial graphics tablet support

---

docs/labwc-actions.5.scd
docs/rc.xml.all
src/action.c

The AutoPlace action will apply `placement_find_best()` to an active view, moving it to a position on its output that will minimize overlap with other views. This may be useful interactively to rearrange windows, but is particularly useful when chained with a `ResizeTo` action in a window rule: the initial placement, when "automatic" is selected, will optimize for a size that is then immediately changed; a follow-up `AutoPlace` action can ensure that the new window size will not push the window off the screen.

feat: add "AutoPlace" action

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/libinput.h
src/config/libinput.c
src/config/rcxml.c
src/seat.c

It is nice to have finer granularity for device types to allow for configurations such as using `naturalScroll` on touchpads, but not on regular pointer devices such as mice.

Add `touchpad` device type

---

.github/workflows/build.yml
scripts/helper/.gitignore

...to search for functions which have been banned from our code base, because they're too easy to misuse, and even if used correctly, complicate audits, cause inconsistencies and/or make static analysis harder.

ci: include scripts/find-banned.sh

---

docs/rc.xml.all
include/config/rcxml.h
include/config/tablet.h
include/input/tablet.h
src/config/meson.build
src/config/rcxml.c
src/config/tablet.c
src/input/drawing_tablet.c
src/input/meson.build
src/input/tablet.c
src/seat.c

This PR allows to configure the tablet pen buttons, thus which pen button emulates which mouse button.
Same as the earlier tablet PR, this one is also based on @Consolatis work in https://github.com/labwc/labwc/issues/1060#issuecomment-1786384495
I also added a rename in the last commit for consistency.

feat: Add tablet button mapping configuration

---

include/placement.h
src/action.c
src/placement.c
src/view.c

The `view_adjust_floating_geometry` function is called when un-maximizing a window or changing the output layout to ensure that views are well placed. Rather than always centering these views should they fall offscren, use the automatic placement strategy if so configured.
This alters the interface of `placement_find_best` to support passing an arbitrary geometry, because we wish to pass either `view->natural_geometry` or `view->pending`, depending on the reason for the placement.

view: honor automatic placement when adjusting floating geometry

---

docs/rc.xml.all
include/config/rcxml.h
include/config/tablet.h
src/config/rcxml.c
src/config/tablet.c
src/input/tablet.c

This PR allow to specify the responsive/active area of the tablet. The Wacom driver on Windows allows something similar, see e.g. https://101.wacom.com/UserHelp/en/PenMode.htm
I'm using this to truncate the active area so that the resulting aspect ratio matches the one from my monitor. Initially i had something like this https://github.com/labwc/labwc/issues/1060#issuecomment-1826875020 in mind, but accessing the output turned out rather tricky on startup and actually this approach here is much more flexible.
This is the last PR from me for anything with tablet cursor movement (for now) ;)

feat: Add active tablet area specification

---

docs/rc.xml.all
include/input/tablet.h
include/input/tablet_pad.h
src/config/tablet.c
src/input/meson.build
src/input/tablet.c
src/input/tablet_pad.c
src/seat.c

This PR wires the tablet pad and lets you map tablet pad buttons to mouse buttons. This is probably not the most important feature but a good stepping stone to bind actions to pad and stylus buttons, like the  mouse-bindings.
@Consolatis did also some work in his branch here https://github.com/labwc/labwc/issues/1060#issuecomment-1786384495 for that. That said, i guess adding mouse-like bindings needs some thinking up front, so I prefer to just open an issue for that after this PR to have a place to collect all thoughts.
I haven't found any `const`'s for the  pad buttons in wlroots. Please let know if you prefer to define our own `const`'s instead of using directly `0x0` etc.

feat: Add initial tablet pad button mappings

---

src/theme.c

src/theme.c: fix loading of alt_name hover icon

---

src/output.c
src/view.c

Issue was found that in some situations adaptive sync does not get disabled when it should when exiting fullscreen. This fixes it.

fix adaptive sync fullscreen

---

include/view.h
src/interactive.c
src/view.c

If a view's output disappears during a layout change, its original geometry will be captured as last_layout_geometry, which will remain valid unless the view's natural geometry is modified. If a subsequent layout change adds an output closer to a valid last_layout_geometry, the view will be relocated to that output.
The intent of this change is to more gracefully handle cases like `wlopm --off` and a subsequent `wlopm --on` which, at least on some multihead `amdgpu` setups, will send disconnect events that will trigger labwc to coalesce all views onto the last display to be disconnected. However, it also allows one to connect an external display to a laptop, put some windows there, remove the display and have them coalesce on the internal display, and then reattach the display and have …

view: try to honor original geometry with layout changes

---

docs/labwc-config.5.scd
include/config/tablet.h
src/config/mousebind.c
src/config/rcxml.c
src/config/tablet.c

This allows those other mouse buttons (from https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L355 ) to be bound and also makes more buttons available to map to from tablet pen/pad buttons.
(Since I have only 4 buttons on my pad, this absolutely sufficient for me)
Also drop one method in favor of reuse.
Closes https://github.com/labwc/labwc/issues/1404 if we want to restrict tablets to pure mouse emulations (which i think is just fine).

feat: add more mouse button definitions

---

docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/labwc.h
include/view.h
protocols/meson.build
src/action.c
src/config/rcxml.c
src/meson.build
src/output.c
src/server.c
src/tearing.c
src/view.c

This adds allowTearing option. `<allowTearing>yes</allowTearing>` will enable tearing support. Also adds action ToggleTearing that can be used to enable it for windows that don't request tearing.
I decided to make it check if WLR_DRM_NO_ATOMIC is set to 1, and disable tearing otherwise, as currently that is required for it to work. That check can be removed later when we get support for atomic tearing page flips.

Tearing support

---

src/config/rcxml.c

Also elevate warning about this variable to an error when tearing is configured, because presumably the user expects the tearing setting to work.
h/t: IRC user Domo

rcxml: avoid crash when checking environment for WLR_DRM_NO_ATOMIC

---

src/view.c
src/xwayland.c

Calling the new `view_constrain_size_to_that_of_usable_area` has some unexpected side-effects for multi-output configurations. In particular, setting `box.x = view->pending.x` and `box.y = view->pending.y` before any placement is selected most likely sets them each to zero. Then, calling `view_move_resize` seems to (eventually) trigger `view_discover_output`, which will override any `view->output` set in, *e.g.*, `xdg_toplevel_view_map` to be the output nearest the cursor. The end result is that, in `center` or `automatic` placement modes, the call to `view_constrain_size_to_that_of_usable_area` will force new windows to always appear on the display at (0, 0), regardless of where the cursor is.
To fix this, I've made a couple of changes to `view_constrain_size_to_that_of_usable_area`:
1. …

view, xwayland: fixes for new size constraints

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
include/input/tablet.h
include/input/tablet_pad.h
include/labwc.h
src/config/rcxml.c
src/output.c
src/seat.c

This PR adds a configuration option to map a tablet surface to a single output in a multi-monitor setup. I've tested a lot of tablet/monitor hot-plug/reconfigure scenarios, so functionality-wise, this seems fine to me.
Please let me know what you think. I've also added a few formatting improvements from my earlier PRs.
PS: Last tablet feature PR from me, no more features missing in my opinion after this one ;) 
Closes https://github.com/labwc/labwc/issues/1405

feat: add tablet output mapping

---

src/input/cursor.c
src/input/keyboard.c
src/menu/menu.c

...and call actions after closing menus so that virtual keyboard input caused by actions are sent to the surface with keyboard-focus rather than being consumed by the open menu.
Fixes: #1366

menu: run actions on button release

---

src/view.c

To reproduce:
Open mpv on a short video; full-screen mpv; minimize it with a hotkey. When the minimized full-screen window closes, labwc always crashes.
Backtrace:
```
Thread 1 "labwc" received signal SIGSEGV, Segmentation fault.
matches_criteria (view=0x555556524fb0, criteria=(LAB_VIEW_CRITERIA_CURRENT_WORKSPACE | LAB_VIEW_CRITERIA_FULLSCREEN)) at ../src/view.c:95
95			if (view->scene_tree->node.parent
#0  matches_criteria (view=0x555556524fb0, criteria=(LAB_VIEW_CRITERIA_CURRENT_WORKSPACE | LAB_VIEW_CRITERIA_FULLSCREEN)) at ../src/view.c:95
server = 0x7fffffffc8b0
#1  0x00005555555741cb in view_next (head=0x7fffffffd9b0, view=0x555556524fb0, criteria=(LAB_VIEW_CRITERIA_CURRENT_WORKSPACE | LAB_VIEW_CRITERIA_FULLSCREEN)) at ../src/view.c:134
__PRETTY_FUNCTION__ = "view_next"
elm = …
```

Fix crash when a minimized fullscreen window closes

---

CONTRIBUTING.md
docs/labwc-actions.5.scd
docs/labwc-config.5.scd
docs/labwc-menu.5.scd
docs/labwc-theme.5.scd
docs/labwc.1.scd
docs/rc.xml.all

- typos: LINGUAS manually, rest with help of aspell(1)
- whitespace: some trailing spaces/tabs, one utf-8 NBSP (#xC2 #xA0)
- made most text in docs/ fit in max 80-column wide lines
- consistent trailing periods in sentences in labwc-actions.5.scd and labwc-config.5.scd; labwc-theme.5.scd had different consistency, changed it follow these other files with sentence-ending periods
- and ", respectively" (comma often used to separate)

Fixed some typos, whitespace, periods, 80-column lines

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/seat.c

From https://github.com/labwc/labwc/issues/1422
This adds a `<touch mapToOutput="" />` switch to the configuration, similar like the switch for `tablet`. This switch allows to override the linked output name from a touch device.
I don't have suitable hardware, so this needs validation from somebody else...
~Also no docs yet.~

feat: touch output mapping

---

docs/labwc-config.5.scd
docs/labwc-theme.5.scd
docs/labwc.1.scd
include/common/dir.h
include/config/rcxml.h
include/config/session.h
src/button/button-png.c
src/button/button-svg.c
src/button/button-xbm.c
src/button/common.c
src/common/dir.c
src/config/rcxml.c
src/config/session.c
src/main.c
src/menu/menu.c
src/server.c
src/theme.c

Instead of caching global config/theme directories, create lists of paths (e.g. '/home/foo/.config/labwc/rc.xml', '/etc/xdg/labwc/rc.xml', etc). This gives the flexibility to iterate forwards or backwards depending on if a config merge is wanted.
It also enables better fallback, for example if a particular theme does not exist in $HOME/.local/share/themes, it can be searched for in ~/.themes/ and so on.
This has the added benefit of using `fopen()` only and avoid the additional `stat()` in most situations.
~~Note: This only half-finished, so just pushing to share the idea. The for-loops in rcxml.c and menu.c use the new approach.~~
Related-to: #1411
@spl237 @ahesford Appreciate thoughts on alternative approach to #1411 
It's a bit bit rushed and only half-finished, but gives an idea of …

config: refactor config/theme directories handling

---

include/input/keyboard.h
src/input/input.c
src/input/keyboard.c
src/seat.c
src/server.c

If keyboard-layout-per-toplevel-window is used, reset the group (index) for each window on --reconfigure whenever XKB_DEFAULT_LAYOUT has changed.
Refactor to use a common configure function for reconfigure and keyboard-group creation.
Co-authored-by: @johanmalm
Fixes #1407

keyboard: set keyboard layout on reconfigure

---

src/view.c

...on view destruction because focus_change_notify() in seat.c changes server->active_view so the logic introduced by 6c6e406 (which checks if view =! active_view) is no longer right.
The glitches described in the commit below have not come back. https://github.com/labwc/labwc/commit/6c6e406507bfb0e9a809b74029b5b05b5a095768
Fixes #1393
@jlindgren90 - This relates to a couple of separate commits from you, so if you've got time, your eyes on this would helpful. Don't worry if you can't, I think the change is fine.

view: fix regression whereby cursor is not updated

---

docs/labwc-config.5.scd
docs/rc.xml.all
include/config/rcxml.h
src/config/rcxml.c
src/input/cursor.c
src/resistance.c

This includes a general refactor of the resistance logic as well as re-use of the major components to allow resistance to apply to window edges in addition to screen edges. Moving behavior seems to be correct, but there are still a couple of bugs with resizing:

resistance: add window-edge resistance for interactive moves/resizes

---

docs/labwc-actions.5.scd
include/view.h
src/action.c
src/view.c
src/xdg.c
src/xwayland.c

As a follow up to https://github.com/labwc/labwc/discussions/1374#discussioncomment-8070782 I wanted to give "~Send~MoveToOutput" another try.
~I guess I'm quite close but I need some hints how to  finish. Playing with it, my code seems to work for snapped and tiled windows,  but I fail at floating windows. What I had in mind was just moving a floating window to the other output and then position it like it was newly started, thus placed and resized according to placement policy (centered or natural). But somehow I haven't found the correct functions for that. Any hints?~

feat: move / fit to output action

---

src/interactive.c

This also fixes a bug wherein dragging a window and pressing a hot-key to maximize or fullscreen a window could leave a snap-region highlight visible after the interactive move was canceled.
To reproduce the issue, define an arbitrary snap region and assign a keybind like `W-f`, that will fullscreen a window. The `Super` key also causes regions to be highlighted during interactive moves, so start dragging a window, press and hold `Super` to highlight the snap region, and press `f` to fullscreen the window. Release the mouse button and press the `W-f` keybind to bring the window out of fullscreen. The snap region will still be highlighted until another interactive move triggers it to disappear.

interactive: unify interactive_{cancel,finish} where possible

---

include/labwc.h
src/output.c

Only tested nested.
Also exposed the test routine to clients while at it, `wlr-randr --dryrun` can be used to verify if it works.
We were previously completely ignoring the `test` signal which requires compositors to destroy the supplied config object. As we handle it now this also fixes a memory leak.
Should fix
- #1458
even without the wlroots patch applied.

Implement proper output configuration test and expose it to clients
