labwc/labwc

- include/labwc.h
- meson.build
- src/menu/menu.c
- src/output.c
- src/server.c
- src/view.c
- src/xbm/xbm.c
- src/xdg.c
> Unbreak build with wlroots 0.13.0 (master snapshot)

- src/xdg.c
6744e103014b bumped wlroots to 0.14.0 (unreleased) which recently got a breaking change.
> Unbreak build with wlroots 0.14.0 (2021-06-03 snapshot)

- include/labwc.h
- src/cursor.c
This addresses #47 
What I've done
* uncommented the commented code in cursor.c
* added the required field to `struct seat`
* implemented request_set_primary_selection_notify, based on request_set_selection_notify
* added a header file
inspiration taken from https://github.com/swaywm/sway/pull/3240/  :-)
> add support for primary selection

- include/labwc.h
- protocols/meson.build
- protocols/wlr-input-inhibitor-unstable-v1.xml
- src/cursor.c
- src/desktop.c
- src/keyboard.c
- src/server.c
this is in "it appears to work" state, though I blindly copy-pasted a little more code[*] than I'm happy with, so might benefit from a review
[*] from here: https://github.com/swaywm/wlroots/pull/807
> implement input_inhibit protocol, needed for swaylock

- docs/rc.xml.all
> rc.xml.all: Fix typo

- src/xdg.c
> xdg: updates from wlroots master

- include/labwc.h
- src/cursor.c
- src/output.c
- src/xdg.c
I have tested this using Firefox for Wayland, and it works as expected. The only problem I have encountered was that in creating a new Firefox window, I would need to drag right or down, because dragging left or up wouldn't spawn a new window.
> Basic drag and drop support

- docs/labwc-menu.5.scd
This is in line with 1a38cc8 and #109
> docs/labwc-menu.5.scd: fix menu definition

- include/labwc.h
- src/output.c
- src/server.c
Chase https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3349
> Unbreak build with wlroots 0.15.0 (2021-11-19 snapshot)

- include/labwc.h
- src/cursor.c
- src/keyboard.c
- src/seat.c
I've tested this with swayidle and waybar's idle inhibitor.
Closes #108.
> Add support for basic idle and idle inhibitor protocols

- include/labwc.h
- src/output.c
- src/view.c
- src/xdg.c
- src/xwayland.c
Once it's done, this should close #105.
~~Scale menu and titlebar text~~
> Fix HiDPI scaling.

- src/server.c
avoid segfaulting sigint/sigterm handlers and drop an unused argument from sighup handler
> fix signal handlers

- src/cursor.c
Double clicks shouldn't be counted if their component "clicks" come from two different buttons, nor if their first click was itself the second click of a different double click.
> Be stricter about what counts as a double-click

- include/labwc.h
- src/foreign.c
This is used by taskbars like waybar.
> Implement foreign toplevel activate

- include/labwc.h
- src/cursor.c
- src/interactive.c
- src/xdg.c
- src/xwayland.c
Need to clean this up if it's our grabbed window!
Signed-off-by: Joshua Ashton <joshua@froggi.es>
> interactive: Fix crash if a window is destroyed while moving it

- include/labwc.h
- src/cursor.c
- src/keyboard.c
- src/seat.c
This is pretty straightforward plumbing but also includes some minor cursor/keyboard cleanups.
> Implement pointer gestures

- include/config/keybind.h
- src/config/keybind.c
That would require at least 3 people involved with all their fingers and two of them having an additional pen in the mouth.
Or just two if they are able to use their fingers and toes simultaneously.
> config/keybind.c: Don't overwrite the stack

- src/view.c
See discussion on issue #194 .
I tested and verified that:
- Disabling all outputs leaves maximized windows in their original location and no longer crashes `labwc`
- Disabling only one output correctly re-maximizes windows from that output onto a different output
Partially reverts commit ab07b68d7e888211e9ef5a3731f5272912d4b878.
> view: Handle maximized view on disabled output more simply

- src/config/rcxml.c
\+ Prevent leaking memory in those cases.
> config/rcxml: Prevent overwriting action argument

- docs/labwc-config.5.scd
> Add missing docs for mouse window snapping

- include/labwc.h
- src/cursor.c
Fixes #258 and #259
Reported-by: @ahmadraniri1994
Reported-by: @01micko
Suggested-by: @bi4k8
> Restore Drag mouse bindings and proper double click

- src/xwayland.c
> [v0.5] xwayland.c: Do not raise window if deactivating

- include/labwc.h
- src/output.c
- src/server.c
Needed for VR to work properly.
> output: Implement drm_lease_v1

- src/output.c
Also make sure we are only applying layout specific changes
once the output specific ones were committed successfully.
Fixes #312
Reported-By: @fakeczg
I only had a quick test with a single screen KMS/DRM setup and this specific issue can't be tested using a nested Wayland / X11 setup (these backends do not actually support disabling outputs at all).
So some more testing (especially with multiple screens) would be really appreciated: just some `wlr-randr --output HDMI-A --off` and `wlr-randr --output HDMI-A --on` cycles should be enough.
> src/output.c: Make sure we are always using the correct scene_node

- src/cursor.c
> [v0.5] cursor.c: make sure resize_edges is always assigned a value

- NEWS.md
- meson.build
- Synced NEWS.md from master
- Added NEWS.md entry for 0.5.2
- Changed version of meson.build to 0.5.2
- Rebased on top of branch v0.5
I think this is ready to "rebase and merge"
> [0.5] Prepare for release of 0.5.2

- README.md
> README: Document what is needed to run on NVIDIA

- include/common/scene-helpers.h
- src/common/scene-helpers.c
- src/cursor.c
- src/debug.c
- src/desktop.c
- src/ssd/ssd.c
- src/touch.c
- src/xwayland-unmanaged.c
- subprojects/wlroots.wrap
`meson subprojects update wlroots`
`WLR_SCENE_DEBUG_DAMAGE=highlight labwc -s foot` may actually come in handy for debugging in the future.
> Chase wlroots: wlr_scene_surface

- src/xdg-popup.c
- subprojects/wlroots.wrap
`meson subprojects update wlroots`
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3514
> Chase wlroots: xdg_popup.geometry

- src/xwayland.c
Some xwayland clients leave unmapped child views around, typically when a
dialog window is closed. Although handle_destroy() is not called for
these, we have to call foreign-toplevel-destroy to avoid panels and the
like incorrecly showing them.
> xwayland: call foreign-toplevel-destroy on unmap

- src/xwayland-unmanaged.c
Some tidying up:
- Remove some forgotten listeners on destroy
- Reduce logging noise
> Fix unmanaged

- src/debug.c
- src/layers.c
Fixes #369 
\+ random `src/debug.c` fix
> src/layers.c: Update output for popup after forced move

- src/layers.c
Currently if a surface with exclusive zone is created prior to regular
surfaces, the size of the exclusize zone does not affect the usable area
for regular surfaces. This for example results in notifications being
rendered over the statusbar.
This commit fixes the issue by handling the surfaces with exclusive
zones first.
Fixes #420.
> Fix usable area calculation

- src/view.c
This makes sure that applications starting in maximized of fullscreen
mode always have their `natural_geometry` set to sensible values.
Partly fixes #403
> src/view.c: Fall back to default geometry when changing state

- include/action.h
- include/config/keybind.h
- include/config/mousebind.h
- include/config/rcxml.h
- include/private/action.h
- src/action.c
- src/config/rcxml.c
- src/menu/menu.c
In preperation for Actions that require multiple arguments
> src/action.c: Convert action->arg to a list of action_arg

- .github/workflows/build.yml
Thanks to @keshto for adding the missing deps for the Void Linux musl runner
> CI: Fix Void Linux runner

- src/view.c
> src/view.c: Fix output handling with no outputs available

- .github/workflows/build.yml
Recommended since https://github.com/vmactions/freebsd-vm/compare/v0.2.1...v0.2.2
> CI: prevent FreeBSD breakage via auto-update

- README.md
- re: https://github.com/labwc/labwc.github.io/pull/1
> README.md: fix broken link for 'environment' man page

- README.md
- src/action.c
- src/common/buf.c
- src/config/keybind.c
- src/config/rcxml.c
- src/view.c
The ones from the [to do list](https://github.com/labwc/labwc/projects/1)
> [v0.5] more backports

- src/xwayland-unmanaged.c
Fixes #469
@Flrian testing welcome.
@johanmalm @jlindgren90
This is not an area of the codebase I am inherently familiar with so extra caution should be taken for the review.
> src/xwayland-unmanaged.c: Prevent racing configure event to reposition

- include/common/font.h
- include/common/scaled_font_buffer.h
- src/common/font.c
- src/common/scaled_font_buffer.c
- src/menu/menu.c
- src/ssd/ssd_titlebar.c
@Consolatis I've had a go at rendering submenu-arrows for the root+context menus. Review with a view to merge appreciated if you have time.
> Submenu arrows

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- src/config/rcxml.c
- src/osd.c
Feel free to close if you guys decide its not quite what you want or prefer something else! :)
> Add config option to disable preview outlines

- include/labwc.h
- src/output.c
- src/view.c
Fixes #497
Reported-by @Flrian
> Disconnect view from destroying output

- src/xwayland-unmanaged.c
- Eliminate multiple `return` paths in `unmanaged_handle_unmap()`, which were a bug waiting to happen.
- Use `wl_list_for_each_reverse()` rather than `wl_list_for_each()` to find the topmost (most-recently-created) unmanaged surface.
- Only call `desktop_focus_topmost_mapped_view()` if the unmapped surface was actually focused.
Fixes #520.
> xwayland: Factor out focus_next_surface() from unmanaged_handle_unmap()

- src/desktop.c
The topmost view may not always be the focused view; for example,
when Audacious's main window is focused but the floating Search
Tool window remains on top of it.  In that case the floating window
(not the main window) should be the first view selected in the
window switcher.
Fixes the issue mentioned in this comment:
https://github.com/labwc/labwc/pull/504#issuecomment-1228903654
> desktop: Cycle first to topmost view if not already focused

- include/labwc.h
- src/xwayland.c
This will hopefully fix
- #317
@acoolstraw @BitterlyIronic testing appreciated.
> xwayland: Keep view->xwayland_surface and view->surface in sync

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/common/font.h
- include/config/rcxml.h
- src/common/font.c
- src/common/scaled_font_buffer.c
- src/config/rcxml.c
- src/menu/menu.c
- src/osd.c
- src/ssd/ssd_titlebar.c
- src/theme.c
- src/workspaces.c
Adds support for bold and italic fonts, following the Openbox syntax.
> config: Add support for font slant and weight

- src/menu/menu.c
> src/menu.c: Clamp separator width

- src/view.c
Trying to fix issue reported by @Flrian 
https://user-images.githubusercontent.com/4444593/192260675-6c57484b-36d0-434b-91fe-96086613cfa4.mp4
Welcome help writing a better commit message that describes this issue better.
> view: no gap for top/left align big window

- include/common/graphic-helpers.h
- include/common/list.h
- src/action.c
- src/config/keybind.c
- src/config/mousebind.c
- src/config/rcxml.c
- src/desktop.c
- src/layers.c
- src/menu/menu.c
- src/ssd/ssd_part.c
- src/workspaces.c
- src/xwayland-unmanaged.c
> Add wl_list_append()

- CONTRIBUTING.md
Add a few more bits :smile: including
- Clarify the coding style relative to Linux kernel and Devault rules
- Add g_pattern_match_simple() example
- Add namespace advice and preference
> CONTRIBUTING.md: describe coding style more accurately

- subprojects/wlroots.wrap
This fixes an issue of unreadable displays in some multiple output configurations.
closes #583
> wlroots.wrap: update to latest wlroots

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/mousebind.h
- src/config/mousebind.c
- src/config/rcxml.c
- src/cursor.c
Hi, C junior here: bear with me, thanks for awesome project
I'll update the documentation after review.
> add support for mouse buttons UP and DOWN (scroll)

- src/output.c
Required by https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3637
See also swaywm/sway@07bfeb2
Fixes #516
> output: test adaptive sync

- src/xwayland.c
Each XWayland view is paired with a particular `wlr_xwayland_surface` and its lifetime is tied to that surface.  This condition in `handle_map()`:
if (xsurface != view->xwayland_surface)
could never be true since the view is only registered to receive the "map" signal from `view->xwayland_surface`, and no other.  So the code updating `view->xwayland_surface` in `handle_map()` was dead.
So let's clean things up a little:
- Remove the dead code
- Add some comments, and slightly rearrange code to match
- Add/update `assert()`s in signal handlers for consistency
- Pass `xsurface` as `data` when calling `handle_unmap()` and `handle_destroy()` explicitly, to be consistent
Lightly tested; I didn't see any new crashers or `assert()` failures.
> xwayland: Better document/assert view/surface association

- docs/README
- docs/meson.build
> docs: install example configs

- CONTRIBUTING.md
...and also split 'Debugging' into sub-sections
> CONTRIBUTING.md: describe how to upversion

- README.md
- Describe why the projects exists and state some core-dev values
- Explain that labwc does not depend on any sessions or UI toolkits
- Merge the two scope sections
- Put video links before screenshot
> README: restructure and amend project description

- src/output.c
- src/xdg.c
> Some fixes from static analysis

- docs/menu.xml
- docs/rc.xml
- docs/rc.xml.all
Should make it easier for users to discover the requirement of `<default />` when having custom mousebinds in place.
~~Not actually tested yet, thus draft for now.~~
> docs: add default mousebind example

- src/osd.c
This gives a clean separation of `osd_update` for changing the state of labwc itself and `osd_draw` for putting pixels in the surface buffer. I didn't want to add anything new to `osd_update` (as may be required by #647 and possibly #672) without simplifying it first.
> osd: factor drawing out of `osd_update`

- subprojects/wlroots.wrap
...in order to use recent fixes including setting exclusive zone correctly when only one edge is anchored (wlroots@48920828)
> subprojects/wlroots.git: use commit fe7e7a14 on 0.16 branch

- src/seat.c
The code just looked a bit ugly. No functionality changed.
> seat.c: minor refactoring of seat_reconfigure()

- src/ssd/ssd_part.c
This allows using large XBM button icons (larger than
the button width / height) for high and mixed DPI usecases.
Instead of scaling up the low pixel icons when moving a window to a
high DPI output we scale the icons down when moving to a non-scaled
output. The user is still responsible to create / use larger XBM
icons for their theme.
Partly fixes #609
Before:
After:
<details><summary>32x32 pixel example icon</summary>
```c
#define menu_width 32
#define menu_height 32
static unsigned char menu_bits[] = {
0xff, 0xff, 0xff, 0xff,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80,
0x01, 0x00, 0x00, 0x80, …
```
> ssd: scale down button icons if necessary

- src/view.c
> src/view.c: reorder includes

- protocols/meson.build
- src/server.c
For now, until we resolve the true cause here either on the Xwayland side or our side.
I intend to look into it soon.
Fixes: https://github.com/labwc/labwc/issues/553
> server: Filter out wp_drm_lease_device from Xwayland 

- CONTRIBUTING.md
- po/LINGUAS
- po/de.po
- po/es.po
- po/it.po
- po/labwc.pot
- po/meson.build
- po/sv.po
- po/tr.po
- also fixes updating tr.po file
- more descriptive instructions in CONTRIBUTING.md
- fix comments in po/pot files when using meson gettext tools
> nls: updates for new strings in menus

- src/debug.c
Before this patch following would cause a use-after-free:
- calling the Debug action when there was at least one view around
- closing that view
- calling the Debug action again
Also add a label for the layer popup tree.
> src/debug.c: reset last_view

- include/ssd.h
- src/ssd/ssd_border.c
- src/ssd/ssd_extents.c
- src/ssd/ssd_part.c
- src/ssd/ssd_titlebar.c
- src/theme.c
> include/ssd.h: prefix defines with SSD_

- docs/rc.xml
.. instead of adding a new one.
Also change from sakura to foot and add comments.
> docs/rc.xml: Overwrite the default W-Return keybind

- src/server.c
...in order to enable cool clients like chayang
References:
- https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3428
- https://git.sr.ht/~emersion/chayang
> Enable single-pixel-buffer-v1

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- src/config/rcxml.c
- src/output.c
> Support flicker free boot with non-preferred resolution / refreshrate

- NEWS.md
> NEWS.md: add notes on 0.6.1

- .github/workflows/build.yml
Trying to figure out whats up with the Debian Testing CI image
> [CI] adapt to new debian.sources format

- docs/labwc-actions.5.scd
> labwc-actions(5): update action format

- src/cursor.c
I looked how this was done in sway and did it in labwc. This fixes issues #339 and #534 for me.
> Mouse constraints implementation

- src/workspaces.c
> src/workspaces.c: update cursor focus

- docs/labwc-actions.5.scd
- include/labwc.h
- src/action.c
- src/desktop.c
- src/output.c
Fixes #806
---
Gave this a try but can't properly test it nested, also didn't check if there is a Openbox action relating to this so this is a Draft for now until somebody verifies this actually works as intended.
If it is deemed out-of-scope for labwc feel free to just close the PR.
> Add `FocusOutput` action

- src/action.c
- src/interactive.c
Fixes #817
Reported-by: @kode54
> Prevent rare crash due to layering move / resize / menu operations

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- src/config/rcxml.c
- src/osd.c
> osd: add config option to disable osd

- docs/labwc-config.5.scd
- docs/rc.xml.all
- src/config/rcxml.c
@Flrian - review appreciated
...and @Consolatis of course :smile:
> Config window switcher

- docs/labwc-actions.5.scd
- src/action.c
> Implement action "Lower"

- include/labwc.h
- include/session-lock.h
- src/desktop.c
- src/keyboard.c
- src/meson.build
- src/output.c
- src/server.c
- src/session-lock.c
…because the next version of swaylock will not run without it.
> Support ext-session-lock protocol

- src/cursor.c
After quite a few awkward and frustrating moments where I couldn't properly use the communication wheel in Overwatch 2 (#872 ) I decided to try implementing pointer warp myself by looking at how Gamescope does it.
This is the result, the game is now able to re-center it's pointer properly. Works for both windowed and fullscreen. Multiple monitors not tested.
Please let me know if there's any silly mistakes in the code.
> Mouse constraints improvements.

- src/output.c
Fixes #642
Reported-by: @heroin-moose
Tested-by: @heroin-moose
> src/output.c: fix adaptive sync

- NEWS.md
Planning to bump the version to `0.6.3` on Monday.
> NEWS.md: add notes on 0.6.3

- src/config/rcxml.c
No functional changes intended.
> src/config/rcxml.c: move region validation into the validate() hook

- src/action.c
Before this patch it was possible to assign an argument with an
existing name to an action that didn't support the given argument.
An example of this is using `direction` for `GoToDesktop`.
This patch now only creates action arguments that are actually
defined for the given action type and logs an error for
unsupported arguments.
The commit also makes sure to always supply the argument name.
This will reduce required checks in other parts of the codebase
in future commits.
> src/action.c: validate action type when assigning arguments

- src/output.c
- src/workspaces.c
> Do not render workspace OSD on disabled outputs

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- src/config/rcxml.c
This are the set of changes that I have been working on with reference to #763. I would really appreciate some feedback and suggestions. Currently the documentation of the changes are still pending but I shall write them once the updated changes are finalised.
> config: support <desktops number="">

- include/view.h
- src/view.c
- src/xdg.c
- src/xwayland.c
Aims to fix: #958
@Ph42oN - testing welcome
> view: add minimize method and call wlr_xwayland_surface_set_minimized() for xwayland surfaces on (un)minimize

- docs/labwc-theme.5.scd
- docs/themerc
- include/theme.h
- src/osd.c
- src/theme.c
> theme: add option osd.window-switcher.padding

- src/dnd.c
By default, leave keyboard-focus with the surface that originally had it at the end of a dnd operation.  This is consistent with the default behaviour of openbox and mutter.
If the 'focus/followMouse' option is enabled, then focus on the surface under the cursor at the end of the dnd operation.
Fixes: issue #976
> dnd: fix focus at end of dnd operation

- src/keyboard.c
This enables keybinds like `W-S-1` and `W-S-Tab`
> Fall back on raw keysyms when translated ones do not match keybinds

- include/view-impl-common.h
- src/view-impl-common.c
- src/xdg.c
- src/xwayland.c
...to share common code with minimize_sub_views()
> view: make move_sub_views() use append_children method

- src/cursor.c
> src/cursor.c: end popup grab on desktop click

- docs/labwc-theme.5.scd
- include/button-png.h
- include/theme.h
- include/xbm/xbm.h
- meson.build
- src/button-png.c
- src/meson.build
- src/ssd/ssd_titlebar.c
- src/theme.c
- src/xbm/xbm.c
TODO
Some review in the meantime would be appreciated
> Support png buttons

- src/xdg.c
- src/xwayland.c
> view: only add foreign-handle for root toplevel

- scripts/checkpatch.pl
- src/xwayland.c
Because the @Consolatis asketh for this
> checkpatch.pl: check single statement brace

- scripts/helper/find-idents.c
...which so far has caused any bugs!
> find-idents.c: fix typo

- include/common/array.h
- src/osd.c
> Add `wl_array_len()`

- include/labwc.h
- include/view.h
- src/desktop.c
- src/osd.c
- src/view.c
> Move `isfocusable()` from `desktop.c` to `view.c`

- include/labwc.h
- src/seat.c
- src/touch.c
> Store coordinate adjustments for touch points

- include/menu/menu.h
- src/keyboard.c
- src/menu/menu.c
Fixes:
- #1058
Requested-by: @stefonarch
> src/menu/menu.c: support keyboard driven selection

- src/config/keybind.c
> keybinds: allow non-english based keybinds

- src/cursor.c
Before this patch, when moving a CSD client below a layershell surface - like a panel that was configured with either the "top" or "overlay" layers - we'd only send a matching release button event to the client but not actually end the interactive move operation. That caused the drag to continue even though the user already released the mouse button.
In comparison, SSD clients were not suffering from the same issue because the initial mouse "down" event was not attached to any client surface and thus it would not take the first early return because there was no surface attached to the release event.
This patch fixes the issue by reordering the conditions where we return early. It also ensures that when we finish the move, we still send the release event to CSD clients.
Fixes:
- #1053 …
> src/cursor: ensure interactive move/resize ends correctly for CSD clients

- docs/labwc-config.5.scd
Fixes https://github.com/labwc/labwc/issues/1075
Not sure if also scroll action can be combined, didn't test.
> docs: clarify mouse binds

- NEWS.md
> Update `NEWS.md` in readiness `0.6.5` release

- src/view.c
> src/view.c: guard xwayland include

- src/output.c
> Fix typo in output.c

- README.md
@Consolatis @jlindgren90 @heroin-moose If you have time, any feedback on the third commit (on icons/gradients/dropshadows) would be appreciated - particularly if you disagree with it.
> Update README with build details and a toning down of the no-frills approach

- docs/labwc-actions.5.scd
- include/action.h
- include/common/match.h
- include/view.h
- src/action.c
- src/common/match.c
- src/config/rcxml.c
- src/view.c
- src/workspaces.c
This patch series introduces support for [If](http://openbox.org/wiki/Help:Actions#If) and [ForEach](http://openbox.org/wiki/Help:Actions#ForEach) actions as referenced in OpenBox Specification.
Missing parts:
* No action nesting
* Most conditions are not there yet (only identifier and title are supported)
* If's query lacks target argument
> Add If and ForEach actions

- docs/labwc-config.5.scd
Forgot to update docs in
- #1145
whoops.
> docs: update supported keybind modifiers

- src/keyboard.c
This was forgotten in 65bd32d62500389a1d6affafac6d1989ba28042f
Reported-by: @jonhiggs (thanks)
Also stop treating the synthetic layout change sym as modifier
but still prevent it from being added to the set of pressed keys.
Additionally slightly reformat the code.
> keyboard: add missing Hyper_ and Meta_ syms to modifier detection

- src/seat.c
If an xwayland-unmanaged surface was focused belonging to the same application as the focused view, allow the view to remain active. This fixes an issue with menus immediately closing in some X11 apps (try LibreOffice with SAL_USE_VCLPLUGIN=gen).
Fixes: 4028a9482f9399e3c3587f5c6eca6c0b128c9afc
("seat: use focus_change event to update focused/active view")
Fixes #1161.
> seat: ignore focus change to unmanaged surface belonging to same PID

- docs/labwc-actions.5.scd
- include/view.h
- src/action.c
- src/view.c
Not tested on multiple screens setup, nor with virtual workspaces.  
(Though this should just work (TM)).
> Add MoveToCursor action.

- src/xdg.c
Qt applications occasionally fail to call set_window_geometry after a configure request, but do correctly update the actual surface extent. This results in a mismatch between the window decorations (which follow the logical geometry) and the visual size of the client area. As a workaround, try to detect this case and ignore the out-of-date window geometry.
Should fix #1194.
> xdg: try to handle missing set_window_geometry with Qt apps

- .github/workflows/build.yml
https://github.com/vmactions/freebsd-vm/issues/74#issuecomment-1798014978
Also drop `llvm15` (via `mesa-dri`) to shave CI time.
> CI: run FreeBSD job on Ubuntu (to improve stability)

- src/input/key-state.c
- src/input/keyboard.c
@jlindgren90  - you're review would be much appreciated if you've got time. Full explanation in commit message.
> Fix small key-repeat regression

- src/xwayland.c
...as it needs to be set before honouring xwayland_surface->fullscreen because that calls desktop_update_top_layer_visiblity() which relies on view->surface being set in view_is_focusable() since 13d0b14.
Fix bug introduced by PR #1237 which fails to hide the xfce4-panel (or any other layer-shell client in the top layer) whilst gaming in fullscreen. The bug can be observed with the following games:
- Alan Wake 2 (wine)
- Starfield (steam+proton)
- Cyberpunk (steam+proton)
- Quake 1 Remaster (steam-native)
Fixes: #661 (the last bit of it)
Reported-by: @ScarecrowDM
> xwayland: assign view->surface earlier in map handler

- src/xwayland.c
Prevents xwayland clients from messing with the geometry of maximized/fullscreen/tiled views.
This should fix the main issue of #753 (VLC having incorrect geometry when started fullscreen) more properly, without the side effects documented in #785. Unfortunately it depends on a wlroots change (https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4008) to work properly, and shouldn't be merged until we can require a wlroots version containing that change (otherwise it will trigger the same repaint issues that #753 suffered from).
> xwayland: Prevent overriding maximized/fullscreen/tiled geometry

- docs/labwc-actions.5.scd
- src/action.c
> Add ResizeTo action

- include/labwc.h
- src/output.c
- src/server.c
References:
- https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4046
- https://github.com/swaywm/sway/pull/7494/files
Fixes: #1262
Have tested with `gammastep -O 4500`
> chase: handle gamma-control-v1 set_gamma events

- src/layers.c
This ensures that the usable area is completely calculated before non exclusive-zone clients are positioned / resized.
Fixes
- #1285
Reported-by: @spl237
> src/layers.c: calculate usable_area before positioning clients

- include/ssd-internal.h
- src/ssd/ssd.c
- src/ssd/ssd_part.c
- src/ssd/ssd_titlebar.c
Followup from
- #1280
Only slightly tested, no functional change intended.
> src/ssd: refactor button hover and maximize toggle

- src/view.c
The `MoveToEdge` action can be extended naturally to adjacent outputs in a matter generally analogous to the behavior of `SnapToEdge`. Such a feature already exists in OpenBox. The proposed behavior is:
1. If the existing move logic determines a nonzero move in either *x* or *y*, keep the existing behavior; the view being moved will advance on the same output to the next edge.
2. When the determined move is zero in both *x* and *y*, find an output adjacent to the current output for the view along the direction in which the move is desired.
3. If an appropriate adjacent output exists, move the view onto that output, at the edge *opposite* the target direction (*i.e.*, along the edge *nearest* the original output).
When the outputs and views are well behaved, that's all there is: the window …
> view: continue move-to-edge behavior to adjacent outputs

- docs/labwc-theme.5.scd
- docs/themerc
- include/theme.h
- src/theme.c
- src/workspaces.c
This allows to configure width and height of "boxes" displayed in the workspace OSD.
Closes #1199
> Theme option to configure boxes from workspace OSD

- CONTRIBUTING.md
- po/labwc.pot
> labwc.pot: update for new OmniPresent menu

- docs/menu.xml
- po/de.po
- po/es.po
- po/id.po
- po/it.po
- po/ka.po
- po/labwc.pot
- po/pl.po
- po/ru.po
- po/sv.po
- po/tr.po
- src/menu/menu.c
...and rename it to "Always on Visible Workspace"
Issue: #1316
> menu: move ToggleOmnipresent to workspaces

- src/xwayland.c
For unknown reasons, XWayland surfaces that are completely offscreen seem not to generate commit events. In rare cases, this can prevent an offscreen window from moving onscreen (since we wait for a commit event that never occurs). As a workaround, move offscreen surfaces immediately.
This fixes an issue that I can reproduce by having qmpanel displayed on a (larger) external monitor, then undocking the laptop so that qmpanel requests a simultaneous move+resize to the (smaller) laptop display.
> xwayland: fix issue with panel getting stuck offscreen

- NEWS.md
Needs a final tweak prior to releasing `0.7.0` (e.g. date, line-count and so on)
> NEWS.md: update notes for 0.7.0

- src/button/button-png.c
- src/button/button-svg.c
- src/button/button-xbm.c
- src/common/font.c
- src/common/parse-bool.c
- src/common/spawn.c
- src/config/rcxml.c
- src/config/session.c
- src/desktop.c
- src/dnd.c
- src/layers.c
- src/menu/menu.c
- src/output.c
- src/snap.c
- src/theme.c
- src/view-impl-common.c
- src/window-rules.c
Fix clangd warnings regarding headers not being used directly.
> Remove headers not being used directly

- src/osd.c
...to allow inclusion of ./scripts/find-banned in CI
> osd: refactor to eliminate usage of g_strcmp0()

- docs/rc.xml.all
- include/config/rcxml.h
- include/config/tablet.h
- src/config/rcxml.c
- src/config/tablet.c
- src/input/tablet.c
Same as the other tablet PRs, based on @Consolatis work here https://github.com/labwc/labwc/issues/1060#issuecomment-1786384495
> feat: Add tablet rotate transformation

- include/config/rcxml.h
- include/labwc.h
- src/config/rcxml.c
- src/output.c
- src/view.c
This option was asked to be added in issue #1323.
Im also planning to use set_view_mode function this adds for tearing option that im making. Im not sure if this is good name for this function.
> Add adaptive sync fullscreen option

- docs/labwc-config.5.scd
@Ph42oN  - any chance you could review this?
> labwc-config(5): describe adaptive sync fullscreen option

- docs/rc.xml.all
As empty string there is not matched as how it was expected.
> rc.xml.all: replace "" with "default" in libinput device category

- docs/labwc-config.5.scd
- docs/rc.xml.all
I forgot those earlier...
Closes https://github.com/labwc/labwc/issues/1401
> docs: add tablet section

- include/view.h
- src/view.c
- src/xdg.c
- src/xwayland.c
In response to https://github.com/labwc/labwc/issues/1399
> Fit within usable area

- docs/labwc-config.5.scd
- docs/rc.xml.all
> docs: fix element ending

- src/input/keyboard.c
...(calling `wlr_session_change_vt()`) because when the session is switched, the access to the keyboard is lost and therefore the RELEASE event will not be passed to the compositor.
Related-to #1424
@jbeich Reported that there is still a crash, but I feel this is still the right thing to do.
Cc: @kennylevinsen
> keyboard: cancel key repeat on vt change

- docs/rc.xml.all
> Removed obsolete comment

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- include/config/tablet.h
- include/config/touch.h
- include/input/tablet.h
- src/config/meson.build
- src/config/rcxml.c
- src/config/tablet.c
- src/config/touch.c
- src/input/tablet.c
- src/input/tablet_pad.c
- src/seat.c
Not a very big fan of this, but it's reasonable and should address the initial issue in https://github.com/labwc/labwc/issues/1422
Still ~WIP...~ needs testing (~also by me, I have just checked that it compiles but wanted CI feedback) and docs~.
PS: the first commit is just a small refactor in the tablet space .
> feat: multiple touch configurations with device name identifier

- src/view.c
Follow up from https://github.com/labwc/labwc/pull/1457#discussion_r1462493089 and based on discussion with @Consolatis
> view: do not resize fullscreen windows

- src/resistance.c
Caught a couple of bugs relating to resistance and attracting when moving shaded windows or when moving/resizing windows in the vicinity of shaded windows. These changes fix the issues.
> resistance: properly handled shaded windows

- docs/environment
> environment: add Thunderbird to MOZ_ENABLE_WAYLAND description

- src/xdg.c
Calling the `wlr_xdg_toplevel_set_size()` function will cause wlroots to record the size in its `wlr_xdg_toplevel.scheduled` structure, which is never cleared after an XDG configure event is sent. All subsequent XDG configure events will include this size. This means that `wlr_xdg_toplevel_set_activated` will send an activation event that includes the last-configured size.
If a client resizes itself after a call to `wlr_xdg_toplevel_set_size()`, the client will trigger a surface commit that calls labwc's `handle_commit` callback, and we record the proper `view->current` (and `view->pending`) to reflect the client's actual size. However, wlroots still holds the last value set by `wlr_xdg_toplevel_set_size()`, which means that any subsequent XDG configure will sent a different size than the …
> xdg: make sure wlroots knows client size before activation

- src/view.c
If a view is fully within the usable area of its original output, it should be fully within the usable area (if possible) on its new output.
This addresses [an issue discovered by @johanmalm](https://github.com/labwc/labwc/pull/1482#issuecomment-1917587158) where the `MoveToEdge` action kicks a view to another output and covers a panel.
> view: better honor usable areas when changing outputs in view_move_to_edge

- src/edges.c
These changes combine two improvements to the edge engine for snapping and resistance behavior:
1. The first commit greatly simplifies edge detection for outputs. The existing implementation was a leftover from a draft where `validate_edges` was a function unique to both `resistance.c` and `snap.c` and, therefore, required that `edges_find_outputs` cast the generic region problem into a form that could be applied to both cases. Now that `validate_edges` is a common routine in `edges.c`, it is much cleaner to add a simpler `validate_output_edges` routine that reduces checks against imaginary, infinite edges.
2. The second commit is a quality-of-life improvement for `edges_find_neighbors` that will ignore snapping to any views on outputs that do not intersect the view being moved. First, …
> Edge snapping/resistance improvements

- NEWS.md
This could probably use some refinement for clarity.
> NEWS.md: note breaking changes in snapping behavior

- src/view.c
> view: respect rc.gap when moving to cursor

- src/desktop.c
Started to annoy me enough recently so I actually had the motivation to "fix" it this time.
> src/desktop.c: reduce OSD log spam on hover

- src/theme.c
Fixes
- #1504
\+ some minor code improvements as 2nd commit.
> src/theme.c: use rounded hover overlays

- .github/workflows/build.yml
- src/config/rcxml.c
- src/input/cursor.c
- src/placement.c
- src/seat.c
- src/ssd/ssd_part.c
To detect more cases like disabled asserts() and in general see stuff that might only show up with optimized builds.
> CI: add release build step

- src/debug.c
and resolve workspaces names + truncate everything.
Also added app_id / WM_CLASS to `view`.
It now looks like
```
X     Y        Node
----  ----  ----------------
server->scene                              0     0  [0xaaaaaba930d0]
+-- output->layer-background          1280     0  [0xaaaaabbc15a0]
+-- output->layer-bottom              1280     0  [0xaaaaabbc16c0]
+-- output->layer-background             0     0  [0xaaaaabbb7f60]
+-- output->layer-bottom                 0     0  [0xaaaaabbb9510]
+-- server->always_on_bottom             0     0  [0xaaaaaba931b0]
+-- server->view_tree                    0     0  [0xaaaaaba93240]
+-- Workspace 1                       0     0  [0xaaaaaba93510]
+-- seat->region_overlay           0     0  [0xaaaaabd59720]
+-- rect                        0     0 …
```
> src/debug.c: detect more scene trees

- src/edges.c
The fix in #1492 ignored cases when the neighbor being snapped is on another display but spills over *slightly* (so as not to affect its designated output) into the output of the view being moved. Rather than just checking that the view being moved or resized intersects with the output containing the neighbor, it is also necessary to check whether the neighbor intersects with the output containing the changing view.
Edit: this has been altered to use the new `view->outputs` bitmap; see comments below.
> edges: handle cases where neighbor spills into output of moving view

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/libinput.h
- src/config/libinput.c
- src/config/rcxml.c
- src/seat.c
Resolves #957 
For this PR to be ready to merge, I still need to 
I did try it out, and it does work. But sadly I can not daily drive labwc master because of #1337
> Add click method libinput option

- README.md
...and use the png files on the labwc website rather than imgur.
Fixes: #1363
> README.md: Add screenshot description

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/libinput.h
- src/config/libinput.c
- src/config/rcxml.c
- src/seat.c
Fixes #559. 
I have changed the following files:
- `include/config/libinput.h`
- `src/config/libinput.c`
- `src/config/rcxml.c`
I shall update the documentation once the code review is complete:)
> config: support libinput sendEventsMode

- docs/labwc-config.5.scd
> docs: add sendEventsMode to libinput snippet

- po/LINGUAS
- po/cs.po
Since I cannot create new language on weblate...
> Add cs language

- docs/labwc-config.5.scd
> fix: typo in labwc-config.5.scd

- src/input/key-state.c
Trivial code simplification. No functional change.
> key-state: use struct assignment

- src/output.c
PR #1301 did partly revert the first variant because `lab_wlr_scene_output_commit()` (which uses the `output->pending` state in contrast to `wlr_scene_output_commit()`) was deemd to cause 'frozen' frames during video playback (#1273).
We are now back at using `lab_wlr_scene_output_commit()` for unrelated reasons and the cause of the original issue #1273 was likely that `wlr_scene_output_send_frame_done()` was only sent on a successful commit. This was changed to always be sent in the meantime.
So lets restore the flicker free nested resize as well.
---
This should be fine to include in 0.7.1. I don't expect it to make any difference other than stopping the nested resize flicker.
> src/output.c: restore flicker free resize when running nested

- protocols/meson.build
- src/server.c
I'd be fine with delaying this until after the release.
> src/server.c: filter out xwayland shell for usual clients

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- include/labwc.h
- include/view.h
- src/config/rcxml.c
- src/desktop.c
- src/input/keyboard.c
- src/osd.c
- src/view.c
Related-to #1454
Cc: @droc12345
> Refactor cycle view

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- src/config/rcxml.c
Default is still "Workspace" for numbers but this allows user to set the prefix
> Add ability to set workspace prefix when using number

- .github/workflows/build.yml
- scripts/ci/autostart
- scripts/ci/ci_autostart.sh
- scripts/ci/smoke-test.sh
To (hopefully) prevent things like
- #1615
from going undetected in the future.
> CI: add simple runtime test

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/libinput.h
- src/config/libinput.c
- src/config/rcxml.c
- src/seat.c
My android pad emit a strange touch input from libinput, need to rotate it in 270 degree clockwise to fix.
I really like this project.
This is my first pr, I would be happy if give me some advice or other things.
> libinput: add support for touchscreen set matrix

- src/config/rcxml.c
It's my fault, forgetting to test for calibration matrix elements less than 6. ;)
> rcxml: add missing check for calibrationMatrix

- CONTRIBUTING.md
Ref
- https://github.com/bsd-ac/wayland-desktop/issues/78
> CONTRIBUTING.md: add Gentoo overlay maintainer

- docs/labwc-config.5.scd
> labwc-config(5): clarify applicability of element/attribute

- docs/labwc-config.5.scd
Let's link tablet rotation and calibration matrix since the calibration matrix can also achieve the rotation, but also more.
> docs: Refer to calibration matrix

- src/server.c
This may happen when running with WLR_BACKENDS=headless.
Fixes:
- #1618
> server: don't create headless backend twice

- docs/labwc.1.scd
- include/common/spawn.h
- include/labwc.h
- src/common/spawn.c
- src/main.c
- src/server.c
See commit message.
Ref #1595
Cc: @stefonarch
> Add `-S|--session` command line option

- src/action.c
- src/config/rcxml.c
adds a none branch to ForEach whose actions will be ran when no matches were found
from issue  #1298
> add none option to ForEach action

- docs/labwc-actions.5.scd
> docs: add missing documention for the ForEach none branch

- include/common/buf.h
- include/common/grab-file.h
- src/action.c
- src/button/button-xbm.c
- src/common/buf.c
- src/common/dir.c
- src/common/grab-file.c
- src/config/rcxml.c
- src/config/session.c
- src/menu/menu.c
- src/osd.c
- src/osd_field.c
Rework of #1629 incorporating some of the ideas mentioned in discussion there.
Also includes the first commit from #1629 as-is (thanks @Consolatis!) which looks like a simple fix and could be merged separately.
> common: remove buf_init(), add BUF_INIT and buf_move()

- .gitignore
`.cache/` is created by Visual Studio Code
`*.user` are files created by Qt Creator
> exclude IDE settings in .gitignore

- src/input/ime.c
This MR fixes that workspace-switcher is immediately terminated when focus is moved between windows while Fcitx5 is running. https://github.com/fcitx/fcitx5/commit/b2924bd361680c493463d240a375b3f0948ae48d is also required to fix the issue.
Demos below is performed with following settings. I kept pressing Alt+Shift and clicked 1 and 2 alternately.
```xml
<desktops>
<names>
<name>Workspace 1</name>
<name>Workspace 2</name>
</names>
</desktops>
<keyboard>
<keybind key="A-S-1"><action name="GotoDesktop" to="Workspace 1" /></keybind>
<keybind key="A-S-2"><action name="GotoDesktop" to="Workspace 2" /></keybind>
...
```
Before:
https://github.com/labwc/labwc/assets/22029524/e7f0ba77-0639-45e8-9bf5-7f7f1139e77e
After:
https://github.com/labwc/labwc/assets/22029524/920d4caf-e257-4f6d-9c52-c2d05fbe4 …
> IME: prevent virtual keyboard from unintentionally releasing modifiers

- src/server.c
> server: refactor to avoid *g_server

- include/workspaces.h
- src/server.c
- src/workspaces.c
> workspaces: react to Reconfigure

- include/view.h
- src/view.c
- src/xwayland.c
> xwayland: prevent shaded views from getting mouse events

- docs/rc.xml.all
Tried values for `x=` and `y=` and they didn't work hence this PR.
> rc.xml.all: s/y/height/ in WindowRule ReSizeTo comment

- src/seat.c
Slurp and Chromium expect `wl_keyboard.keymap` event to be sent before `wl_keyboard.modifiers` event.
Normally, `wl_keyboard.keymap` event is sent on the client first obtains `wl_keyboard` with `wl_seat.get_keyboard` request.
However, after the active (especially virtual) keyboard is destroyed, wlroots doesn't respond to `wl_seat.get_keyboard` request with `wl_keyboard.keymap` event since there's no active keyboard on the seat.
Therefore, if we run commands like `sleep 2; wtype hello; chromium` (without fcitx5), the active keyboard is destroyed when `wtype` finishes, and `wl_keyboard.modifiers` event is sent to Chromium when Chromium first maps the surface and the keyboard focus is moved to it, then Chromium crashes. I guess something similar is happening in #1770. …
> seat: prevent Chromium from crashing when active keyboard is gone

- NEWS.md
> NEWS.md: update for 0.7.2

- src/config/keybind.c
This is entirely untested, as of yet.
I'll test it tomorrow if no one gets around to it :)
> keybind: allow keybinding "-"

- src/action.c
> SendToDesktop: ensure we focus the topmost view with follow=no

- docs/labwc-actions.5.scd
- include/config/rcxml.h
- include/view.h
- src/action.c
- src/config/rcxml.c
- src/view.c
- src/xdg.c
- src/xwayland.c
> action: allow configurable policy in AutoPlace action

- src/main.c
This mostly allows for using scripts that trigger a labwc SIGHUP to work as expected. Before this patch, there was a race between the event loop starting up and the autostart scripts executing.
One example of such a use-case is dynamically setting the keyboard layout or cursor theme via environment variable based on feedback from a dbus service like discussed in #1588.
> src/main: delay startup of applications until event loop is ready

- include/input/tablet.h
- src/input/tablet.c
- src/input/tablet_pad.c
- src/seat.c
These are the first three commits from https://github.com/labwc/labwc/pull/1678 which are imho a good idea regardless of support for more axis. See the separate commits for what gets improved.
> impr: small tablet improvements

- docs/labwc-theme.5.scd
> doc: fix inconsistent wording

- src/view.c
Fixup 41a3b6884630eb3299aa66c2152f1b639242999e
Fixes #1841
> decorations: fix handling of SSD/non-SSD windows

- docs/labwc-actions.5.scd
- src/action.c
Suggested-by: @Vladimir-csp
Fixes: #1825
> Add action UnMaximize

- src/view.c
> view: fix child views can open outside of usable area to right/bottom

- src/input/keyboard.c
...that is longer than the specified repeatDelay interval.
> keyboard: handle onRelease keybind after long press

- src/dnd.c
> dnd: show dnd icon above layer-shell surfaces

- src/menu/menu.c
No inteded functional change intended with refactoring of get_submenu_position().
Fixes #1870
> menu: support menu.overlap.x with pipemenus

- src/ssd/ssd-shadow.c
Before this patch, we were leaking memory [0] because the shadow implementation did not free the ssd_parts on destruction.
There was also no check if shadows were actually enabled via rc.xml or not so this also impacted people who were not using shadows but were not setting the shadow size via their theme to 0.
[0] 44 bytes per ssd_part * 8 parts * 2 states == 704 bytes per view closed. Note that Reconfigure also re-creates the SSD, thus we were also leaking 704 bytes * nr_views per Reconfigure.
> ssd/ssd-shadow.c: fix memory leak

- NEWS.md
Review(s) appreciated.
Intend to merge on Friday.
> NEWS.md: update for 0.7.3

- include/labwc.h
- src/magnifier.c
- src/server.c
Fixes:
- #1980
Draft while waiting for confirmation that disabling direct scanout fixes the issue.
> magnifier: disable direct scanout when active

- src/config/rcxml.c
Add some defaults which were missing from initialization.
> config: initialize some missing defaults

- src/common/font.c
- src/osd.c
- src/workspaces.c
Chase https://github.com/swaywm/sway/commit/8c5b23e592d2334b3324227dd9d1311e46c5fd69
Intended to be merged after transition to wlroots 0.18
> Disable pango glyph position rounding

- scripts/check
by running up to nproc checkpatch.pl instances in parallel
> CI: increase speed of codestyle check

- src/view.c
I intended to fix this quite some time ago but didn't get around to it.
I don't think there's any good reason why we need to un-fullscreen a view when its output is disconnected. We can handle it the same as a maximized view, and move it to a new output (remaining fullscreen) or, if all outputs are disconnected, just leave it as-is.
This is helpful for a media-center use-case, where you have just one view (e.g. Kodi) fullscreen all the time, but the TV might appear to be disconnected if you switch it to a different source.
Tested with a couple different scenarios:
1. Single output disconnected and re-connected: view stayed fullscreen.
2. Secondary output disconnected: view stayed fullscreen but moved to the primary output, and the layer-shell panel on that output was hidden as expected. …
> view: stay fullscreen when view's output is disconnected

- docs/labwc-config.5.scd
- include/config/keybind.h
- src/config/rcxml.c
- src/input/keyboard.c
fixes #2034
There is a [similar feature in sway](https://github.com/swaywm/sway/blob/bc258a3be2f946c1c93bcbe40735b2db068e0ea8/sway/sway.5.scd?plain=1#L409).
> Implement locked keybindings

- src/input/keyboard.c
With XKB_DEFAULT_LAYOUT= (set to empty rather than unset) the keyboard just does not work.
Ref: https://github.com/labwc/labwc-tweaks/issues/89
> keyboard: fix bug with empty XKB_DEFAULT_LAYOUT

- src/common/scene-helpers.c
Using the output damage_ring for early out will break VRR in direct scanout mode. The reason being that the damage_ring will be completely ignored in that mode so we need to check `output->pending_commit_damage` instead. This matches with what wlroots has been doing since [0] and it was missed in the initial port to wlroots 0.18.x.
However, that would then break the magnifier which only adds its damage to the damage ring. After some discussion with the wlroots devs we came up with a solution that should work for both, wlroots 0.18.0 and when [1] is backported to 0.18.1.
Note that even with this PR, VRR in direct scanout mode is broken in 0.18.0 from the wlroots side and will be fixed once [1] is backported to the 0.18 branch and 0.18.1 is released.
Fixes: #2078
[0] …
> scene-helpers: use pending_commit_damage, chases wlr!4253

- docs/labwc-config.5.scd
- docs/labwc-theme.5.scd
- docs/menu.xml
- docs/rc.xml.all
- docs/themerc
- include/common/font.h
- include/config/rcxml.h
- include/theme.h
- src/common/font.c
- src/config/rcxml.c
- src/menu/menu.c
- src/theme.c
separators work with and without a label
label title additions
- text color
- font selection
- center justification
- Oblique font style
> menu title enhancements

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/rcxml.h
- include/ssd-internal.h
- include/ssd.h
- src/config/rcxml.c
- src/snap.c
- src/ssd/ssd-part.c
- src/ssd/ssd-titlebar.c
- src/ssd/ssd.c
- src/theme.c
- src/view.c
- src/xwayland.c
An attempt at implementing #857 
I don't really understand `add_scene_button_corner()`, so I would be happy to get some help with that.
> theme: implement titleLayout

- docs/labwc-actions.5.scd
- include/common/direction.h
- include/labwc.h
- include/view.h
- src/action.c
- src/common/direction.c
- src/common/meson.build
- src/desktop.c
- src/output.c
- src/view.c
This is a small patch to address https://github.com/labwc/labwc/issues/2099.
> Change "FocusOutput" to be more in-line with "MoveToOutput"

- docs/labwc-theme.5.scd
> docs: add description for new theme buttons 'shade' and desk'

- README.md
> README.md: update config files to six

- docs/labwc-actions.5.scd
- src/action.c
menu placement
. x,y coordinates ie. 0,0 or 100,100
. centered on output monitor
< popupPosition>Fixed</popupPosition>
< popupFixedPosition>
< x>10</x>
< y>10</y>
< /popupFixedPosition>
OR
< popupPosition>Center< /popupPosition>
> menu enhancements placement

- src/theme.c
This enhances the mitigation in #2136 by using the buffer returned from `rounded_corner()` as a mask for the hover overlay buffer.
Please note that this is my first time writing code with cairo.
> theme: round the hover effect along the window border

- src/action.c
It looks slightly awkward when the client menu shows up in the left corner of the view and the window menu button is configured to be on the right side.
Before:
After:
The appearance is unchanged when the menu button is the first one and when no padding is applied. 
My initial version placed the menu in the center underneath the button (like GTK4 does), but I think this version fits better considering how the menu looks.
> action: open the client menu underneath the window menu button

- src/action.c
Without this fix it doesn't update properly as a submenu.
> client list combined menu fix for submenu use

- docs/menu.xml
- docs/rc.xml.all
2 examples in rc.xml.all 
one for mouse bind, one for keybind
1 example in menu.xml
show client-list-combined-menu as submenu of root-menu
> client list combined menu examples

- docs/labwc-actions.5.scd
- docs/labwc-menu.5.scd
- docs/menu.xml
- include/menu/menu.h
- src/action.c
- src/menu/menu.c
Needs to be merged after #2101.
Edit to add: after 2101 gets merged, I'll have to repush this to get a clean pr. 
Eta2: I have rebased this, should be good for review.
> Sendto menu - addition to client window menu

- po/labwc.pot
> labwc.pot: update translation template for 71b2b5a

- include/view.h
- src/xdg.c
> xdg: handle `show_window_menu` requests

- docs/labwc-config.5.scd
- docs/rc.xml.all
- src/config/rcxml.c
Change Openbox style `WLIMC` syntax to `menu:title:minimize,maximize,close` as was agreed when PR #2088 was merged.
Ref:
- https://github.com/labwc/labwc/pull/2088#issuecomment-2295730704
Cc: @xi
> theme: finish titleLayout implementation

- src/config/rcxml.c
https://github.com/labwc/labwc/pull/2150#issuecomment-2370235187
Cc: @jp7677
> theme: fix incorrect default for <titlebar><showTitle>

- src/icon-loader.c
@vyivel @tokyo4j would one of you mind doing a review of this one.
I've tested and it works with `gtk-lshw` which has an absolute icon-name.
> Fix absolute icon name

- src/icon-loader.c
Add fallbacks to:
1) match reverse-URL .desktop file names when the app_id is just the
base name (e.g. "thunderbird" -> org.mozilla.Thunderbird.desktop)
~2) look in /usr/share/pixmaps when the icon isn't present in the
hicolor theme (still the case for many applications)~
> icon-loader: match more application icons via fallbacks

- src/icon-loader.c
Useful for debugging why an icon isn't being loaded.
> icon-loader: add a log handler for sfdo messages

- src/theme.c
Reported by @jp7677: https://github.com/labwc/labwc/pull/2213#issuecomment-2395337540
> theme: fix loading *-inactive.svg icons

- src/xdg-popup.c
With Qt apps I get a scheduled x coordinate of `-6` for the `File` menu (the left-most one) pushing it over to the next output.
[recording.webm](https://github.com/user-attachments/assets/c7174596-1624-45e0-9759-b7f39dc1fbea)
> xdg-shell: fix popup on wrong output

- src/icon-loader.c
@tokyo4j or @jlindgren90 - happy with this?
Fixes: #2247
> icon-loader: use relaxed load options

- NEWS.md
> NEWS.md: update for 0.8.1

- src/input/keyboard.c
...to all clients rather than just the one with keyboard focus on keyboard enter/create, modifer press/release and wlr_seat_set_keyboard().
This enables:
- Clients such as panels to display the current keyboard layout without introducing new wayland protocols or other IPC.
- Unfocused xdg-shell clients to understand button press with keyboard modifiers for example Ctrl+click.
The keymap is forwarded to all clients in wlr_seat_set_keyboard(). When a keymap contains multiple layouts, the selection is made via modifiers, which previously were only sent to the client with keyboard focus.
Tested with: https://github.com/johanmalm/keyboard-layout
Ref: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4496
Fixes: #2271
> keyboard: broadcast modifiers

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/config/touch.h
- src/config/rcxml.c
- src/input/touch.c
Cleaned-up version of mouse emulation code for touch devices.
> Add mouse emulation for touch devices

- src/session-lock.c
session_lock_output_create() can safely no-op if the lock output has already been created for the specified output. This scenario doesn't happen currently, and the change is in preparation for some other output-related changes I am working on. But I think it's a nice code improvement worth merging separately.
For after 0.8.1.
> session-lock: make session_lock_output_create() safe to call twice

- docs/labwc-theme.5.scd
Sorry for my careless review in #2235.
> docs: add documentation for window.button.height

- .github/workflows/irc.yml
As we move to feature requests being in discussions (which I don't really have an opinion on) lets create IRC triggers for new discussions as well.
> CI: add IRC notification for discussion created

- meson.build
- src/common/buf.c
Fixes: #2313
Backported from 7e50c60b003618729554777e61abda6ca935dc4b
> [v0.7 backport] buf.c: fix off by one bug in buf_add_char()

- src/seat.c
As per https://github.com/labwc/labwc/issues/2320
> Fix bug whereby pointer speed of -1 is not valid

- src/output.c
- src/view.c
> view: ensure output is usable before setting adaptive sync

- NEWS.md
Thanks for the honors, but this fix wasn't on me ;)
> NEWS.md: fix author

- scripts/asan_leak_suppressions
- scripts/run-with-asan.sh
...so suppress errors from ASAN with EGL renderer.
Also add Makefile to simplify running with sanitizer and this suppression file.
Related-to: #2331
> Add lsan.supp

- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/common/match.h
...to align with glob(7) language
Reported-by: @vyivel
> docs: simplify description of shell wildcard patterns

- include/view.h
- src/debug.c
- src/input/ime.c
- src/view.c
- src/xdg.c
- src/xwayland.c
Just for readability. Intended for merging after 0.8.2 release.
> view: s/scene_node/content_node/

- docs/labwc-actions.5.scd
> labwc-actions(5): add missing position option to ShowMenu

- include/layers.h
- src/input/cursor.c
- src/layers.c
- src/xdg-popup.c
Fixes #2438.
@jlindgren90 Should we do this also for unmanaged xwayland surfaces?
> xdg-popup: update pointer focus on popup destruction

- src/foreign-toplevel/wlr-foreign.c
> wlr-foreign-toplevel: send initial pre-map state

- src/debug.c
> src/debug.c: fix inverted string_null_or_empty() check

- src/output.c
The wlr_output_state passed to the new_output signal sometimes has a non-preferred mode set, which we were ignoring before 03be489eb973. Ignore it again to prevent the wrong mode from being set.
The first commit adds some debugging output which might be useful again in future, so I left it.
See discussion on #2458.
> output: ignore wlr_output_state.mode/custom_mode except for client request

- src/server.c
> src/server.c: delete a comment which was missed to erase in #1944

- include/common/scaled-img-buffer.h
- include/common/scaled-scene-buffer.h
- include/img/img.h
- src/img/img.c
> img: rename lab_img_cache to lab_img_data + add ASCII graphs

- README.md
- docs/labwc-theme.5.scd
- include/theme.h
- src/common/dir.c
- src/theme.c
Rationale in commit message.
Have set to draft because it could do with some more testing + discussion.
> Use 'labwc' directory for themes as well as 'openbox-3'

- src/xdg.c
assert found by 
https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4918
> xdg: cleanup request_show_window_menu listener when destroy

- include/view.h
- src/debug.c
- src/input/ime.c
- src/view.c
- src/xdg.c
- src/xwayland.c
To provide more type information
> view: replace content_node with content_tree

- include/common/scaled-img-buffer.h
- include/common/string-helpers.h
- include/desktop-entry.h
- include/img/img-svg.h
- include/img/img.h
- include/theme.h
- src/common/scaled-font-buffer.c
- src/common/scaled-img-buffer.c
- src/common/string-helpers.c
- src/img/img-svg.c
- src/img/img.c
- src/osd-field.c
- src/server.c
- src/ssd/ssd-part.c
- src/ssd/ssd-titlebar.c
- src/theme.c
Split from
- #2518
to ease review. Commits weren't changed other than rebased on master.
@tokyo4j: LGTM so feel free to get these ones into the master branch.
> prep: scaled window icons

- src/config/rcxml.c
Staging for https://github.com/labwc/labwc/pull/2427.
> config/rcxml.c: encapsulate parser state into a struct

- src/action.c
> action.c: add SSD margin to MoveTo coordinates

- README.md
inspired by https://forums.bunsenlabs.org/viewtopic.php?pid=141053#p141053
> README.md#Integration: add xfce4-panel

- src/input/keyboard.c
I find myself trying to select menu items with the keypad enter key all the time. I'm not a coder but this seems easy enough. Please forgive me if egregious!
> call selected menu action with keypad enter

- src/config/rcxml.c
...because the parser ignores empty nodes, so users cannot get rid of the previous default of "Workspace" without using <names> which is not that obvious.
This is a breaking change, but feels like a soft one for a good reason.
Fixes: #2601
> config: make prefix.desktops default to nothing

- src/menu/menu.c
> menu: show app icons in client-list-combined-menu

- src/menu/menu.c
Based on #2673.
I believe `!current_menu` is equivalent to `is_toplevel_static_menu_definition()`.
This PR and #2673 are not urgent, so delaying them to after the next release is totally fine.
> menu: refactor handle_menu_element() (part 2)

- docs/labwc-config.5.scd
> labwc-config(5): add mousebind direction example

- src/ssd/ssd-shadow.c
This simplifies `corner_scale_crop()`.
Just for testing, this PR also includes a commit that paints the corner shadow buffer with green.
CC @cillian64
> ssd-shadow: flip top-right/bottom-left corner instead of rotating

- src/input/keyboard.c
> keyboard.c: don't broadcast modifiers from virtual keyboards

- docs/labwc-actions.5.scd
> labwc-actions(5): add example for ShowMenu with wtype

- include/common/box.h
- src/common/box.c
- src/view.c
Wlroots now has `wlr_box_contains_box()`.
> common/box: drop box_contains()

- src/server.c
ref: https://github.com/swaywm/sway/commit/05e895c4638293a6bfe594ff0cae4eaab63b740e
feel free to edit if needed
> add linux_drm_syncobj_v1

- src/server.c
ref: https://github.com/swaywm/sway/commit/17e2e52c6d1bf4bfebde8f6b2869702aacc3750a
> drm_syncobj check backend support for timelines

- src/layers.c
> layer-shell: only configure initialized layer surfaces

- src/img/img-xbm.c
Background: we agreed on IRC to add `-Wshadow` compiler option in order to prevent unintended variable overrides.
This PR is a step forward to it, as compiling `img-xbm.c` with `-Wshadow` currently outputs warnings like:
```
[87/189] Compiling C object labwc.p/src_img_img-xbm.c.o
../src/img/img-xbm.c: In function ‘process_bytes’:
../src/img/img-xbm.c:177:52: warning: declaration of ‘tokens’ shadows a global declaration [-Wshadow]
177 | process_bytes(struct pixmap *pixmap, struct token *tokens)
|                                      ~~~~~~~~~~~~~~^~~~~~
../src/img/img-xbm.c:47:22: note: shadowed declaration is here
47 | static struct token *tokens;
|                      ^~~~~~
../src/img/img-xbm.c: In function ‘parse_xbm_tokens’:
../src/img/img-xbm.c:208:32: warning: declaration of …
```
> common/img/img-xbm: avoid using global variables

- docs/autostart
- docs/labwc-config.5.scd
- docs/labwc-menu.5.scd
for the wlr18 to 19 check list
ref: https://github.com/swaywm/sway/commit/10e50e6bf9b63b205c141f97a5709fd4d405542f
> doc: s/view/window/

- docs/labwc-config.5.scd
> docs: update documentations for osd fields

- src/view.c
> view: simplify freeing of view->icon

- src/ssd/ssd-titlebar.c
Closes #2859.
This PR works around #2859 by using `WLR_SCALE_FILTER_NEAREST` filter mode if pixman renderer is used.
> ssd: work around the translucent titlebar in pixman renderer

- NEWS.md
Just letting this one develop over the next couple of weeks.
> NEWS.md for the release

- src/menu/menu.c
The lifetime of the "current_" variables (current_menu, current_item, current_item_action) is very difficult to understand from reading the code. It appears that e.g. current_menu could still point to a previous menu when starting to parse a new one, with unpredictable results.
Let's use a context struct when parsing, and consistently initialize it when beginning to build a new menu.
Lightly tested with:
- default menus (no menu.xml)
- example static menu from labwc.github.io/getting-started.html
- an added "client-list-combined-menu" sub-menu
- pipe menu generated by `labwc-menu-generator -p`
Includes one commit from #2884 to avoid conflicts.
> menu: add struct menu_parse_context to reduce static vars

- .github/workflows/build.yml
- include/layers.h
- src/layers.c
- src/xdg-popup.c
- src/xdg.c
Backport of 30248e1ba3b651b70f9cf525945e084fd88bfae4
Fixes:
- #2955
> [v0.8] Backport of "Destroy xdg_popups when its parent is destroyed"

- src/action.c
As I proposed in https://github.com/labwc/labwc/pull/2699#issuecomment-3082599289.
I think this PR also makes the logic easier to follow.
I advise you to use "hide whitespaces" feature when reviewing this PR with GitHub's diff viewer.
> action: refactor in preparation for labnag

- src/menu/menu.c
> menu: fix segfault with toplevel <separator>

- src/input/cursor.c
Self-explanatory, I think.
edit: also, cheers to PR 3000 :)
> input/cursor: fix assignment/equality mix-up

- docs/rc.xml.all
> docs/rc.xml.all: clean up libinput section.

- clients/labnag.c
> clients/labnag.c: add newline to color errors.

- clients/labnag.c
> labnag: s/nag/labnag/ in usage string

- clients/labnag.c
- docs/labwc-config.5.scd
- docs/rc.xml.all
- include/action-prompt-command.h
- include/action.h
- include/common/buf.h
- include/config/rcxml.h
- src/action-prompt-command.c
- src/action.c
- src/common/buf.c
- src/config/rcxml.c
- src/meson.build
-- EDIT --
See commit messages for description.
With zenity:
> config: add `<core><promptCommand>`

- include/common/string-helpers.h
- include/common/xml.h
- include/input/key-state.h
- include/menu/menu.h
- include/node.h
- include/output.h
- include/scaled-buffer/scaled-font-buffer.h
- src/common/string-helpers.c
- src/common/xml.c
- src/input/key-state.c
- src/menu/menu.c
- src/node.c
- src/output.c
- src/scaled-buffer/scaled-font-buffer.c
> Remove unused functions

- include/action.h
- src/action.c
- src/server.c
Reported-by: @jlindgren90
Fixes #3106
> action: fix UAF when using prompt during reconfigure

- include/config/rcxml.h
- include/labwc.h
- include/output.h
- include/view.h
- include/xwayland.h
- meson.build
- meson_options.txt
- src/config/rcxml.c
- src/desktop.c
- src/output.c
- src/view.c
- src/xwayland.c
> Add build option to show unused functions; and make some functions private
